/* pages-dash.js — shared page helpers + role dashboards */
(function (G) {
  'use strict';
  const C = G.C, S = G.S, UI = G.UI, esc = C.esc, App = G.App;
  const Pages = G.Pages = G.Pages || {};
  const H = G.H = {};

  /* ---------- helpers reused across pages ---------- */
  H.dtbox = d => `<div class="dtbox"><b>${C.pd(d).getDate()}</b><span>${C.MONTHS[C.pd(d).getMonth()].slice(0, 3)}</span></div>`;
  H.evTag = t => ({ holiday: ['Holiday', 'bad'], public: ['Public holiday', 'gold'], exam: ['Exam', 'navy'], event: ['Event', 'ok'], ptm: ['Parent meeting', 'info'], special: ['Special', 'navy'] }[t] || [t, '']);
  H.eventList = (evs, empty) => evs.length ? evs.map(e => { const [l, k] = H.evTag(e.type); return `<div class="list-i">${H.dtbox(e.date)}<div class="grow"><b>${esc(e.title)}</b><div class="muted small">${e.end !== e.date ? C.fmtDate(e.date) + ' – ' + C.fmtDate(e.end) : C.fmtDateLong(e.date)}</div></div>${UI.badge(l, k)}</div>`; }).join('') : UI.empty(empty || 'Nothing scheduled');
  H.upcoming = (u, types, n = 5) => { const T = C.today(); return S.calendarFor(u).filter(e => types.includes(e.type) && e.end >= T).sort((a, b) => a.date.localeCompare(b.date)).slice(0, n); };
  H.annList = (list, n = 4) => list.length ? list.slice(0, n).map(a => `<div class="list-i"><div class="avatar sm" style="background:${a.type === 'emergency' ? 'var(--bad)' : 'var(--navy-700)'}">${UI.icon(a.type === 'exam' ? 'clipboard' : a.type === 'holiday' ? 'sun' : a.type === 'fee' ? 'rupee' : 'bell', 14)}</div><div class="grow"><b>${esc(a.title)}</b><div class="muted small" style="margin:2px 0 3px">${esc(a.body.length > 130 ? a.body.slice(0, 127) + '…' : a.body)}</div><span class="tiny muted">${C.fmtDate(a.ts)} · ${esc(S.audienceLabel(a.audience))} · ${esc(a.by)}</span></div></div>`).join('') : UI.empty('No announcements');
  H.ttDay = () => S.ttDayFor();
  H.dayNote = td => td.isToday ? '' : `<span class="badge nodot warn">Showing ${C.DAYS[td.day]} – next school day</span>`;
  H.periodRow = (p, content, isNow, free) => `<div class="it ${isNow ? 'now' : ''} ${free ? 'free' : ''}"><div class="tm"><b>Period ${p.p}</b>${C.t12(p.s)} – ${C.t12(p.e)}</div>${content}</div>`;
  H.brkRow = b => `<div class="it" style="background:#fafbfd;padding:6px 18px"><div class="tm" style="grid-column:1/-1;text-align:center;letter-spacing:.1em;text-transform:uppercase;font-size:10.5px">${b.brk} · ${C.t12(b.s)} – ${C.t12(b.e)}</div></div>`;
  H.classSched = (cid, td) => { const cp = td.isToday ? C.currentPeriod() : null; return `<div class="sched">${C.PERIODS.map(p => { if (p.brk) return H.brkRow(p); const cell = S.ttCell(cid, td.day, p.p); if (!cell) return H.periodRow(p, '<div>Free period</div><div></div>', cp && cp.p === p.p, true); const t = S.emp(cell.teacherId); return H.periodRow(p, `<div><b>${esc(cell.subject)}</b><div class="muted small">${esc(t ? t.name : '—')} · ${esc(cell.room || '')}</div></div><div>${cp && cp.p === p.p ? UI.badge('Now', 'gold') : ''}</div>`, cp && cp.p === p.p); }).join('')}</div>`; };
  H.teacherSched = (eid, td) => { const g = S.teacherTT(eid)[td.day] || {}; const cp = td.isToday ? C.currentPeriod() : null; return `<div class="sched">${C.PERIODS.map(p => { if (p.brk) return H.brkRow(p); const cell = g[p.p]; const now = cp && cp.p === p.p; if (!cell) return H.periodRow(p, '<div>Free period</div><div></div>', now, true); return H.periodRow(p, `<div><b>${esc(S.className(cell.classId))} · ${esc(cell.subject)}</b><div class="muted small">Room: ${esc(cell.room || '')}</div></div><div>${now ? UI.badge('Now', 'gold') : ''}</div>`, now); }).join('')}</div>`; };
  H.ttGrid = (getCell, opts = {}) => {
    const T = C.dow(C.today()), cp = C.currentPeriod(); const sel = (App.st('ttday').d != null ? App.st('ttday').d : (T < 6 ? T : 0));
    const table = `<div class="tt-wrap"><table class="tt"><thead><tr><th></th>${C.DAYS.map((d, i) => `<th class="${i === T ? 'today' : ''}">${d}</th>`).join('')}</tr></thead><tbody>${C.PERIODS.map(p => p.brk ? `<tr><td class="brk" colspan="7">${p.brk} · ${C.t12(p.s)} – ${C.t12(p.e)}</td></tr>` : `<tr><td>P${p.p}<div class="muted tiny" style="font-weight:400">${C.t12(p.s)}–${C.t12(p.e)}</div></td>${C.DAYS.map((d, i) => { const r = getCell(i, p.p); const now = cp && cp.p === p.p && i === T; return `<td class="${now ? 'now' : i === T ? 'todaycol' : ''} ${r.cls || ''}" ${r.attr || ''}>${r.html}</td>`; }).join('')}</tr>`).join('')}</tbody></table></div>`;
    const mobile = `<div class="tt-mobile"><div class="day-pills">${C.DAYS.map((d, i) => `<button class="${i === sel ? 'on' : ''}" data-act="ttDay" data-d="${i}">${d.slice(0, 3)}${i === T ? '<i></i>' : ''}</button>`).join('')}</div>${C.DAYS.map((d, i) => `<div class="tt-day" data-day="${i}" style="display:${i === sel ? 'block' : 'none'}">${C.PERIODS.map(p => { if (p.brk) return `<div class="tt-brk">${p.brk} · ${C.t12(p.s)} – ${C.t12(p.e)}</div>`; const r = getCell(i, p.p); const now = cp && cp.p === p.p && i === T; return `<div class="tt-row ${now ? 'now' : ''} ${r.cls || ''}" ${r.attr || ''}><div class="tm"><b>P${p.p}</b>${C.t12(p.s)}<br>${C.t12(p.e)}</div><div class="tc">${r.html}</div></div>`; }).join('')}</div>`).join('')}</div>`;
    return table + mobile;
  };
  UI.act.ttDay = t => { App.st('ttday').d = +t.dataset.d; const wrap = t.closest('.tt-mobile'); wrap.querySelectorAll('.day-pills button').forEach(b => b.classList.toggle('on', b === t)); wrap.querySelectorAll('.tt-day').forEach(x => x.style.display = x.dataset.day === t.dataset.d ? 'block' : 'none'); };
  H.sparkAtt = pct => UI.progress(pct);
  H.monthsAY = () => { const out = []; let m = S.db().ayStart.slice(0, 7); const cur = C.today().slice(0, 7); while (m <= cur) { out.push(m); const [y, mm] = m.split('-').map(Number); m = mm === 12 ? (y + 1) + '-01' : y + '-' + C.pad(mm + 1); } return out; };
  H.attDates = (n = 20) => S.attDates().filter(d => S.dayAtt(d).classes >= 12).slice(-n);
  H.finMonthly = () => { const ms = H.monthsAY(); const col = S.monthlyCollection(); const exp = {}; S.db().expenses.forEach(e => { const k = e.date.slice(0, 7); exp[k] = (exp[k] || 0) + e.amount; }); return { ms, income: ms.map(m => col[m] || 0), salary: ms.map(m => S.salaryExpense(m)), other: ms.map(m => exp[m] || 0) }; };
  H.latestExam = () => { const ex = S.db().exams.filter(x => S.examStatus(x) === 'Completed'); return ex[ex.length - 1] || null; };
  H.classPerf = exId => S.classes().map(c => ({ c, avg: S.classExam(c.id, exId).avg }));
  H.alertRow = (tone, icon, text, href) => `<a class="alert ${tone}" style="text-decoration:none;margin-bottom:8px" href="${href || '#/dashboard'}">${UI.icon(icon, 17)}<div class="grow">${text}</div>${UI.icon('chevR', 15)}</a>`;
  H.greet = (u, sub) => `<div class="dash-head"><div><h1>${u.role === 'principal' ? "Principal's Dashboard" : u.role === 'dean' ? 'Academic Dashboard' : u.role === 'accountant' ? 'Accounts Dashboard' : u.role === 'teacher' ? 'Teacher Dashboard' : u.role === 'ops' ? 'Operations Dashboard' : 'Administration Dashboard'}</h1><p>${C.fmtDateLong(C.today())} · Academic year ${S.db().ay}</p></div></div><!--Q-->${sub ? `<div class="note-line mb">${sub}</div>` : ''}`;
  H.tiles = list => `<div class="quick-grid mb">${list.map(q => `<a class="qt" ${q[3] ? `href="#" data-act="${q[3]}"` : `href="${q[2]}"`}><span class="qi">${UI.icon(q[0], 22)}</span><span><b>${q[1]}</b>${q[5] ? `<small>${q[5]}</small>` : ''}</span></a>`).join('')}</div>`;
  H.quick = list => `<div class="tasks-line"><b>Quick links</b>${list.map(q => `<a ${q[3] ? `href="#" data-act="${q[3]}"` : `href="${q[2]}"`}>${q[1]}</a>`).join('')}</div>`;

  /* ---------- Principal ---------- */
  function dashPrincipal(ctx) {
    const db = S.db(), T = C.today(), sd = S.schoolDay(), u = ctx.u; const ft = S.feeTotals(), att = S.dayAtt(sd), tatt = S.teacherAtt(sd) || { P: 0, total: 0, pct: 0, A: 0 };
    const mk = T.slice(0, 7); const teachers = S.teachers(); const tSal = C.sum(S.payrollFor(mk).filter(r => S.emp(r.empId).role === 'teacher'), r => r.net), allSal = S.salaryExpense(mk); const otherExp = C.sum(db.expenses.filter(e => e.date.startsWith(mk)), e => e.amount);
    const overdue = db.students.map(s => S.feeInfo(s.id)).filter(f => f.status === 'Overdue'); const pm = S.pendingMarks(); const low = db.students.filter(s => S.studentAtt(s.id).pct < 75);
    const lvPending = db.leaves.filter(l => l.status === 'Pending').length; const hiMaint = db.maint.filter(m => m.priority === 'High' && m.status !== 'Resolved').length; const taskAtt = db.tasks.filter(t => t.status === 'Requires Attention' && t.date >= C.addDays(T, -2)).length;
    const fin = H.finMonthly(); const ex = H.latestExam(); const tk = db.tasks.filter(t => t.date === sd); const tkDone = tk.filter(t => t.status === 'Completed').length;
    const ad = H.attDates(18); const exPerf = db.exams.filter(x => S.examStatus(x) === 'Completed').map(x => { const all = S.classes().map(c => S.classExam(c.id, x.id)); const n = C.sum(all, a => a.n), p = C.sum(all, a => a.pass); return { x, avg: C.avg(all.filter(a => a.res.length), a => a.avg), pass: C.pct(p, n) }; });
    const cumul = []; fin.income.reduce((a, v, i) => (cumul[i] = a + v), 0);
    const catTot = {}; db.expenses.forEach(e => catTot[e.category] = (catTot[e.category] || 0) + e.amount);
    const alerts = [];
    if (att.classes < db.classes.length) alerts.push(H.alertRow('', 'check', `<b>${db.classes.length - att.classes} of ${db.classes.length} classes</b> have not submitted attendance for ${C.fmtDate(sd)}.`, '#/attendance'));
    if (overdue.length) alerts.push(H.alertRow('bad', 'rupee', `<b>${overdue.length} students</b> have overdue fees totalling <b>${C.inr(C.sum(overdue, f => f.overdueAmt))}</b>.`, '#/fees'));
    if (pm.filter(p => p.status === 'submitted').length) alerts.push(H.alertRow('info', 'clipboard', `<b>${pm.filter(p => p.status === 'submitted').length} mark sheets</b> are awaiting the Dean's approval.`, '#/marks'));
    if (hiMaint) alerts.push(H.alertRow('bad', 'wrench', `<b>${hiMaint} high-priority maintenance</b> request${hiMaint > 1 ? 's' : ''} still open.`, '#/operations'));
    if (lvPending) alerts.push(H.alertRow('', 'clock', `<b>${lvPending} teacher leave request${lvPending > 1 ? 's' : ''}</b> awaiting your decision.`, '#/teachers'));
    if (low.length) alerts.push(H.alertRow('', 'alert', `<b>${low.length} students</b> have attendance below 75%.`, '#/attendance'));
    if (taskAtt) alerts.push(H.alertRow('', 'sparkle', `<b>${taskAtt} cleaning task${taskAtt > 1 ? 's' : ''}</b> flagged “Requires Attention”.`, '#/operations'));
    const enq = db.enquiries.filter(e => e.status === 'New').length; if (enq) alerts.push(H.alertRow('ok', 'userplus', `<b>${enq} new admission enquir${enq > 1 ? 'ies' : 'y'}</b> received from the website.`, '#/settings'));
    return H.greet(u, `${att.classes ? 'Attendance so far on ' + C.fmtDate(sd) + ': <b>' + att.pct + '%</b> across ' + att.classes + ' classes' : 'Attendance not yet submitted for today'} · Fees collected today <b>${C.inr(ft.today)}</b>`) +
      `<div class="grid g6">${UI.kpi({ label: 'Total students', value: C.num(db.students.length), sub: db.classes.length + ' classes · Classes 1–10', icon: 'users', href: '#/students' })}${UI.kpi({ label: 'Teaching staff', value: teachers.length, sub: 'Teacher attendance today ' + tatt.pct + '%', icon: 'user', href: '#/teachers' })}${UI.kpi({ label: 'Non-teaching staff', value: db.employees.length - teachers.length, sub: 'Admin, accounts, operations', icon: 'building', href: '#/staff' })}${UI.kpi({ label: 'Classes / sections', value: db.classes.length, sub: 'Class teachers assigned: ' + db.classes.filter(c => c.classTeacherId).length, icon: 'book', href: '#/classes' })}
      ${UI.kpi({ label: 'Student attendance' + (sd === T ? ' today' : ' · ' + C.fmtDate(sd)), value: att.classes ? att.pct + '%' : '—', sub: `${att.P + att.L} present · ${att.A} absent · ${att.V} leave`, icon: 'check', tone: att.pct >= 92 ? 'ok' : 'warn', href: '#/attendance' })}${UI.kpi({ label: 'Teacher attendance', value: tatt.total ? tatt.P + ' / ' + tatt.total : '—', sub: tatt.total ? tatt.pct + '% present · ' + tatt.A + ' absent' : 'Not marked yet', icon: 'user', tone: 'gold', href: '#/attendance' })}${UI.kpi({ label: 'Fees collected today', value: C.inr(ft.today), sub: 'This month ' + C.inr(ft.month), icon: 'rupee', tone: 'ok', href: '#/fees' })}${UI.kpi({ label: 'Collected this academic year', value: C.inrK(ft.year), sub: C.pct(ft.collected, ft.expected, 0) + '% of ' + C.inrK(ft.expected) + ' expected', icon: 'wallet', tone: 'ok', href: '#/finance' })}
      ${UI.kpi({ label: 'Pending fees', value: C.inrK(ft.pending), sub: ft.status.Overdue + ' students overdue', icon: 'alert', tone: 'bad', href: '#/fees' })}${UI.kpi({ label: 'Teacher salary expense', value: C.inrK(tSal), sub: 'Teaching staff · ' + C.monthLong(mk), icon: 'receipt', tone: 'gold', href: '#/payroll' })}${UI.kpi({ label: 'Total payroll (all staff)', value: C.inrK(allSal), sub: C.num(db.employees.length) + ' employees · ' + C.monthLong(mk), icon: 'users', href: '#/payroll' })}${UI.kpi({ label: 'Other school expenses', value: C.inrK(otherExp), sub: 'Operations, utilities · this month', icon: 'trend', tone: 'warn', href: '#/finance' })}</div>
      <div class="grid g-21 mt"><div class="grid" style="gap:16px">${UI.card('Monthly fee collection', UI.chart.bars({ labels: fin.ms.map(C.monthLabel), series: [{ name: 'Fees collected', data: fin.income }], fmt: C.inrK, height: 230 }), { sub: 'Academic year ' + db.ay + ' · all payment channels' })}
        <div class="grid g2">${UI.card('Student attendance trend', UI.chart.line({ labels: ad.map(d => C.pd(d).getDate() + ' ' + C.MONTHS[C.pd(d).getMonth()].slice(0, 3)), series: [{ name: 'Attendance %', data: ad.map(d => S.dayAtt(d).pct), color: UI.PAL[0] }], ymin: 80, ymax: 100, fmt: v => v + '%', area: true, height: 220 }), { sub: 'Last ' + ad.length + ' school days' })}${UI.card('Teacher attendance trend', UI.chart.line({ labels: ad.map(d => C.pd(d).getDate() + ' ' + C.MONTHS[C.pd(d).getMonth()].slice(0, 3)), series: [{ name: 'Teachers present %', data: ad.map(d => (S.teacherAtt(d) || { pct: 0 }).pct), color: UI.PAL[2] }], ymin: 80, ymax: 100, fmt: v => v + '%', area: true, height: 220 }), { sub: 'Daily presence of teaching staff' })}</div></div>
      <div class="grid" style="gap:16px">${UI.card('Important alerts', alerts.join('') || '<div class="alert ok">All systems normal – nothing needs attention.</div>', { sub: 'Things that need your attention' })}${UI.card('Fee status', UI.chart.donut({ items: [{ label: 'Paid', value: ft.status.Paid, color: '#1b7f57' }, { label: 'Partially paid', value: ft.status['Partially Paid'], color: '#25609f' }, { label: 'Pending', value: ft.status.Pending, color: '#d99a2b' }, { label: 'Overdue', value: ft.status.Overdue, color: '#b3261e' }], center: db.students.length, centerLabel: 'STUDENTS' }), { sub: 'Pending fees by payment status' })}</div></div>
      <div class="grid g2 mt">${UI.card('Class performance' + (ex ? ' – ' + ex.name : ''), ex ? UI.chart.bars({ labels: S.classes().map(c => S.clsShort(c.id)), series: [{ name: 'Average %', data: S.classes().map(c => +S.classExam(c.id, ex.id).avg.toFixed(1)), color: UI.PAL[0] }], fmt: v => v + '%', ymax: 100, height: 230 }) : UI.empty('No completed exams'), { sub: 'Average percentage of published results' })}${UI.card('Examination performance', UI.chart.bars({ labels: exPerf.map(e => e.x.name), series: [{ name: 'Average %', data: exPerf.map(e => +e.avg.toFixed(1)), color: UI.PAL[0] }, { name: 'Pass %', data: exPerf.map(e => +e.pass.toFixed(1)), color: UI.PAL[2] }], fmt: v => v + '%', ymax: 100, height: 230 }), { sub: 'Whole-school results by examination' })}</div>
      <div class="grid g3 mt">${UI.card('School income vs expenses', UI.chart.bars({ labels: fin.ms.map(C.monthLabel), series: [{ name: 'Income', data: fin.income, color: UI.PAL[2] }, { name: 'Salaries', data: fin.salary, color: UI.PAL[0] }, { name: 'Operational', data: fin.other, color: UI.PAL[1] }], fmt: C.inrK, height: 230 }), { sub: 'Monthly, this academic year' })}${UI.card('Cumulative fee collection', UI.chart.line({ labels: fin.ms.map(C.monthLabel), series: [{ name: 'Collected to date', data: cumul, color: UI.PAL[1] }], fmt: C.inrK, area: true, height: 230 }), { sub: 'Year-to-date vs ' + C.inrK(ft.expected) + ' expected' })}${UI.card('Operational expenses by category', UI.chart.hbars({ items: Object.entries(catTot).sort((a, b) => b[1] - a[1]).slice(0, 6).map(([k, v]) => ({ label: k, value: v })), fmt: C.inrK }), { sub: 'Year-to-date' })}</div>
      <div class="grid g4 mt">${UI.card('Upcoming examinations', H.upcomingExams(), { flush: true })}${UI.card('Upcoming holidays', H.eventList(H.upcoming(u, ['holiday', 'public'], 4)), { flush: true })}${UI.card('Upcoming events', H.eventList(H.upcoming(u, ['event', 'ptm', 'special'], 4)), { flush: true })}${UI.card('Operations snapshot', `<div class="col" style="gap:14px"><div><div class="row between small"><span>Tasks completed (${C.fmtDay(sd)})</span><b>${tkDone}/${tk.length}</b></div>${UI.progress(C.pct(tkDone, tk.length), '')}</div><div class="row between small"><span>Open maintenance requests</span><b>${db.maint.filter(m => m.status !== 'Resolved').length}</b></div><div class="row between small"><span>Tasks requiring attention</span><b>${tk.filter(t => t.status === 'Requires Attention').length}</b></div><div class="row between small"><span>Verified by supervisor</span><b>${tk.filter(t => t.verified).length}</b></div><a class="btn sm" href="#/operations">Open operations</a></div>`)}</div>
      <div class="mt">${UI.card('Recent announcements', H.annList(S.announcementsFor(u), 4), { flush: true, actions: '<a class="btn sm" href="#/announcements">View all</a>' })}</div>`;
  }
  H.upcomingExams = () => { const l = S.db().exams.filter(x => S.examStatus(x) !== 'Completed').slice(0, 4); return l.length ? l.map(x => `<div class="list-i">${H.dtbox(x.schedule[0].date)}<div class="grow"><b>${esc(x.name)}</b><div class="muted small">${C.fmtDate(x.schedule[0].date)} – ${C.fmtDate(x.schedule[x.schedule.length - 1].date)}</div></div>${UI.status(S.examStatus(x))}</div>`).join('') : UI.empty('No upcoming exams'); };

  /* ---------- Dean ---------- */
  function dashDean(ctx) {
    const db = S.db(), u = ctx.u, sd = S.schoolDay(); const att = S.dayAtt(sd), pm = S.pendingMarks(); const ex = H.latestExam(); const ts = S.teachers();
    const sub = C.EXAM_SUBJECTS.map(s => ({ s, v: ex ? C.avg(S.classes(), c => S.subjectAvg(ex.id, c.id, s) || 0) : 0 }));
    const noCT = db.classes.filter(c => !c.classTeacherId);
    return H.greet(u, `${pm.filter(p => p.status === 'submitted').length} mark sheets are waiting for your review · ${db.exams.filter(x => S.examStatus(x) === 'Upcoming').length} upcoming examinations`) +
      `<div class="grid g4">${UI.kpi({ label: 'Classes & sections', value: db.classes.length, sub: 'Class teachers: ' + (db.classes.length - noCT.length) + '/' + db.classes.length, icon: 'book', href: '#/classes' })}${UI.kpi({ label: 'Teachers', value: ts.length, sub: 'Subjects taught: ' + C.SUBJECTS.length, icon: 'user', href: '#/teachers' })}${UI.kpi({ label: 'Student attendance', value: att.classes ? att.pct + '%' : '—', sub: att.classes + ' of ' + db.classes.length + ' classes marked · ' + C.fmtDay(sd), icon: 'check', tone: 'ok', href: '#/attendance' })}${UI.kpi({ label: 'Marks awaiting approval', value: pm.filter(p => p.status === 'submitted').length, sub: pm.filter(p => p.status !== 'submitted').length + ' not yet submitted by teachers', icon: 'award', tone: 'gold', href: '#/marks' })}</div>
      <div class="grid g-21 mt"><div class="grid g2">${UI.card('Class performance' + (ex ? ' – ' + ex.name : ''), ex ? UI.chart.bars({ labels: S.classes().map(c => S.clsShort(c.id)), series: [{ name: 'Average %', data: S.classes().map(c => +S.classExam(c.id, ex.id).avg.toFixed(1)) }], fmt: v => v + '%', ymax: 100, height: 220 }) : '', { sub: 'Published results only' })}${UI.card('Subject performance', ex ? UI.chart.hbars({ items: sub.map(x => ({ label: x.s, value: +x.v.toFixed(1) })), fmt: v => v + '%', max: 100 }) : '', { sub: 'School average per subject' })}</div>
      ${UI.card('Marks review queue', pm.filter(p => p.status === 'submitted').slice(0, 6).map(p => `<div class="list-i"><div class="grow"><b>${esc(p.cls.name)} · ${esc(p.subject)}</b><div class="muted small">${esc(p.exam.name)} · ${esc(S.emp(p.teacherId).name)}</div></div><a class="btn xs primary" href="#/marks?e=${p.exam.id}&c=${p.cls.id}&s=${encodeURIComponent(p.subject)}">Review</a></div>`).join('') || UI.empty('Queue is clear'), { flush: true, actions: '<a class="btn sm" href="#/marks">Open</a>' })}</div>
      <div class="grid g3 mt">${UI.card('Teacher workload (periods / week)', UI.chart.hbars({ items: ts.map(t => ({ label: t.name, value: S.teacherLoad(t.id) })).sort((a, b) => b.value - a.value).slice(0, 8), max: 42, fmt: v => v + ' / 42' }), { sub: 'Top 8 of ' + ts.length })}${UI.card('Upcoming examinations', H.upcomingExams(), { flush: true, actions: '<a class="btn sm" href="#/exams">Manage</a>' })}${UI.card('Class teachers', noCT.length ? noCT.map(c => `<div class="list-i"><div class="grow"><b>${c.name}</b><div class="muted small">No class teacher assigned</div></div><a class="btn xs" href="#/classteachers">Assign</a></div>`).join('') : `<div class="alert ok">${UI.icon('check', 16)} Every class has an assigned class teacher.</div><div class="mt-s small muted">Reassign any time under Class Teachers – the teacher's dashboard updates instantly.</div>`, {})}</div>
      <div class="grid g2 mt">${UI.card('Recent announcements', H.annList(S.announcementsFor(u), 3), { flush: true })}${UI.card('Upcoming events & holidays', H.eventList(H.upcoming(u, ['event', 'ptm', 'special', 'holiday', 'public'], 4)), { flush: true })}</div>`;
  }

  /* ---------- Accountant ---------- */
  function dashAccountant(ctx) {
    const db = S.db(), u = ctx.u, T = C.today(), mk = T.slice(0, 7); const ft = S.feeTotals(), fin = H.finMonthly(); const pr = S.payrollFor(mk); const pend = pr.filter(r => r.status !== 'Paid');
    const cls = S.classes().map(c => ({ c, f: S.classFee(c.id) })); const recent = db.payments.slice().sort((a, b) => b.ts.localeCompare(a.ts)).slice(0, 6);
    const exp = C.sum(db.expenses.filter(e => e.date.startsWith(mk)), e => e.amount);
    const dues = db.students.map(s => ({ s, f: S.feeInfo(s.id) })).filter(x => x.f.next && x.f.balance > 0 && x.f.next.due >= T && x.f.next.due <= C.addDays(T, 30)).length;
    return H.greet(u, `${ft.status.Overdue} students have overdue fees · ${pend.length} salaries pending for ${C.monthLong(mk)}`) +
      `<div class="grid g4">${UI.kpi({ label: 'Collected today', value: C.inr(ft.today), sub: db.payments.filter(p => p.date === T).length + ' receipts issued', icon: 'rupee', tone: 'ok', href: '#/receipts' })}${UI.kpi({ label: 'Collected this month', value: C.inr(ft.month), sub: C.monthLong(mk), icon: 'wallet', tone: 'ok', href: '#/reports' })}${UI.kpi({ label: 'Collected this year', value: C.inrK(ft.collected), sub: C.pct(ft.collected, ft.expected, 0) + '% of ' + C.inrK(ft.expected), icon: 'trend', href: '#/reports' })}${UI.kpi({ label: 'Pending balance', value: C.inrK(ft.pending), sub: ft.status.Overdue + ' overdue · ' + ft.status.Pending + ' pending', icon: 'alert', tone: 'bad', href: '#/pending' })}</div>
      <div class="grid g4 mt">${UI.kpi({ label: 'Salary payable (' + C.monthLabel(mk) + ')', value: C.inrK(C.sum(pend, r => r.net)), sub: pend.length + ' of ' + pr.length + ' not paid', icon: 'receipt', tone: 'gold', href: '#/payroll' })}${UI.kpi({ label: 'Expenses this month', value: C.inrK(exp), sub: 'Recorded vouchers', icon: 'trend', tone: 'warn', href: '#/expenses' })}${UI.kpi({ label: 'Instalments due ≤ 30 days', value: dues, sub: 'Send reminders from Pending Fees', icon: 'clock', href: '#/pending' })}${UI.kpi({ label: 'Online payments', value: C.inrK(C.sum(db.payments.filter(p => p.mode === 'Online'), p => p.amount)), sub: db.payments.filter(p => p.mode === 'Online').length + ' via parent portal', icon: 'globe', href: '#/receipts' })}</div>
      <div class="grid g-21 mt">${UI.card('Monthly collection vs expenses', UI.chart.bars({ labels: fin.ms.map(C.monthLabel), series: [{ name: 'Fees collected', data: fin.income, color: UI.PAL[2] }, { name: 'Salaries', data: fin.salary, color: UI.PAL[0] }, { name: 'Other expenses', data: fin.other, color: UI.PAL[1] }], fmt: C.inrK, height: 240 }), { sub: 'Academic year ' + db.ay })}${UI.card('Fee status', UI.chart.donut({ items: [{ label: 'Paid', value: ft.status.Paid, color: '#1b7f57' }, { label: 'Partially paid', value: ft.status['Partially Paid'], color: '#25609f' }, { label: 'Pending', value: ft.status.Pending, color: '#d99a2b' }, { label: 'Overdue', value: ft.status.Overdue, color: '#b3261e' }], center: db.students.length, centerLabel: 'STUDENTS' }))}</div>
      <div class="grid g-21 mt">${UI.card('Class-wise pending amount', UI.chart.bars({ labels: cls.map(x => S.clsShort(x.c.id)), series: [{ name: 'Pending', data: cls.map(x => x.f.pending), color: UI.PAL[3] }], fmt: C.inrK, height: 220 }), { sub: 'Outstanding balance by class' })}${UI.card('Recent receipts', recent.map(p => { const s = S.student(p.sid); return `<div class="list-i"><div class="grow"><b>${esc(s.name)}</b><div class="muted small">${p.rcpt} · ${esc(S.className(s.classId))} · ${esc(p.method)}</div></div><div class="right"><b>${C.inr(p.amount)}</b><div class="tiny muted">${C.fmtDate(p.date)}</div></div></div>`; }).join(''), { flush: true, actions: '<a class="btn sm" href="#/receipts">All receipts</a>' })}</div>
      <div class="mt">${UI.card('Announcements', H.annList(S.announcementsFor(u), 3), { flush: true })}</div>`;
  }

  /* ---------- Teacher ---------- */
  function dashTeacher(ctx) {
    const db = S.db(), u = ctx.u, e = S.emp(u.empId), ct = S.classTeacherClass(e.id), td = H.ttDay(), sd = S.schoolDay(); const tc = S.teacherClasses(e.id);
    const today = S.teacherTT(e.id)[td.day] || {}; const nToday = Object.keys(today).length; const subs = Array.from(new Set(Object.values(tc).flat()));
    const attDone = ct ? !!S.classAtt(ct.id, sd) : true; const pm = S.pendingMarks().filter(p => p.teacherId === e.id && p.status !== 'submitted');
    const upExams = db.exams.filter(x => S.examStatus(x) !== 'Completed').slice(0, 3);
    return H.greet(u, `${ct ? 'Class Teacher – <b>' + ct.name + '</b> · ' : ''}${e.designation} · ${e.dept}`) +
      `<div class="grid g4">${UI.kpi({ label: "Today's periods", value: nToday, sub: td.isToday ? C.DAYS[td.day] : 'Next: ' + C.DAYS[td.day], icon: 'calendar', href: '#/timetables' })}${UI.kpi({ label: 'Assigned classes', value: Object.keys(tc).length, sub: subs.join(', ') || '—', icon: 'book', href: '#/myclasses' })}${UI.kpi({ label: 'Attendance task', value: ct ? (attDone ? 'Done' : 'Pending') : 'N/A', sub: ct ? (attDone ? ct.name + ' marked for ' + C.fmtDay(sd) : ct.name + ' not marked yet') : 'You are not a class teacher', icon: 'check', tone: ct ? (attDone ? 'ok' : 'warn') : '', href: '#/attendance' })}${UI.kpi({ label: 'Pending mark entry', value: pm.length, sub: pm.length ? 'Entry/updates required' : 'All up to date', icon: 'award', tone: pm.length ? 'warn' : 'ok', href: '#/marks' })}</div>
      ${ct && !attDone ? `<div class="alert mt">${UI.icon('alert', 17)}<div class="grow"><b>Attendance for ${ct.name} has not been submitted</b> for ${C.fmtDate(sd)}.</div><a class="btn sm primary" href="#/attendance">Mark attendance</a></div>` : ''}
      <div class="grid g-21 mt">${UI.card("Today's timetable", H.teacherSched(e.id, td), { flush: true, sub: C.fmtDateLong(td.date), actions: H.dayNote(td) + '<a class="btn sm" href="#/timetables">Weekly view</a>' })}<div class="grid" style="gap:16px">${UI.card('Assigned classes', Object.entries(tc).map(([cid, sb]) => `<div class="list-i"><div class="grow"><b>${S.className(cid)} ${ct && ct.id === cid ? UI.badge('Class teacher', 'gold') : ''}</b><div class="muted small">${sb.join(', ') || 'Class teacher'} · ${S.studentsOf(cid).length} students</div></div><a class="btn xs" href="#/myclasses/${cid}">Open</a></div>`).join('') || UI.empty('No classes assigned'), { flush: true })}${UI.card('Pending mark entry', pm.slice(0, 5).map(p => `<div class="list-i"><div class="grow"><b>${p.cls.name} · ${p.subject}</b><div class="muted small">${esc(p.exam.name)} · ${p.status === 'draft' ? 'Draft saved' : 'Not started'}</div></div><a class="btn xs primary" href="#/marks?e=${p.exam.id}&c=${p.cls.id}&s=${encodeURIComponent(p.subject)}">Enter</a></div>`).join('') || UI.empty('No pending mark entry'), { flush: true })}</div></div>
      <div class="grid g3 mt">${UI.card('Upcoming examinations', upExams.length ? upExams.map(x => `<div class="list-i">${H.dtbox(x.schedule[0].date)}<div class="grow"><b>${esc(x.name)}</b><div class="muted small">${C.fmtDate(x.schedule[0].date)} – ${C.fmtDate(x.schedule[x.schedule.length - 1].date)}</div></div></div>`).join('') : UI.empty('None scheduled'), { flush: true })}${UI.card('Holidays & events', H.eventList(H.upcoming(u, ['holiday', 'public', 'event', 'ptm', 'special'], 4)), { flush: true })}${UI.card('Announcements', H.annList(S.announcementsFor(u), 3), { flush: true, actions: '<a class="btn sm" href="#/announcements">All</a>' })}</div>`;
  }

  /* ---------- Parent / Student (one shared portal) ---------- */
  function dashFamily(ctx) {
    const u = ctx.u, s = S.student(u.studentId), c = S.cls(s.classId), ct = S.emp(c.classTeacherId), att = S.studentAtt(s.id), fi = S.feeInfo(s.id), td = H.ttDay(), sd = S.schoolDay(), T = C.today();
    const exs = S.db().exams.filter(x => S.examStatus(x) === 'Completed' && S.examResult(s.id, x.id).done); const last = exs[exs.length - 1]; const lr = last ? S.examResult(s.id, last.id) : null;
    const up = S.db().exams.filter(x => x.grades.includes(s.grade) && S.examStatus(x) !== 'Completed')[0]; const days = up ? Math.round((C.pd(up.schedule[0].date) - C.pd(T)) / 864e5) : null; const ht = up && S.hallTicket(up.id, s.id);
    const rec = att.rec[sd]; const todayLabel = rec ? { P: ['Present', 'ok'], A: ['Absent', 'bad'], L: ['Late', 'warn'], V: ['On leave', 'info'] }[rec.s] : ['Not marked yet', '']; const mine = u.byStudent;
    const ptm = S.calendarFor(u).filter(e => e.type === 'ptm' && e.end >= T && e.date <= C.addDays(T, 14))[0];
    const alerts = [];
    if (fi.status === 'Overdue') alerts.push(H.alertRow('bad', 'rupee', '<b>' + C.inr(fi.overdueAmt) + ' fee is overdue.</b> Please pay at the school office or online.', '#/fees'));
    else if (fi.next && fi.balance > 0 && C.pd(fi.next.due) - C.pd(T) <= 14 * 864e5) alerts.push(H.alertRow('', 'rupee', 'Next fee instalment of <b>' + C.inr(fi.next.amount) + '</b> is due on <b>' + C.fmtDate(fi.next.due) + '</b>.', '#/fees'));
    if (ht) alerts.push(H.alertRow('ok', 'ticket', 'Hall ticket for <b>' + esc(up.name) + '</b> is ready to download.', '#/hallticket'));
    if (ptm) alerts.push(H.alertRow('info', 'users', 'Parent–teacher meeting on <b>' + C.fmtDate(ptm.date) + '</b>.', '#/calendar'));
    if (att.pct < 75) alerts.push(H.alertRow('bad', 'alert', 'Attendance is <b>' + att.pct + '%</b>, below the required 75%.', '#/attendance'));
    return `<div class="welcome mb"><div class="who-line">${UI.avatar(s.name, s.colorIdx, 'lg')}<div><div class="date">${C.fmtDateLong(T)}</div><h2>${App.greeting()}, ${esc(u.name.split(' ')[0])}</h2><p>${mine ? 'Here is your school summary.' : 'Here is how <b>' + esc(s.first) + '</b> is doing at school.'} <span class="muted">${esc(c.name)} · Class teacher ${esc(ct.name)} · Adm. no. ${esc(s.adm)}</span></p></div></div></div>
      ${alerts.length ? '<div class="mb">' + alerts.join('') + '</div>' : ''}
      ${H.tiles([['calendar', "Today's timetable", '#/timetables', '', '#1d4690'], ['check', 'Attendance', '#/attendance', '', '#1b9e8c'], ['award', 'Results', '#/marks', '', '#7a5198'], ['rupee', 'Pay fees', '#/fees', '', '#e0245e', fi.balance > 0 ? C.inr(fi.balance) + ' due' : 'All paid'], ['ticket', 'Hall ticket', '#/hallticket', '', '#f2a516'], ['phone', 'Contact school', '#', 'contactSchool', '#1eaaf1']])}
      <div class="grid g3 mb"><div class="card stat"><div class="lbl">Attendance today</div><div class="big">${UI.badge(todayLabel[0], todayLabel[1])}</div><div class="sub">${att.pct}% this year · ${att.A} day${att.A === 1 ? '' : 's'} absent</div></div>
        <div class="card stat"><div class="lbl">${last ? esc(last.name) : 'Latest result'}</div><div class="big">${lr ? lr.pct + '%' : '—'}</div><div class="sub">${lr ? 'Grade ' + lr.grade + ' · ' + (lr.result === 'Partial' ? 'some subjects awaited' : lr.result) : 'Results will appear here'}</div></div>
        <div class="card stat"><div class="lbl">${up ? 'Next exam: ' + esc(up.name) : 'Next exam'}</div><div class="big">${up ? (days > 0 ? 'in ' + days + ' days' : 'Going on') : '—'}</div><div class="sub">${up ? C.fmtDate(up.schedule[0].date) : 'No exam scheduled'}</div></div></div>
      <div class="grid g-21">${UI.card("Today's timetable", H.classSched(c.id, td), { flush: true, sub: C.fmtDateLong(td.date), actions: H.dayNote(td) + '<a class="btn sm" href="#/timetables">Full week</a>' })}<div class="grid" style="gap:16px">${UI.card('Notices from school', H.annList(S.announcementsFor(u), 3), { flush: true, actions: '<a class="btn sm" href="#/announcements">All notices</a>' })}${UI.card('Coming up', H.eventList(H.upcoming(u, ['holiday', 'public', 'event', 'ptm', 'special', 'exam'], 4)), { flush: true, actions: '<a class="btn sm" href="#/calendar">Calendar</a>' })}</div></div>`;
  }

  /* ---------- Operations ---------- */
  function dashOps(ctx) {
    const db = S.db(), u = ctx.u, sd = S.schoolDay(), sup = u.supervisor; const mine = db.tasks.filter(t => t.date === sd && (sup || t.assignedTo === u.empId));
    const cnt = k => mine.filter(t => t.status === k).length; const open = db.maint.filter(m => m.status !== 'Resolved');
    return H.greet(u, sup ? 'Supervising ' + db.employees.filter(e => e.role === 'ops' && !e.supervisor).length + ' staff · ' + C.fmtDate(sd) : 'Your assigned tasks for ' + C.fmtDate(sd)) +
      `<div class="grid g5">${UI.kpi({ label: sup ? "Today's tasks" : 'My tasks today', value: mine.length, icon: 'clipboard', href: '#/tasks' })}${UI.kpi({ label: 'Completed', value: cnt('Completed'), sub: C.pct(cnt('Completed'), mine.length, 0) + '% done', icon: 'check', tone: 'ok', href: '#/tasks' })}${UI.kpi({ label: 'In progress', value: cnt('In Progress'), icon: 'clock', href: '#/tasks' })}${UI.kpi({ label: 'Pending', value: cnt('Pending'), icon: 'dot', tone: 'warn', href: '#/tasks' })}${UI.kpi({ label: 'Requires attention', value: cnt('Requires Attention'), icon: 'alert', tone: 'bad', href: '#/tasks' })}</div>
      <div class="grid g-21 mt">${UI.card(sup ? "Today's tasks – all staff" : 'My tasks today', Pages.tasks.table(mine.slice(0, 8), u, true), { flush: true, actions: '<a class="btn sm" href="#/tasks">Open all</a>' })}<div class="grid" style="gap:16px">${UI.card('Maintenance queue', open.slice(0, 5).map(m => `<div class="list-i"><div class="grow"><b>${esc(m.issue)}</b><div class="muted small">${esc(m.location)} · ${esc(m.reportedBy)}</div></div><div class="col" style="align-items:flex-end;gap:4px">${UI.status(m.priority)}${UI.status(m.status)}</div></div>`).join('') || UI.empty('No open requests'), { flush: true, actions: '<a class="btn sm" href="#/issues">View all</a>' })}${UI.card('Announcements', H.annList(S.announcementsFor(u), 2), { flush: true })}</div></div>
      ${sup ? `<div class="grid g2 mt">${UI.card('Awaiting verification', (() => { const v = db.tasks.filter(t => t.status === 'Completed' && !t.verified).slice(-6); return v.map(t => `<div class="list-i"><div class="grow"><b>${esc(t.task)} – ${esc(t.location)}</b><div class="muted small">${C.fmtDay(t.date)} · ${esc(S.emp(t.assignedTo).name)}</div></div><button class="btn xs ok" data-act="verifyTask" data-id="${t.id}">Verify</button></div>`).join('') || UI.empty('Nothing to verify'); })(), { flush: true })}${UI.card('Staff workload today', UI.chart.hbars({ items: db.employees.filter(e => e.role === 'ops' && !e.supervisor).map(e => { const t = mine.filter(x => x.assignedTo === e.id); return { label: e.name, value: t.filter(x => x.status === 'Completed').length, note: 'of ' + t.length + ' tasks', cls: '' }; }), max: 4 }), { sub: 'Completed tasks per staff member' })}</div>` : ''}`;
  }

  /* ---------- Admin ---------- */
  function dashAdmin(ctx) {
    const db = S.db(), u = ctx.u; const byRole = {}; db.users.forEach(x => byRole[x.role] = (byRole[x.role] || 0) + 1); const kb = Math.round(JSON.stringify(db).length / 1024);
    return H.greet(u, 'System configuration, accounts and integrations') +
      `<div class="grid g4">${UI.kpi({ label: 'User accounts', value: db.users.length, sub: db.users.filter(x => !x.active).length + ' disabled', icon: 'users', href: '#/accounts' })}${UI.kpi({ label: 'WhatsApp notifications', value: db.settings.whatsappEnabled ? 'Enabled' : 'Paused', sub: db.notifications.length + ' messages in history', icon: 'wa', tone: db.settings.whatsappEnabled ? 'ok' : 'warn', href: '#/notifylog' })}${UI.kpi({ label: 'Audit entries', value: db.audit.length, sub: 'Last: ' + (db.audit.length ? C.fmtStamp(db.audit[db.audit.length - 1].ts) : '—'), icon: 'shield', href: '#/audit' })}${UI.kpi({ label: 'Data store', value: kb + ' KB', sub: 'Browser storage (demo mode)', icon: 'layers', href: '#/settings' })}</div>
      <div class="grid g2 mt">${UI.card('Accounts by role', UI.chart.hbars({ items: Object.entries(byRole).map(([k, v]) => ({ label: C.ROLES[k], value: v })), fmt: v => v }))}${UI.card('Integrations & modules', `<div class="col" style="gap:0">${[['WhatsApp Business gateway', db.settings.whatsappEnabled ? 'Simulated – messages logged' : 'Paused', db.settings.whatsappEnabled], ['Online fee payments', db.settings.onlinePayments ? 'Enabled (test mode)' : 'Disabled', db.settings.onlinePayments], ['Hall ticket fee-clearance rule', db.settings.hallTicketRequiresFees ? 'Enforced' : 'Not enforced', db.settings.hallTicketRequiresFees]].map(r => `<div class="setting"><div><b>${r[0]}</b><small>${r[1]}</small></div>${UI.badge(r[2] ? 'On' : 'Off', r[2] ? 'ok' : '')}</div>`).join('')}</div><div class="mt-s"><a class="btn sm" href="#/settings">Open settings</a></div>`)}</div>
      <div class="mt">${UI.card('Recent audit activity', `<div class="tbl-wrap"><table class="tbl"><tbody>${db.audit.slice(-6).reverse().map(a => `<tr><td class="nowrap muted">${C.fmtStamp(a.ts)}</td><td><b>${esc(a.user)}</b></td><td>${esc(a.action)}</td><td class="muted">${esc(a.entity)}</td></tr>`).join('')}</tbody></table></div>`, { flush: true, actions: '<a class="btn sm" href="#/audit">Full log</a>' })}</div>`;
  }

  const QUICK = {
    principal: () => [['users', 'Students', '#/students'], ['rupee', 'Fee collection', '#/fees', '', '#e0245e'], ['check', 'Attendance', '#/attendance', '', '#1b9e8c'], ['chart', 'Reports', '#/reports', '', '#7a5198'], ['bell', 'Post announcement', '#/announcements', '', '#f2a516']],
    dean: () => [['calendar', 'Timetables', '#/timetables'], ['award', 'Approve marks', '#/marks', '', '#7a5198'], ['clipboard', 'Examinations', '#/exams', '', '#e0245e'], ['users', 'Class teachers', '#/classteachers', '', '#1b9e8c'], ['check', 'Attendance', '#/attendance', '', '#1eaaf1']],
    accountant: () => [['rupee', 'Collect fee', '#/fees', '', '#e0245e'], ['alert', 'Pending fees', '#/pending', '', '#f2a516'], ['receipt', 'Receipts', '#/receipts'], ['wallet', 'Payroll', '#/payroll', '', '#1b9e8c'], ['trend', 'Expenses', '#/expenses', '', '#7a5198']],
    teacher: u => [['check', 'Take attendance', '#/attendance', '', '#1b9e8c'], ['award', 'Enter marks', '#/marks', '', '#7a5198'], ['calendar', 'My timetable', '#/timetables'], ['book', 'My classes', '#/myclasses', '', '#e0245e'], ['clock', 'Apply for leave', '#/leave', '', '#f2a516']],
    ops: () => [['check', "Today's tasks", '#/tasks', '', '#1b9e8c'], ['wrench', 'Maintenance', '#/maintenance'], ['alert', 'Reported issues', '#/issues', '', '#e0245e'], ['shield', 'Completed tasks', '#/completed', '', '#7a5198']],
    admin: () => [['users', 'User accounts', '#/accounts'], ['settings', 'Settings', '#/settings', '', '#7a5198'], ['wa', 'Message history', '#/notifylog', '', '#1b9e8c'], ['shield', 'Audit logs', '#/audit', '', '#e0245e']]
  };
  Pages.dashboard = { render: ctx => { const html = ({ principal: dashPrincipal, dean: dashDean, accountant: dashAccountant, teacher: dashTeacher, parent: dashFamily, ops: dashOps, admin: dashAdmin }[ctx.u.role])(ctx); return QUICK[ctx.u.role] ? html.replace('<!--Q-->', H.quick(QUICK[ctx.u.role](ctx.u))) : html; } };
})(window);
