/* pages-comm.js — calendar, announcements, leave, hall tickets (family), class teachers, subjects, academics */
(function (G) {
  'use strict';
  const C = G.C, S = G.S, UI = G.UI, esc = C.esc, App = G.App, H = G.H;
  const Pages = G.Pages = G.Pages || {};

  /* ---------- Calendar ---------- */
  Pages.calendar = {
    roles: ['principal', 'dean', 'teacher', 'student', 'parent'],
    render(ctx) {
      const u = ctx.u, st = ctx.st; const ym = st.ym || C.today().slice(0, 7); const [Y, M] = ym.split('-').map(Number); const T = C.today(); const typ = st.t || '';
      const evs = S.calendarFor(u).filter(e => !typ || e.type === typ); const first = C.ymd(new Date(Y, M - 1, 1)); const lead = C.dow(first); const days = new Date(Y, M, 0).getDate(); let cells = '';
      for (let i = 0; i < lead; i++) cells += '<div class="d out"></div>';
      for (let d = 1; d <= days; d++) { const date = ym + '-' + C.pad(d); const es = evs.filter(e => date >= e.date && date <= e.end); const sun = C.dow(date) === 6; const hol = es.some(e => e.type === 'holiday' || e.type === 'public');
        cells += `<div class="d ${sun ? 'st-S' : hol ? 'st-H' : ''} ${es.length ? 'click' : ''} ${date === T ? 'today' : ''}" ${es.length ? `data-act="calDay" data-d="${date}"` : ''}><span class="n">${d}</span>${es.slice(0, 2).map(e => `<span class="tag t-${e.type}" title="${esc(e.title)}">${esc(e.title)}</span>`).join('')}${es.length > 2 ? `<span class="tiny muted">+${es.length - 2} more</span>` : ''}</div>`; }
      const up = S.calendarFor(u).filter(e => e.end >= T).sort((a, b) => a.date.localeCompare(b.date)).slice(0, 8);
      return UI.head({ title: 'School calendar', sub: 'Holidays, examinations, events and parent meetings for ' + S.db().ay, actions: ['principal', 'dean'].includes(u.role) ? UI.btn('Add event', 'addEvent', { cls: 'primary', icon: 'plus' }) : '' }) +
        `<div class="grid g-21"><div class="card"><div class="card-h"><div class="row"><button class="btn sm" data-act="calNav" data-n="-1">‹</button><h3 style="min-width:150px;text-align:center">${C.MONTHS[M - 1]} ${Y}</h3><button class="btn sm" data-act="calNav" data-n="1">›</button><button class="btn sm" data-act="calNav" data-n="0">Today</button></div><select class="input sm" style="width:auto" data-on="calType">${UI.opts([['', 'All events'], ['holiday', 'School holidays'], ['public', 'Public holidays'], ['exam', 'Examinations'], ['event', 'Events'], ['ptm', 'Parent meetings'], ['special', 'Special programmes']], typ)}</select></div><div class="card-b"><div class="cal"><div class="dh">Mon</div><div class="dh">Tue</div><div class="dh">Wed</div><div class="dh">Thu</div><div class="dh">Fri</div><div class="dh">Sat</div><div class="dh">Sun</div>${cells}</div><div class="legend-row mt">${[['holiday', 'School holiday'], ['public', 'Public holiday'], ['exam', 'Examination'], ['event', 'Event'], ['ptm', 'Parent meeting'], ['special', 'Special programme']].map(([k, l]) => `<span><i class="t-${k}" style="background:currentColor"></i>${l}</span>`).join('')}</div></div></div>
        ${UI.card('Upcoming', H.eventList(up), { flush: true })}</div>`;
    }
  };
  UI.act.calNav = t => { const st = App.st('calendar'); const n = +t.dataset.n; if (n === 0) delete st.ym; else { const [y, m] = (st.ym || C.today().slice(0, 7)).split('-').map(Number); const d = new Date(y, m - 1 + n, 1); st.ym = d.getFullYear() + '-' + C.pad(d.getMonth() + 1); } App.refresh(); };
  UI.on.calType = t => { App.st('calendar').t = t.value; App.refresh(); };
  UI.act.calDay = t => { const d = t.dataset.d; const es = S.calendarFor(App.u).filter(e => d >= e.date && d <= e.end); UI.modal({ title: C.fmtDateLong(d), size: 'sm', body: es.map(e => { const [l, k] = H.evTag(e.type); return `<div style="padding:10px 0;border-bottom:1px solid var(--line-2)"><div class="row between"><b>${esc(e.title)}</b>${UI.badge(l, k)}</div><div class="muted small">${e.end !== e.date ? C.fmtDate(e.date) + ' – ' + C.fmtDate(e.end) : 'Single day'}</div>${e.desc ? `<div class="small" style="margin-top:4px">${esc(e.desc)}</div>` : ''}</div>`; }).join('') }); };
  UI.act.addEvent = () => UI.modal({ title: 'Add calendar event', body: `<form id="evForm" class="form-grid">${UI.field('Title *', UI.input('title', '', 'required'), { cls: 'full' })}${UI.field('Type', UI.select('type', [['event', 'Event'], ['holiday', 'School holiday'], ['public', 'Public holiday'], ['ptm', 'Parent meeting'], ['special', 'Special programme']]))}${UI.field('Audience', UI.select('audience', [['all', 'Everyone'], ['parents', 'Parents'], ['staff', 'Staff only']]))}${UI.field('Start date *', UI.input('date', C.addDays(C.today(), 7), 'type="date" required'))}${UI.field('End date', UI.input('end', '', 'type="date"'))}${UI.field('Description', '<textarea class="input" name="desc"></textarea>', { cls: 'full' })}</form>`, footer: '<button class="btn" data-act="closeModal">Cancel</button><button class="btn primary" data-act="saveEvent">Add to calendar</button>' });
  UI.act.saveEvent = () => { const f = document.getElementById('evForm'); if (!f.reportValidity()) return; const d = UI.formData(f); if (d.end && d.end < d.date) { UI.toast('End date cannot be before start date', 'bad'); return; } const e = S.addEvent({ title: d.title, type: d.type, audience: d.audience, date: d.date, end: d.end || d.date, desc: d.desc }); if (e.type === 'holiday' || e.type === 'public') { const n = S.broadcast('holiday', `${e.title}: school closed ${C.fmtDate(e.date)}${e.end !== e.date ? ' to ' + C.fmtDate(e.end) : ''}. – ${C.SCHOOL.name}`, S.students().length); UI.toast('Holiday added to calendar', 'ok', 'Attendance & timetables will skip this date'); setTimeout(() => UI.waToast(n), 300); } else UI.toast('Event added', 'ok'); UI.closeModal(); App.refresh(); };

  /* ---------- Announcements ---------- */
  const TYPES = [['notice', 'Important notice'], ['holiday', 'Holiday notice'], ['exam', 'Exam notice'], ['fee', 'Fee reminder'], ['ptm', 'Parent meeting'], ['event', 'Event'], ['emergency', 'Emergency information']];
  const ICON = { exam: 'clipboard', holiday: 'sun', fee: 'rupee', ptm: 'users', event: 'trophy', emergency: 'alert', notice: 'bell' };
  function audienceOptions(u) {
    const all = [['school', 'Entire school'], ['teachers', 'Teachers & staff'], ['students', 'Students'], ['parents', 'Parents'], ['ops', 'Operations staff']].concat([1, 2, 3, 4, 5, 6, 7, 8, 9, 10].map(g => ['grade:' + g, 'Grade ' + g + ' (all sections)']), S.classes().map(c => ['class:' + c.id, c.name + ' (section)']));
    if (u.role === 'accountant') return all.filter(a => ['school', 'parents'].includes(a[0]) || a[0].startsWith('grade') || a[0].startsWith('class'));
    if (u.role === 'teacher') return Object.keys(S.teacherClasses(u.empId)).map(c => ['class:' + c, S.className(c) + ' (section)']);
    return all;
  }
  const parseAud = v => v.startsWith('grade:') ? { kind: 'grade', grade: +v.slice(6) } : v.startsWith('class:') ? { kind: 'class', classId: v.slice(6) } : { kind: v };
  Pages.announcements = {
    render(ctx) {
      const u = ctx.u, st = ctx.st; const can = ['principal', 'dean', 'admin', 'accountant'].includes(u.role) || (u.role === 'teacher' && S.classTeacherClass(u.empId)); const tab = u.role === 'parent' ? App.tab('announcements', 'ann') : 'ann'; const typ = st.t || '';
      const list = S.announcementsFor(u).filter(a => !typ || a.type === typ);
      const msgs = u.role === 'parent' ? S.db().notifications.filter(n => n.sid === u.studentId).slice().reverse() : [];
      return UI.head({ title: 'Announcements', sub: 'Notices from school administration and teachers.', actions: can ? UI.btn('New announcement', 'newAnn', { cls: 'primary', icon: 'plus' }) : '' }) + (u.role === 'parent' ? App.tabs('announcements', [['ann', 'Announcements', list.length], ['wa', 'WhatsApp messages', msgs.length]], tab) : '') +
        (tab === 'wa' ? UI.card('WhatsApp messages sent to ' + C.phone(S.parentOf(u.studentId).whatsapp), msgs.map(n => `<div class="list-i"><div class="avatar sm" style="background:#25d366">${UI.icon('wa', 14)}</div><div class="grow"><div class="tiny muted" style="margin-bottom:4px">${C.fmtStamp(n.ts)} · ${esc(n.type)} · ${n.status}</div>${UI.wa(n.message)}</div></div>`).join('') || UI.empty('No messages yet'), { flush: true }) :
          `<div class="row mb"><select class="input sm" style="width:auto" data-on="annType">${UI.opts([['', 'All types']].concat(TYPES), typ)}</select></div><div class="grid" style="gap:14px">${list.map(a => `<div class="card"><div class="card-b row top" style="gap:14px"><div class="avatar" style="background:${a.type === 'emergency' ? 'var(--bad)' : 'var(--navy-700)'}">${UI.icon(ICON[a.type] || 'bell', 17)}</div><div class="grow"><div class="row between wrap"><h3 style="font-size:16px">${a.pinned ? '' : ''}${esc(a.title)}</h3><div class="row">${UI.badge(TYPES.find(t => t[0] === a.type) ? TYPES.find(t => t[0] === a.type)[1] : a.type, a.type === 'emergency' ? 'bad' : 'navy')}${a.public ? UI.badge('Public website', 'gold') : ''}</div></div><p style="margin:6px 0 8px;white-space:pre-line">${esc(a.body)}</p><div class="muted small">${C.fmtStamp(a.ts)} · To: ${esc(S.audienceLabel(a.audience))} · By ${esc(a.by)}</div></div>${(u.role === 'principal' || a.by === u.name) ? `<button class="btn xs danger" data-act="delAnn" data-id="${a.id}" title="Delete">${UI.icon('trash', 13)}</button>` : ''}</div></div>`).join('') || UI.card('', UI.empty('No announcements'))}</div>`);
    }
  };
  UI.on.annType = t => { App.st('announcements').t = t.value; App.refresh(); };
  UI.act.delAnn = t => UI.confirm('Delete announcement?', 'This removes it for all recipients.', 'Delete', () => { S.deleteAnnouncement(t.dataset.id); App.refresh(); }, true);
  UI.act.newAnn = () => {
    const u = App.u; const types = u.role === 'accountant' ? TYPES.filter(t => ['fee', 'notice'].includes(t[0])) : u.role === 'teacher' ? TYPES.filter(t => ['notice', 'event', 'exam'].includes(t[0])) : TYPES;
    UI.modal({ title: 'New announcement', size: 'lg', body: `<form id="anForm" class="form-grid">${UI.field('Title *', UI.input('title', '', 'required'), { cls: 'full' })}${UI.field('Type', UI.select('type', types, 'notice', 'data-on="annPrev"'))}${UI.field('Audience', UI.select('aud', audienceOptions(u), audienceOptions(u)[0][0], 'data-on="annPrev"'))}${UI.field('Message *', '<textarea class="input" name="body" rows="5" required></textarea>', { cls: 'full' })}${['principal', 'admin'].includes(u.role) ? UI.field('Visibility', '<label class="row"><input type="checkbox" name="pub"> Also show on the public school website</label><label class="row"><input type="checkbox" name="pin"> Pin to top</label>', { cls: 'full' }) : ''}<div class="full" id="annPrev"></div></form>`, footer: '<button class="btn" data-act="closeModal">Cancel</button><button class="btn primary" data-act="saveAnn">Publish</button>', onMount: () => UI.on.annPrev() });
  };
  UI.on.annPrev = () => { const f = document.getElementById('anForm'); if (!f) return; const aud = parseAud(f.aud.value); const map = ['holiday', 'emergency', 'ptm', 'fee', 'exam', 'notice', 'event']; const par = ['school', 'parents', 'students', 'grade', 'class'].includes(aud.kind); const n = par ? S.audienceParents(aud).length : 0; document.getElementById('annPrev').innerHTML = par && map.includes(f.type.value) ? `<div class="alert info">${UI.icon('wa', 16)}<div>A WhatsApp broadcast will be sent to <b>${n}</b> parent${n === 1 ? '' : 's'} (if this alert type is enabled in notification settings).</div></div>` : `<div class="note-row">Visible in the portal to: <b>${esc(S.audienceLabel(aud))}</b></div>`; };
  UI.act.saveAnn = () => { const f = document.getElementById('anForm'); if (!f.reportValidity()) return; const d = UI.formData(f); const r = S.addAnnouncement({ title: d.title, body: d.body, type: d.type, audience: parseAud(d.aud), public: !!d.pub, pinned: !!d.pin }); UI.closeModal(); UI.toast('Announcement published', 'ok', S.audienceLabel(r.ann.audience)); if (r.sent) setTimeout(() => UI.toast(r.sent.status === 'Delivered' ? 'WhatsApp sent to ' + r.sent.recipients + ' parents' : 'WhatsApp not sent', r.sent.status === 'Delivered' ? 'wa' : '', r.sent.status === 'Delivered' ? 'Broadcast logged in notification history' : 'Alert type disabled in settings'), 350); App.refresh(); };

  /* ---------- Teacher leave ---------- */
  Pages.leave = {
    roles: ['teacher'],
    render(ctx) {
      const e = S.emp(ctx.u.empId), ls = S.db().leaves.filter(l => l.empId === e.id).sort((a, b) => b.from.localeCompare(a.from));
      return UI.head({ title: 'Leave', sub: 'Apply for leave and track approvals.', actions: UI.btn('Apply for leave', 'applyLeave', { cls: 'primary', icon: 'plus' }) }) + `<div class="grid g3 mb">${Object.entries(e.leaveBalance).map(([k, v]) => UI.kpi({ label: k + ' leave balance', value: v + ' days', icon: 'clock', tone: 'ok' })).join('')}</div>` + UI.card('My leave requests', UI.table([{ h: 'Applied', f: r => C.fmtDate(r.appliedOn) }, { h: 'Type', f: r => r.type }, { h: 'From', f: r => C.fmtDate(r.from) }, { h: 'To', f: r => C.fmtDate(r.to) }, { h: 'Days', f: r => r.days, cls: 'num' }, { h: 'Reason', f: r => esc(r.reason) }, { h: 'Status', f: r => UI.status(r.status) }, { h: 'Decided by', f: r => esc(r.decidedBy) || '—' }], ls, { empty: 'No leave requests' }), { flush: true });
    }
  };
  UI.act.applyLeave = () => UI.modal({ title: 'Apply for leave', size: 'sm', body: `<form id="lvForm" class="col" style="gap:14px">${UI.field('Leave type', UI.select('type', ['Casual', 'Sick', 'Earned']))}${UI.field('From', UI.input('from', C.addDays(C.today(), 1), 'type="date" required'))}${UI.field('To', UI.input('to', C.addDays(C.today(), 1), 'type="date" required'))}${UI.field('Reason', '<textarea class="input" name="reason" required></textarea>')}</form>`, footer: '<button class="btn" data-act="closeModal">Cancel</button><button class="btn primary" data-act="saveLeave">Submit request</button>' });
  UI.act.saveLeave = () => { const f = document.getElementById('lvForm'); if (!f.reportValidity()) return; const d = UI.formData(f); if (d.to < d.from) { UI.toast('End date is before start date', 'bad'); return; } const days = Math.round((C.pd(d.to) - C.pd(d.from)) / 864e5) + 1; S.applyLeave({ empId: App.u.empId, type: d.type, from: d.from, to: d.to, days, reason: d.reason }); UI.closeModal(); UI.toast('Leave request sent to the Principal', 'ok'); App.refresh(); };

  /* ---------- Hall tickets (student / parent) ---------- */
  Pages.hallticket = {
    roles: ['student', 'parent'],
    render(ctx) {
      const sid = ctx.u.studentId, s = S.student(sid); const exs = S.db().exams.filter(x => x.grades.includes(s.grade)).sort((a, b) => b.schedule[0].date.localeCompare(a.schedule[0].date)); const rule = S.db().settings.hallTicketRequiresFees;
      return UI.head({ title: 'Hall tickets', sub: 'Download hall tickets issued by the school for upcoming examinations.' }) + `<div class="grid g2">${exs.map(x => { const h = S.hallTicket(x.id, sid), el = S.hallEligibility(sid, x.id), stt = S.examStatus(x); return UI.card(esc(x.name), `<div class="muted small mb">${C.fmtDate(x.schedule[0].date)} – ${C.fmtDate(x.schedule[x.schedule.length - 1].date)} · ${esc(x.centre)}</div>${h ? `<div class="alert ok">${UI.icon('check', 16)}<div>Hall ticket <b>${h.no}</b> issued ${C.fmtDate(h.ts)}.</div></div><div class="mt-s">${UI.btn('View / download hall ticket', 'hallView', { cls: 'primary', icon: 'download', data: { sid, ex: x.id } })}</div>` : !el.ok ? `<div class="alert bad">${UI.icon('lock', 16)}<div><b>Hall ticket on hold.</b> ${esc(el.reason)} Please contact the accounts office.</div></div>` : `<div class="alert">${UI.icon('clock', 16)}<div>${stt === 'Completed' ? 'This examination is over.' : 'Not issued yet – the Dean’s office will publish it before the exam.'}</div></div>`}`, { actions: UI.status(stt) }); }).join('')}</div>`;
    }
  };

  /* ---------- Class teachers (Dean) ---------- */
  Pages.classteachers = {
    roles: ['dean'],
    render() {
      const ts = S.teachers(); const ctMap = {}; S.classes().forEach(c => { if (c.classTeacherId) ctMap[c.classTeacherId] = c; });
      return UI.head({ title: 'Class teachers', sub: 'Assign a class teacher – access to student details and attendance is granted immediately.' }) + UI.card('', UI.table([{ h: 'Class', f: c => `<b>${c.name}</b><div class="muted small">${esc(c.room)} · ${S.studentsOf(c.id).length} students</div>` }, { h: 'Current class teacher', f: c => c.classTeacherId ? UI.person(S.emp(c.classTeacherId).name, S.emp(c.classTeacherId).dept, 3) : UI.badge('Unassigned', 'bad') }, { h: 'Assign / change', f: c => `<select class="input sm" id="ct_${c.id}">${UI.opts(ts.map(t => [t.id, t.name + (ctMap[t.id] && ctMap[t.id].id !== c.id ? ' – currently CT ' + ctMap[t.id].name : '')]), c.classTeacherId)}</select>` }, { h: '', f: c => UI.btn('Assign', 'ctAssign', { cls: 'xs primary', data: { id: c.id } }) }], S.classes()), { flush: true });
    }
  };
  UI.act.ctAssign = t => { const cid = t.dataset.id, eid = document.getElementById('ct_' + cid).value; const c = S.cls(cid); if (c.classTeacherId === eid) { UI.toast('No change – already assigned', ''); return; } const rel = S.assignClassTeacher(cid, eid); UI.toast(S.emp(eid).name + ' is now Class Teacher of ' + c.name, 'ok', rel ? 'Released from ' + rel.name + ' – assign a new class teacher there.' : 'Class-teacher dashboard, student details and attendance access enabled.'); App.refresh(); };

  /* ---------- Subjects (Dean) ---------- */
  Pages.subjects = {
    roles: ['dean'],
    render() {
      const ts = S.teachers();
      return UI.head({ title: 'Subjects', sub: 'Subjects, weekly periods and subject-teacher allocation for every class.' }) + UI.card('Subjects', UI.table([{ h: 'Subject', f: s => `<b>${s.name}</b>` }, { h: 'Department', f: s => s.dept }, { h: 'Periods / week', f: s => s.per, cls: 'num' }, { h: 'Assessed in exams', f: s => s.exam ? UI.badge('Yes', 'ok') : UI.badge('No', '') }, { h: 'Teachers', f: s => ts.filter(t => t.subjects.includes(s.name)).length, cls: 'num' }, { h: 'Teachers list', f: s => `<span class="small">${esc(ts.filter(t => t.subjects.includes(s.name)).map(t => t.name).join(', '))}</span>` }], C.SUBJECTS), { flush: true }) + '<div class="mt"></div>' + UI.card('Subject-teacher allocation', `<div class="tbl-wrap"><table class="tbl"><thead><tr><th>Class</th>${C.SUBJECTS.map(s => `<th>${s.name}</th>`).join('')}</tr></thead><tbody>${S.classes().map(c => `<tr><td><b>${c.name}</b></td>${C.SUBJECTS.map(s => `<td><select class="input sm" style="min-width:150px" data-on="setSubjTeacher" data-cid="${c.id}" data-sub="${esc(s.name)}">${UI.opts(ts.filter(t => t.subjects.includes(s.name)).map(t => [t.id, t.name]), c.subjectTeachers[s.name])}</select></td>`).join('')}</tr>`).join('')}</tbody></table></div>`, { flush: true, sub: 'Changes apply immediately; timetables reflect the new teacher when published.' });
    }
  };

  /* ---------- Academics (Principal) ---------- */
  Pages.academics = {
    roles: ['principal'],
    render(ctx) {
      const exs = S.db().exams.filter(x => S.examStatus(x) !== 'Upcoming'); const exId = ctx.st.e || exs[exs.length - 1].id; const x = S.exam(exId);
      const cls = S.classes().map(c => ({ c, r: S.classExam(c.id, exId) })); const all = S.students().map(s => ({ s, r: S.examResult(s.id, exId) })).filter(a => a.r.done); const full = all.filter(a => a.r.complete);
      const gd = ['A+', 'A', 'B+', 'B', 'C', 'D', 'E'].map(g => ({ g, n: full.filter(a => a.r.grade === g).length }));
      const heat = v => v == null ? '' : `background:hsl(${Math.round(Math.max(0, Math.min(100, (v - 50) * 2)) * 1.3)},55%,${v > 75 ? 88 : 90}%)`;
      return UI.head({ title: 'Academics', sub: 'Academic performance across classes, subjects and examinations.', actions: `<select class="input sm" data-on="acEx">${UI.opts(exs.map(e => [e.id, e.name]), exId)}</select>` }) + `<div class="grid g4">${UI.kpi({ label: 'School average', value: C.avg(cls.filter(c => c.r.res.length), c => c.r.avg).toFixed(1) + '%', icon: 'award', tone: 'gold' })}${UI.kpi({ label: 'Pass percentage', value: C.pct(full.filter(a => a.r.result === 'Pass').length, full.length, 1) + '%', sub: full.length + ' students with complete results', icon: 'check', tone: 'ok' })}${UI.kpi({ label: 'Top class', value: cls.slice().sort((a, b) => b.r.avg - a.r.avg)[0].c.name, sub: cls.slice().sort((a, b) => b.r.avg - a.r.avg)[0].r.avg.toFixed(1) + '% average', icon: 'trophy' })}${UI.kpi({ label: 'Needs support', value: cls.filter(c => c.r.res.length).sort((a, b) => a.r.avg - b.r.avg)[0].c.name, sub: cls.filter(c => c.r.res.length).sort((a, b) => a.r.avg - b.r.avg)[0].r.avg.toFixed(1) + '% average', icon: 'alert', tone: 'warn' })}</div>
      <div class="grid g-21 mt">${UI.card('Subject × class heat-map – average %', `<div class="tbl-wrap"><table class="tbl"><thead><tr><th>Class</th>${x.schedule.map(s => `<th class="center">${esc(s.subject)}</th>`).join('')}<th class="center">Overall</th></tr></thead><tbody>${cls.map(c => `<tr><td><b>${c.c.name}</b></td>${x.schedule.map(s => { const v = S.subjectAvg(exId, c.c.id, s.subject); return `<td class="center" style="${heat(v)}"><b>${v == null ? '—' : v.toFixed(0)}</b></td>`; }).join('')}<td class="center"><b>${c.r.avg ? c.r.avg.toFixed(1) : '—'}</b></td></tr>`).join('')}</tbody></table></div>`, { flush: true })}${UI.card('Grade distribution', UI.chart.bars({ labels: gd.map(g => g.g), series: [{ name: 'Students', data: gd.map(g => g.n), color: UI.PAL[0] }], fmt: v => v, height: 220 }), { sub: x.name })}</div>
      <div class="grid g2 mt">${UI.card('Top performers', UI.table([{ h: '#', f: (r, i) => '' }].slice(0, 0).concat([{ h: 'Student', f: r => UI.person(r.s.name, S.className(r.s.classId), r.s.colorIdx, '#/student/' + r.s.id) }, { h: 'Percentage', f: r => `<b>${r.r.pct}%</b>`, cls: 'num' }, { h: 'Grade', f: r => r.r.grade }]), full.sort((a, b) => b.r.pct - a.r.pct).slice(0, 8)), { flush: true })}${UI.card('Class ranking', UI.chart.hbars({ items: cls.filter(c => c.r.res.length).sort((a, b) => b.r.avg - a.r.avg).map(c => ({ label: c.c.name, value: +c.r.avg.toFixed(1), note: C.pct(c.r.pass, c.r.n, 0) + '% pass' })), max: 100, fmt: v => v + '%' }))}</div>`;
    }
  };
  UI.on.acEx = t => { App.st('academics').e = t.value; App.refresh(); };
})(window);
