/* pages-people.js — students, parents, teachers, staff, classes, class-teacher views */
(function (G) {
  'use strict';
  const C = G.C, S = G.S, UI = G.UI, esc = C.esc, App = G.App, H = G.H;
  const Pages = G.Pages = G.Pages || {};
  const gl = g => g === 'M' ? 'Male' : 'Female';
  const lastExam = () => { const l = S.db().exams.filter(x => S.examStatus(x) === 'Completed'); return l[l.length - 1] || null; };
  const stuPerson = s => UI.person(s.name, s.adm, s.colorIdx, '#/student/' + s.id);
  const attBadge = p => `<div style="min-width:92px"><b class="mono">${p}%</b>${UI.progress(p)}</div>`;

  /* ---------- Attendance calendar (shared by profile + family attendance page) ---------- */
  H.attCal = (sid, opts = {}) => {
    const st = App.st('attcal'); const ym = st[sid] || C.today().slice(0, 7); const [Y, M] = ym.split('-').map(Number); const s = S.student(sid); const at = S.studentAtt(sid); const T = C.today();
    const first = C.ymd(new Date(Y, M - 1, 1)); const lead = C.dow(first); const days = new Date(Y, M, 0).getDate(); let cells = '';
    for (let i = 0; i < lead; i++) cells += '<div class="d out"></div>';
    const stats = { P: 0, A: 0, L: 0, V: 0, W: 0 };
    for (let d = 1; d <= days; d++) {
      const date = ym + '-' + C.pad(d); const rec = at.rec[date]; const hol = S.holidayOn(date); const sun = C.dow(date) === 6; let cls = 'st-N', tag = '', click = true;
      if (sun) { cls = 'st-S'; tag = '<span class="tag" style="background:none;color:var(--muted)">Sunday</span>'; }
      else if (hol) { cls = 'st-H'; tag = `<span class="tag">${esc(hol.title)}</span>`; }
      else if (rec) { cls = 'st-' + rec.s; tag = `<span class="tag">${{ P: 'Present', A: 'Absent', L: 'Late', V: 'Leave' }[rec.s]}</span>`; stats[rec.s]++; stats.W++; }
      else if (date > T) { tag = ''; click = false; } else tag = '<span class="tag" style="background:none;color:var(--muted)">Not marked</span>';
      cells += `<div class="d ${cls} ${click ? 'click' : ''} ${date === T ? 'today' : ''}" ${click ? `data-act="attDay" data-sid="${sid}" data-d="${date}"` : ''}><span class="n">${d}</span>${tag}</div>`;
    }
    const pct = stats.W ? +((stats.P + stats.L) * 100 / stats.W).toFixed(1) : 0;
    return `<div class="card"><div class="card-h"><div><h3>${C.MONTHS[M - 1]} ${Y}</h3><div class="sub">Tap a date for details</div></div><div class="row"><button class="btn sm" data-act="attMonth" data-sid="${sid}" data-n="-1">‹ Prev</button><button class="btn sm" data-act="attMonth" data-sid="${sid}" data-n="0">Today</button><button class="btn sm" data-act="attMonth" data-sid="${sid}" data-n="1">Next ›</button></div></div><div class="card-b"><div class="cal"><div class="dh">Mon</div><div class="dh">Tue</div><div class="dh">Wed</div><div class="dh">Thu</div><div class="dh">Fri</div><div class="dh">Sat</div><div class="dh">Sun</div>${cells}</div>
      <div class="legend-row mt"><span><i style="background:var(--ok)"></i>Present</span><span><i style="background:var(--bad)"></i>Absent</span><span><i style="background:#d99a2b"></i>Late</span><span><i style="background:var(--info)"></i>Leave</span><span><i style="background:var(--gold)"></i>Holiday</span><span><i style="background:#dfe4ee"></i>Sunday</span></div></div>
      <div class="card-f"><div class="grid g6" style="gap:10px;text-align:center">${[['This month', pct + '%'], ['Present', stats.P], ['Absent', stats.A], ['Late', stats.L], ['Leave', stats.V], ['Working days', stats.W]].map(x => `<div><div class="muted tiny">${x[0]}</div><b style="font-size:17px">${x[1]}</b></div>`).join('')}</div></div></div>`;
  };
  UI.act.attMonth = t => { const st = App.st('attcal'), sid = t.dataset.sid; const n = +t.dataset.n; if (n === 0) delete st[sid]; else { const [y, m] = (st[sid] || C.today().slice(0, 7)).split('-').map(Number); const d = new Date(y, m - 1 + n, 1); st[sid] = d.getFullYear() + '-' + C.pad(d.getMonth() + 1); } App.refresh(); };
  UI.act.attDay = t => {
    const sid = t.dataset.sid, d = t.dataset.d, s = S.student(sid); const rec = S.studentAtt(sid).rec[d]; const hol = S.holidayOn(d); const meta = ((S.db().attMeta[d] || {})[s.classId]) || null; const lab = { P: 'Present', A: 'Absent', L: 'Late arrival', V: 'Approved leave' };
    UI.modal({ title: C.fmtDateLong(d), size: 'sm', body: C.dow(d) === 6 ? '<div class="alert info">Sunday – no classes.</div>' : hol ? `<div class="alert">${UI.icon('calendar', 16)}<div><b>${esc(hol.title)}</b><br>School holiday – attendance not recorded.</div></div>` : rec ? UI.dl([['Student', esc(s.name)], ['Status', UI.badge(lab[rec.s], { P: 'ok', A: 'bad', L: 'warn', V: 'info' }[rec.s])], ['Remarks', esc(rec.r) || 'None'], ['Marked by', meta ? esc(meta.by) : '—'], ['Marked at', meta ? C.fmtStamp(meta.ts) : '—'], ['Class', esc(S.className(s.classId))]]) : '<div class="alert">Attendance has not been marked for this day.</div>' });
  };

  /* ---------- Students directory ---------- */
  Pages.students = {
    roles: ['principal', 'dean', 'accountant'],
    render(ctx) {
      const u = ctx.u, role = u.role, last = lastExam();
      const rows = () => S.students().map(s => ({ s, p: S.parent(s.parentId), att: S.studentAtt(s.id), fee: S.feeInfo(s.id), r: last ? S.examResult(s.id, last.id) : null }));
      const cols = [{ h: 'Student', f: r => stuPerson(r.s), csv: r => r.s.name }, { h: 'Admission No.', f: r => r.s.adm, cls: 'mono' }, { h: 'Class', f: r => esc(S.className(r.s.classId)) }, { h: 'Roll', f: r => r.s.roll, cls: 'num' }, { h: 'Parent', f: r => `<b>${esc(r.p.name)}</b><div class="muted small">${C.phone(r.p.phone)}</div>`, csv: r => r.p.name + ' (' + r.p.phone + ')' }];
      if (role !== 'accountant') cols.push({ h: 'Attendance', f: r => attBadge(r.att.pct), csv: r => r.att.pct + '%' }, { h: last ? last.name : 'Exam', f: r => r.r && r.r.done ? `<b>${r.r.pct}%</b> <span class="muted small">${r.r.grade}</span>` : '—', csv: r => r.r ? r.r.pct : '' });
      if (role !== 'dean') cols.push({ h: 'Total fee', f: r => C.inr(r.fee.total), cls: 'num', csv: r => r.fee.total }, { h: 'Balance', f: r => C.inr(r.fee.balance), cls: 'num', csv: r => r.fee.balance }, { h: 'Fee status', f: r => UI.status(r.fee.status), csv: r => r.fee.status });
      const grades = [['', 'All grades']].concat([1, 2, 3, 4, 5, 6, 7, 8, 9, 10].map(g => [g, 'Grade ' + g]));
      const lv = UI.listView({
        id: 'students', title: role === 'accountant' ? 'Student fee directory' : 'Student directory', sub: S.students().length + ' students enrolled · AY ' + S.db().ay, csv: 'students', pageSize: 14, print: true,
        filters: [{ k: 'q', type: 'search', label: 'Search', ph: role === 'dean' ? 'Student name, admission no., parent…' : 'Name, admission no., parent name or phone' }, { k: 'g', type: 'select', label: 'Class', options: grades }, { k: 'sec', type: 'select', label: 'Section', options: [['', 'All'], 'A', 'B'] }].concat(role === 'dean' ? [] : [{ k: 'fs', type: 'select', label: 'Fee status', options: [['', 'All'], 'Paid', 'Partially Paid', 'Pending', 'Overdue'] }]),
        source: rows, cols, href: r => '#/student/' + r.s.id,
        filter: (r, f) => (!f.g || r.s.grade == f.g) && (!f.sec || r.s.section === f.sec) && (!f.fs || r.fee.status === f.fs) && (!f.q || (r.s.name + ' ' + r.s.adm + ' ' + r.p.name + ' ' + r.p.phone).toLowerCase().includes(f.q.toLowerCase()))
      });
      const ptab = role === 'principal' ? App.tab('students', 'students') : 'students';
      const tabsHtml = role === 'principal' ? App.tabs('students', [['students', 'Students'], ['parents', 'Parents & guardians']], ptab) : '';
      const parentsLv = UI.listView({ id: 'parents', title: 'Parents & guardians', sub: S.db().parents.length + ' registered families', csv: 'parents', pageSize: 14, print: true, source: () => S.db().parents.map(p => ({ p, kids: S.students().filter(s => s.parentId === p.id) })), filters: [{ k: 'q', type: 'search', label: 'Search', ph: 'Parent name, phone, email or child' }], filter: (r, f) => !f.q || (r.p.name + r.p.mother + r.p.phone + r.p.email + r.kids.map(k => k.name).join(' ')).toLowerCase().includes(f.q.toLowerCase()),
        cols: [{ h: 'Parent / guardian', f: r => UI.person(r.p.name, r.p.occupation, r.p.name.length), csv: r => r.p.name }, { h: 'Mother', f: r => esc(r.p.mother) }, { h: 'Mobile / WhatsApp', f: r => C.phone(r.p.whatsapp), csv: r => r.p.whatsapp }, { h: 'Email', f: r => esc(r.p.email) }, { h: 'Children', f: r => r.kids.map(k => '<a href="#/student/' + k.id + '">' + esc(k.name) + '</a> <span class="muted small">(' + S.className(k.classId) + ')</span>').join('<br>'), csv: r => r.kids.map(k => k.name).join('; ') }] });
      if (ptab === 'parents') return UI.head({ title: 'Students', sub: 'Parent and guardian directory linked to student records.' }) + tabsHtml + parentsLv;
      return UI.head({ title: 'Students', sub: role === 'accountant' ? 'Search any student to view fee position, payments and receipts.' : 'Complete student records, linked to attendance, marks and fees.', actions: role === 'principal' ? UI.btn('Admit student', 'admitStudent', { cls: 'primary', icon: 'userplus' }) : (role === 'accountant' ? UI.link('Open fee collection', '#/fees', { cls: 'primary', icon: 'rupee' }) : '') }) + tabsHtml + lv;
    }
  };
  UI.act.admitStudent = () => {
    const cls = S.classes().map(c => [c.id, c.name]);
    UI.modal({ title: 'Admit new student', size: 'lg', body: `<form id="admitForm" class="form-grid">${UI.field('Student full name *', UI.input('name', '', 'required'))}${UI.field('Gender', UI.select('gender', [['M', 'Male'], ['F', 'Female']]))}${UI.field('Date of birth *', UI.input('dob', '2018-01-01', 'type="date" required'))}${UI.field('Class & section *', UI.select('classId', cls, 'C1A'))}${UI.field("Father / guardian name *", UI.input('parent', '', 'required'))}${UI.field("Mother's name", UI.input('mother', ''))}${UI.field('Mobile (WhatsApp) *', UI.input('phone', '', 'inputmode="numeric" maxlength="10" placeholder="10-digit mobile" required'), { hint: 'Used for parent portal login and WhatsApp alerts' })}${UI.field('Email', UI.input('email', '', 'type="email"'))}${UI.field('Blood group', UI.select('blood', ['', 'O+', 'A+', 'B+', 'AB+', 'O-', 'A-', 'B-']))}${UI.field('School transport', `<label class="row"><input type="checkbox" name="transport"> Opt for school bus (+₹14,000/yr)</label>`)}${UI.field('Residential address *', `<textarea class="input" name="address" required></textarea>`, { cls: 'full' })}${UI.field('Medical notes', `<textarea class="input" name="medical" placeholder="Allergies, conditions (optional)"></textarea>`, { cls: 'full' })}</form>`, footer: '<button class="btn" data-act="closeModal">Cancel</button><button class="btn primary" data-act="admitSave">Admit student</button>' });
  };
  UI.act.admitSave = () => { const f = document.getElementById('admitForm'); if (!f.reportValidity()) return; const d = UI.formData(f); if (!/^\d{10}$/.test(d.phone)) { UI.toast('Enter a valid 10-digit mobile number', 'bad'); return; } if (G.S.db().users.some(x => x.username === d.phone && x.role === 'parent')) { UI.toast('A parent account with this mobile number already exists', 'bad'); return; } const s = S.admitStudent(d); UI.closeModal(); UI.toast('Admitted ' + esc(s.name), 'ok', 'Admission no. ' + s.adm + ' · parent & student logins created (default password School@123)'); App.refresh(); };

  /* ---------- Student profile ---------- */
  function studentPage(ctx, sid) {
    const u = ctx.u, s = S.student(sid), ac = S.studentAccess(u, sid);
    if (!s || !ac.any) return UI.head({ title: 'Access restricted' }) + UI.card('', `<div class="empty"><div style="color:var(--bad);display:grid;place-items:center;margin-bottom:8px">${UI.icon('lock', 34)}</div><b>You are not authorised to view this student</b>Student records are visible only to the Principal, the Dean, the class teacher and the student’s own family.</div>`);
    const p = S.parent(s.parentId), c = S.cls(s.classId), ct = S.emp(c.classTeacherId), att = S.studentAtt(sid), fi = S.feeInfo(sid);
    const tabs = [['overview', 'Overview']]; if (ac.attendance) tabs.push(['attendance', 'Attendance']); if (ac.marks) tabs.push(['marks', 'Marks & results']); if (ac.fees && ac.fees !== 'none') tabs.push(['fees', 'Fees']); if (ac.docs) tabs.push(['docs', 'Documents']);
    const tab = App.tab('student:' + sid) && tabs.some(t => t[0] === App.tab('student:' + sid)) ? App.tab('student:' + sid) : 'overview';
    let body = '';
    if (tab === 'overview') body = `<div class="grid g-12">${UI.card('Personal details', UI.dl([['Full name', esc(s.name)], ['Admission no.', esc(s.adm)], ['Roll no.', s.roll], ['Class / section', esc(c.name)], ['Academic year', s.ay], ['Gender', gl(s.gender)], ['Date of birth', C.fmtDate(s.dob)], ['Blood group', s.blood || '—'], ['Admission date', C.fmtDate(s.admDate)], ac.contact ? ['Address', esc(s.address)] : null, ['School transport', s.transport ? 'Yes' : 'No']]), { actions: ac.edit ? UI.btn('Edit', 'editStudent', { cls: 'sm', icon: 'edit', data: { id: sid } }) : '' })}
      <div class="grid" style="gap:16px">${ac.contact ? UI.card('Parent & emergency contacts', `<div class="grid g2"><div>${UI.dl([['Father / guardian', esc(p.name)], ['Mother', esc(p.mother)], ['Mobile / WhatsApp', C.phone(p.whatsapp)], ['Email', esc(p.email)], ['Occupation', esc(p.occupation)]])}</div><div>${UI.dl([['Emergency contact', esc(s.emergency.name)], ['Relationship', esc(s.emergency.relation)], ['Emergency phone', C.phone(s.emergency.phone)]])}</div></div>${ac.medical ? `<div class="note-row mt-s"><b>Medical notes:</b> ${esc(s.medical) || 'None recorded.'}</div>` : ''}`) : ''}
      ${ac.history ? UI.card('Academic history', UI.table([{ h: 'Academic year', f: r => r.ay }, { h: 'Class', f: r => 'Grade ' + r.grade + r.section }, { h: 'Result', f: r => r.pct + '%', cls: 'num' }, { h: 'Attendance', f: r => r.attendance + '%', cls: 'num' }, { h: 'Outcome', f: r => UI.badge(r.result, 'ok') }], [{ ay: s.ay + ' (current)', grade: s.grade, section: s.section, pct: (() => { const l = lastExam(); const r = l ? S.examResult(sid, l.id) : null; return r && r.done ? r.pct : '—'; })(), attendance: att.pct, result: 'In progress' }].concat(s.history.slice().reverse())), { flush: true }) : ''}</div></div>`;
    else if (tab === 'attendance') body = `<div class="grid g-21">${H.attCal(sid)}${UI.card('Attendance summary', `<div class="col" style="gap:14px"><div class="center"><div style="font-size:38px;font-weight:700;color:var(--navy-900)">${att.pct}%</div><div class="muted">Overall attendance · ${att.total} school days recorded</div></div>${UI.progress(att.pct)}${UI.chart.donut({ items: [{ label: 'Present', value: att.P, color: '#1b7f57' }, { label: 'Absent', value: att.A, color: '#b3261e' }, { label: 'Late', value: att.L, color: '#d99a2b' }, { label: 'Leave', value: att.V, color: '#25609f' }], center: att.total, centerLabel: 'DAYS' })}</div>`)}</div>`;
    else if (tab === 'marks') body = marksTab(s, ac);
    else if (tab === 'fees') body = H.feeBlock(sid, ac.fees === 'full', u);
    else if (tab === 'docs') body = UI.card('Documents on file', UI.table([{ h: 'Document', f: r => esc(r.name) }, { h: 'Status', f: r => UI.status(r.status) }], s.docs), { flush: true });
    const crumbs = u.role === 'student' || u.role === 'parent' ? 'My profile' : `<a href="#/${u.role === 'teacher' ? 'mystudents' : 'students'}">${u.role === 'teacher' ? 'My students' : 'Students'}</a> › ${esc(s.name)}`;
    return `<div class="crumbs">${crumbs}</div><div class="card mb"><div class="card-b row wrap" style="gap:20px">${UI.avatar(s.name, s.colorIdx, 'xl')}<div class="grow"><h1 style="font-family:var(--serif);font-size:25px;font-weight:600">${esc(s.name)}</h1><div class="row wrap" style="gap:6px 18px;margin-top:6px;color:var(--text-2)"><span>${esc(s.adm)}</span><span>${esc(c.name)} · Roll ${s.roll}</span><span>Class teacher: ${esc(ct.name)}</span>${ac.contact ? `<span>${UI.icon('phone', 13)} ${C.phone(p.phone)}</span>` : ''}</div><div class="row wrap mt-s">${ac.attendance ? UI.badge('Attendance ' + att.pct + '%', att.pct >= 90 ? 'ok' : att.pct >= 75 ? 'warn' : 'bad') : ''}${ac.fees && ac.fees !== 'none' ? UI.status(fi.status) : ''}${ac.marks === true ? (() => { const l = lastExam(), r = l && S.examResult(sid, l.id); return r && r.done ? UI.badge(l.name + ': ' + r.pct + '% (' + r.grade + ')', 'navy') : ''; })() : ''}</div></div></div></div>` + (tabs.length > 1 ? App.tabs('student:' + sid, tabs, tab) : '') + body;
  }
  function marksTab(s, ac) {
    const exs = S.db().exams.filter(x => S.examStatus(x) !== 'Upcoming');
    if (ac.marks === 'subject') { const mine = S.teacherClasses(App.u.empId)[s.classId] || []; return UI.card('Marks in your subject(s)', UI.table([{ h: 'Examination', f: r => esc(r.x.name) }, { h: 'Subject', f: r => esc(r.sub) }, { h: 'Marks', f: r => r.e ? r.e.obt + ' / ' + r.rec.max : '—', cls: 'num' }], exs.flatMap(x => mine.map(sub => { const rec = S.marksRec(x.id, s.classId, sub); return rec && rec.status === 'published' ? { x, sub, rec, e: rec.entries[s.id] } : null; }).filter(Boolean)), { empty: 'No published marks' }), { flush: true }); }
    return exs.map(x => { const r = S.examResult(s.id, x.id); return UI.card(esc(x.name), r.done ? `<div class="tbl-wrap"><table class="tbl"><thead><tr><th>Subject</th><th class="num">Max</th><th class="num">Obtained</th><th>Grade</th><th>Result</th></tr></thead><tbody>${r.rows.map(w => w.pending ? `<tr><td>${esc(w.subject)}</td><td class="num">${w.max}</td><td colspan="3" class="muted">Awaited</td></tr>` : `<tr><td>${esc(w.subject)}</td><td class="num">${w.max}</td><td class="num"><b>${w.obt}</b></td><td>${w.grade}</td><td>${UI.status(w.pass ? 'Pass' : 'Fail')}</td></tr>`).join('')}</tbody><tfoot><tr><td>Total</td><td class="num">${r.max}</td><td class="num">${r.total}</td><td>${r.grade}</td><td>${r.pct}% · ${r.result}</td></tr></tfoot></table></div>` : UI.empty('Results not yet published'), { flush: true, actions: r.done ? UI.btn('Report card', 'reportCard', { cls: 'sm', icon: 'file', data: { sid: s.id, ex: x.id } }) : '' }); }).join('<div class="mt"></div>') || UI.card('', UI.empty('No examinations yet'));
  }
  UI.act.reportCard = t => G.Docs.open('report', t.dataset.sid, t.dataset.ex);
  UI.act.editStudent = t => {
    const s = S.student(t.dataset.id), p = S.parent(s.parentId), full = App.u.role === 'principal';
    UI.modal({ title: 'Edit student details', size: 'lg', body: `<form id="editStu" class="form-grid">${UI.field('Residential address', `<textarea class="input" name="address">${esc(s.address)}</textarea>`, { cls: 'full' })}${UI.field('Emergency contact name', UI.input('en', s.emergency.name))}${UI.field('Relationship', UI.input('er', s.emergency.relation))}${UI.field('Emergency phone', UI.input('ep', s.emergency.phone, 'maxlength="10"'))}${UI.field('Blood group', UI.select('blood', ['', 'O+', 'A+', 'B+', 'AB+', 'O-', 'A-', 'B-'], s.blood))}${UI.field('Medical notes', `<textarea class="input" name="medical">${esc(s.medical)}</textarea>`, { cls: 'full' })}${UI.field('Parent mobile / WhatsApp', UI.input('pw', p.whatsapp, 'maxlength="10"'), { hint: 'WhatsApp alerts are sent to this number' })}${UI.field('Parent email', UI.input('pe', p.email))}</form><div class="hint mt-s">Changes are recorded in the audit log with previous and new values.</div>`, footer: '<button class="btn" data-act="closeModal">Cancel</button><button class="btn primary" data-act="saveStudent" data-id="' + s.id + '">Save changes</button>' });
  };
  UI.act.saveStudent = t => { const s = S.student(t.dataset.id), d = UI.formData(document.getElementById('editStu')); if (!/^\d{10}$/.test(d.pw) || !/^\d{10}$/.test(d.ep)) { UI.toast('Phone numbers must be 10 digits', 'bad'); return; } S.updateStudent(s.id, { address: d.address, blood: d.blood, medical: d.medical, emergency: { name: d.en, relation: d.er, phone: d.ep } }); S.updateParent(s.parentId, { whatsapp: d.pw, email: d.pe }); UI.closeModal(); UI.toast('Student record updated', 'ok'); App.refresh(); };
  Pages.student = { render: ctx => studentPage(ctx, ctx.arg) };
  Pages.profile = { roles: ['student', 'parent'], render: ctx => studentPage(ctx, ctx.u.studentId) };

  /* ---------- Fee block (used on student profile + parent fees) ---------- */
  H.feeBlock = (sid, full, u) => {
    const fi = S.feeInfo(sid), s = S.student(sid);
    const sum = `<div class="grid g4 mb">${UI.kpi({ label: 'Total annual fee', value: C.inr(fi.total), icon: 'wallet' })}${UI.kpi({ label: 'Paid', value: C.inr(fi.paid), icon: 'check', tone: 'ok' })}${UI.kpi({ label: 'Remaining balance', value: C.inr(fi.balance), icon: 'alert', tone: fi.balance ? 'bad' : 'ok' })}${UI.kpi({ label: 'Status', value: UI.status(fi.status), sub: fi.next ? 'Next due ' + C.fmtDate(fi.next.due) + ' · ' + C.inr(fi.next.amount) : 'No dues', icon: 'clock' })}</div>`;
    if (!full) return sum;
    const terms = UI.table([{ h: 'Instalment', f: r => r.label }, { h: 'Due date', f: r => C.fmtDate(r.due) }, { h: 'Amount', f: r => C.inr(r.amount), cls: 'num' }, { h: 'Paid', f: r => C.inr(r.paid), cls: 'num' }, { h: 'Pending', f: r => C.inr(r.pending), cls: 'num' }, { h: 'Status', f: r => UI.status(r.status) }], fi.terms);
    const pays = UI.table([{ h: 'Receipt no.', f: r => `<b>${r.rcpt}</b>` }, { h: 'Date', f: r => C.fmtDate(r.date) }, { h: 'For', f: r => esc(r.term) }, { h: 'Method', f: r => esc(r.method) }, { h: 'Amount', f: r => C.inr(r.amount), cls: 'num' }, { h: '', f: r => UI.btn('Receipt', 'receipt', { cls: 'xs', icon: 'receipt', data: { id: r.id } }) }], fi.payments, { empty: 'No payments yet' });
    return sum + `<div class="grid g-12">${UI.card('Instalment schedule', terms, { flush: true })}${UI.card('Payment history', pays, { flush: true })}</div>`;
  };
  UI.act.receipt = t => G.Docs.open('receipt', t.dataset.id);

  /* ---------- Teachers ---------- */
  Pages.teachers = {
    roles: ['principal', 'dean'],
    render(ctx) {
      const u = ctx.u, db = S.db();
      const rows = () => S.teachers().map(t => ({ t, ct: S.classTeacherClass(t.id), load: S.teacherLoad(t.id), att: S.teacherAttPct(t.id), cl: Object.keys(S.teacherClasses(t.id)).length }));
      const lv = UI.listView({ id: 'teachers', title: 'Teaching staff', sub: S.teachers().length + ' teachers', csv: 'teachers', pageSize: 14, print: true, source: rows, href: r => '#/teacher/' + r.t.id,
        filters: [{ k: 'q', type: 'search', label: 'Search', ph: 'Name, employee ID, subject' }, { k: 'd', type: 'select', label: 'Department', options: [['', 'All departments']].concat(Array.from(new Set(S.teachers().map(t => t.dept)))) }],
        filter: (r, f) => (!f.d || r.t.dept === f.d) && (!f.q || (r.t.name + r.t.empId + r.t.subjects.join(' ')).toLowerCase().includes(f.q.toLowerCase())),
        cols: [{ h: 'Teacher', f: r => UI.person(r.t.name, r.t.designation, r.t.id.length * 3 + r.t.name.length, '#/teacher/' + r.t.id), csv: r => r.t.name }, { h: 'Employee ID', f: r => r.t.empId }, { h: 'Department', f: r => esc(r.t.dept) }, { h: 'Subjects', f: r => esc(r.t.subjects.join(', ')) }, { h: 'Classes', f: r => r.cl, cls: 'num' }, { h: 'Class teacher', f: r => r.ct ? UI.badge(r.ct.name, 'gold') : '<span class="muted">—</span>', csv: r => r.ct ? r.ct.name : '' }, { h: 'Periods/wk', f: r => r.load, cls: 'num' }, { h: 'Attendance', f: r => attBadge(r.att), csv: r => r.att + '%' }] });
      const pend = db.leaves.filter(l => l.status === 'Pending');
      const leaves = u.role === 'principal' && pend.length ? UI.card('Leave requests awaiting approval', UI.table([{ h: 'Teacher', f: r => UI.person(S.emp(r.empId).name, S.emp(r.empId).dept, 3) }, { h: 'Type', f: r => r.type }, { h: 'Dates', f: r => C.fmtDate(r.from) + (r.days > 1 ? ' – ' + C.fmtDate(r.to) : '') }, { h: 'Days', f: r => r.days, cls: 'num' }, { h: 'Reason', f: r => esc(r.reason) }, { h: '', f: r => `<div class="row"><button class="btn xs ok" data-act="decideLeave" data-id="${r.id}" data-s="Approved">Approve</button><button class="btn xs danger" data-act="decideLeave" data-id="${r.id}" data-s="Rejected">Reject</button></div>` }], pend), { flush: true }) + '<div class="mt"></div>' : '';
      return UI.head({ title: 'Teachers', sub: 'Faculty profiles, workload, class-teacher responsibilities and leave.' }) + leaves + lv;
    }
  };
  UI.act.decideLeave = t => { S.decideLeave(t.dataset.id, t.dataset.s); UI.toast('Leave ' + t.dataset.s.toLowerCase(), 'ok'); App.refresh(); };

  Pages.teacher = {
    roles: ['principal', 'dean'],
    render(ctx) {
      const u = ctx.u, e = S.emp(ctx.arg); if (!e || e.role !== 'teacher') return UI.head({ title: 'Teacher not found' });
      const key = 'teacher:' + e.id; const tabs = [['profile', 'Profile'], ['classes', 'Classes & timetable'], ['attendance', 'Attendance'], ['leave', 'Leave records']]; if (u.role === 'principal') tabs.push(['salary', 'Salary']);
      const tab = App.tab(key) || 'profile'; const ct = S.classTeacherClass(e.id); const tc = S.teacherClasses(e.id); let body = '';
      if (tab === 'profile') body = UI.card('Employment details', `<div class="grid g2">${UI.dl([['Employee ID', e.empId], ['Department', esc(e.dept)], ['Designation', esc(e.designation)], ['Qualification', esc(e.qualification)], ['Joining date', C.fmtDate(e.joinDate)]])}${UI.dl([['Phone', C.phone(e.phone)], ['Email', esc(e.email)], ['Subjects', esc(e.subjects.join(', '))], ['Class teacher of', ct ? `<a href="#/class/${ct.id}">${ct.name}</a>` : '—'], ['Weekly periods', S.teacherLoad(e.id) + ' of 42']])}</div>`);
      if (tab === 'classes') body = `<div class="grid g-12">${UI.card('Assigned classes', Object.entries(tc).map(([cid, sb]) => `<div class="list-i"><div class="grow"><b>${S.className(cid)}</b><div class="muted small">${esc(sb.join(', ') || 'Class teacher')}</div></div>${ct && ct.id === cid ? UI.badge('Class teacher', 'gold') : ''}</div>`).join('') || UI.empty('None'), { flush: true })}${UI.card('Weekly timetable', H.ttGrid((d, p) => { const c = (S.teacherTT(e.id)[d] || {})[p]; return { html: c ? `<div class="cell"><b>${esc(S.clsShort(c.classId))} · ${esc(c.subject)}</b><span>${esc(c.room)}</span></div>` : '<div class="cell free">Free</div>' }; }), { flush: true })}</div>`;
      if (tab === 'attendance') { const days = Object.keys(S.db().tAtt).sort().slice(-30); body = UI.card('Last 30 school days · ' + S.teacherAttPct(e.id) + '% present', `<div class="row wrap" style="gap:6px">${days.map(d => { const v = S.db().tAtt[d][e.id]; return `<span class="badge ${v === 'P' ? 'ok' : v === 'A' ? 'bad' : 'info'} nodot" title="${C.fmtDate(d)}">${C.pd(d).getDate()} ${C.MONTHS[C.pd(d).getMonth()].slice(0, 3)} · ${v === 'P' ? 'P' : v === 'A' ? 'A' : 'L'}</span>`; }).join('')}</div>`); }
      if (tab === 'leave') { const ls = S.db().leaves.filter(l => l.empId === e.id); body = UI.card('Leave balance', `<div class="grid g3">${Object.entries(e.leaveBalance).map(([k, v]) => `<div class="center"><div class="muted small">${k}</div><b style="font-size:22px">${v}</b> days</div>`).join('')}</div>`) + '<div class="mt"></div>' + UI.card('Leave records', UI.table([{ h: 'Type', f: r => r.type }, { h: 'From', f: r => C.fmtDate(r.from) }, { h: 'To', f: r => C.fmtDate(r.to) }, { h: 'Days', f: r => r.days, cls: 'num' }, { h: 'Reason', f: r => esc(r.reason) }, { h: 'Status', f: r => UI.status(r.status) }], ls, { empty: 'No leave applied' }), { flush: true }); }
      if (tab === 'salary') body = G.H.salaryHistory(e.id);
      return `<div class="crumbs"><a href="#/teachers">Teachers</a> › ${esc(e.name)}</div><div class="card mb"><div class="card-b row wrap" style="gap:20px">${UI.avatar(e.name, e.id.length * 3 + e.name.length, 'xl')}<div class="grow"><h1 style="font-family:var(--serif);font-size:25px;font-weight:600">${esc(e.name)}</h1><div class="muted">${esc(e.designation)} · ${esc(e.dept)} · ${e.empId}</div><div class="row wrap mt-s">${ct ? UI.badge('Class Teacher – ' + ct.name, 'gold') : ''}${e.subjects.map(s => UI.badge(s, 'navy')).join('')}</div></div></div></div>` + App.tabs(key, tabs, tab) + body;
    }
  };

  /* ---------- Staff ---------- */
  Pages.staff = {
    roles: ['principal'],
    render() {
      const rows = () => S.employees().filter(e => e.role !== 'teacher');
      return UI.head({ title: 'Staff', sub: 'Administrative, accounts and operations staff.' }) + UI.listView({ id: 'staff', title: 'Non-teaching staff', sub: rows().length + ' employees', csv: 'staff', source: rows, pageSize: 15, print: true,
        filters: [{ k: 'q', type: 'search', label: 'Search', ph: 'Name or employee ID' }, { k: 'r', type: 'select', label: 'Role', options: [['', 'All roles'], ['principal', 'Principal'], ['dean', 'Dean'], ['accountant', 'Accountant'], ['ops', 'Operations'], ['admin', 'Administrator']] }],
        filter: (e, f) => (!f.r || e.role === f.r) && (!f.q || (e.name + e.empId).toLowerCase().includes(f.q.toLowerCase())),
        cols: [{ h: 'Employee', f: e => UI.person(e.name, e.designation, e.name.length), csv: e => e.name }, { h: 'Employee ID', f: e => e.empId }, { h: 'Department', f: e => esc(e.dept) }, { h: 'Phone', f: e => C.phone(e.phone) }, { h: 'Email', f: e => esc(e.email) }, { h: 'Joined', f: e => C.fmtDate(e.joinDate) }, { h: 'Basic salary', f: e => C.inr(e.basic), cls: 'num' }] });
    }
  };

  /* ---------- Classes ---------- */
  Pages.classes = {
    roles: ['principal', 'dean'],
    render(ctx) {
      const u = ctx.u, T = C.today(); const last = lastExam();
      const rows = () => S.classes().map(c => ({ c, ct: S.emp(c.classTeacherId), n: S.studentsOf(c.id).length, att: S.classAttPct(c.id), fee: S.classFee(c.id), avg: last ? S.classExam(c.id, last.id).avg : 0 }));
      const cols = [{ h: 'Class', f: r => `<a href="#/class/${r.c.id}"><b>${r.c.name}</b></a><div class="muted small">${esc(r.c.room)}</div>`, csv: r => r.c.name }, { h: 'Class teacher', f: r => r.ct ? esc(r.ct.name) : UI.badge('Unassigned', 'bad') }, { h: 'Students', f: r => r.n, cls: 'num' }, { h: 'Attendance', f: r => attBadge(r.att), csv: r => r.att + '%' }, { h: last ? last.name + ' avg' : 'Avg', f: r => r.avg ? r.avg.toFixed(1) + '%' : '—', cls: 'num' }];
      if (u.role === 'principal') cols.push({ h: 'Fees collected', f: r => `${C.pct(r.fee.received, r.fee.expected, 0)}%`, cls: 'num', csv: r => C.pct(r.fee.received, r.fee.expected, 0) + '%' }, { h: 'Overdue', f: r => r.fee.Overdue, cls: 'num' });
      return UI.head({ title: 'Classes', sub: 'All classes and sections for ' + S.db().ay, actions: u.role === 'dean' ? UI.btn('Create class / section', 'newClass', { cls: 'primary', icon: 'plus' }) : '' }) + UI.listView({ id: 'classes', csv: 'classes', source: rows, cols, href: r => '#/class/' + r.c.id, pageSize: 20, filters: [{ k: 'q', type: 'search', label: 'Search', ph: 'Class or teacher' }], filter: (r, f) => !f.q || (r.c.name + (r.ct ? r.ct.name : '')).toLowerCase().includes(f.q.toLowerCase()) });
    }
  };
  UI.act.newClass = () => UI.modal({ title: 'Create class / section', size: 'sm', body: `<form id="ncForm" class="col" style="gap:14px">${UI.field('Grade', UI.select('grade', [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 9))}${UI.field('Section', UI.input('section', 'A', 'maxlength="1" style="text-transform:uppercase"'))}${UI.field('Room', UI.input('room', ''), { hint: 'Optional – defaults to a standard room number' })}</form>`, footer: '<button class="btn" data-act="closeModal">Cancel</button><button class="btn primary" data-act="saveClass">Create</button>' });
  UI.act.saveClass = () => { const d = UI.formData(document.getElementById('ncForm')); if (!/^[A-Za-z]$/.test(d.section)) { UI.toast('Section must be a single letter', 'bad'); return; } const r = S.createClass(d.grade, d.section.toUpperCase(), d.room); if (r.error) { UI.toast(r.error, 'bad'); return; } UI.closeModal(); UI.toast(r.cls.name + ' created', 'ok', 'Assign a class teacher, subject teachers and build the timetable next.'); App.refresh(); };

  Pages.class = {
    roles: ['principal', 'dean'],
    render(ctx) {
      const u = ctx.u, c = S.cls(ctx.arg); if (!c) return UI.head({ title: 'Class not found' }); const last = lastExam(); const ct = S.emp(c.classTeacherId); const sts = S.studentsOf(c.id); const dean = u.role === 'dean'; const cf = S.classFee(c.id);
      const teachers = S.teachers();
      const subj = C.SUBJECTS.map(s => { const t = c.subjectTeachers[s.name]; const cands = teachers.filter(x => x.subjects.includes(s.name)); return `<tr><td><b>${s.name}</b></td><td>${s.per}/wk</td><td>${dean ? `<select class="input sm" data-on="setSubjTeacher" data-cid="${c.id}" data-sub="${esc(s.name)}">${UI.opts(cands.map(x => [x.id, x.name]), t)}</select>` : esc(S.emp(t) ? S.emp(t).name : '—')}</td><td class="num">${last && s.exam ? (S.subjectAvg(last.id, c.id, s.name) || 0).toFixed(1) + '%' : '—'}</td></tr>`; }).join('');
      return `<div class="crumbs"><a href="#/classes">Classes</a> › ${c.name}</div>` + UI.head({ title: c.name, sub: `${esc(c.room)} · ${sts.length} students · Class teacher: ${ct ? esc(ct.name) : 'Unassigned'}`, actions: dean ? UI.link('Edit timetable', '#/timetables?c=' + c.id, { cls: 'primary', icon: 'calendar' }) + UI.link('Assign class teacher', '#/classteachers', { icon: 'users' }) : UI.link('View timetable', '#/timetables?c=' + c.id, { icon: 'calendar' }) }) +
        `<div class="grid g4">${UI.kpi({ label: 'Students', value: sts.length, icon: 'users' })}${UI.kpi({ label: 'Attendance', value: S.classAttPct(c.id) + '%', icon: 'check', tone: 'ok' })}${UI.kpi({ label: last ? last.name + ' average' : 'Average', value: last ? S.classExam(c.id, last.id).avg.toFixed(1) + '%' : '—', icon: 'award', tone: 'gold' })}${u.role === 'principal' ? UI.kpi({ label: 'Fees collected', value: C.pct(cf.received, cf.expected, 0) + '%', sub: C.inr(cf.pending) + ' pending', icon: 'rupee' }) : UI.kpi({ label: 'Subjects', value: C.SUBJECTS.length, icon: 'layers' })}</div>
      <div class="grid g-12 mt">${UI.card('Subject teachers', `<div class="tbl-wrap"><table class="tbl"><thead><tr><th>Subject</th><th>Periods</th><th>Teacher</th><th class="num">Avg</th></tr></thead><tbody>${subj}</tbody></table></div>`, { flush: true })}${UI.card('Students', UI.table([{ h: 'Roll', f: r => r.s.roll, cls: 'num' }, { h: 'Student', f: r => stuPerson(r.s) }, { h: 'Parent', f: r => esc(r.p.name) }, { h: 'Attendance', f: r => attBadge(r.a.pct) }, { h: last ? last.name : 'Exam', f: r => r.r && r.r.done ? r.r.pct + '%' : '—', cls: 'num' }].concat(u.role === 'principal' ? [{ h: 'Fees', f: r => UI.status(r.f.status) }] : []), sts.map(s => ({ s, p: S.parent(s.parentId), a: S.studentAtt(s.id), r: last ? S.examResult(s.id, last.id) : null, f: S.feeInfo(s.id) })), { href: r => '#/student/' + r.s.id }), { flush: true })}</div>`;
    }
  };
  UI.on.setSubjTeacher = t => { S.assignSubjectTeacher(t.dataset.cid, t.dataset.sub, t.value); UI.toast('Subject teacher updated', 'ok', S.className(t.dataset.cid) + ' · ' + t.dataset.sub + ' → ' + S.emp(t.value).name); };

  /* ---------- Teacher: My classes / My students ---------- */
  function teacherStudentTable(cid, u, full) {
    const sts = S.studentsOf(cid), tc = S.teacherClasses(u.empId)[cid] || [], last = lastExam();
    if (full) return UI.table([{ h: 'Photo', f: r => UI.avatar(r.s.name, r.s.colorIdx) }, { h: 'Roll', f: r => r.s.roll, cls: 'num' }, { h: 'Student', f: r => `<a href="#/student/${r.s.id}"><b>${esc(r.s.name)}</b></a><div class="muted small">${esc(r.s.adm)} · DOB ${C.fmtDate(r.s.dob)}</div>` }, { h: 'Parent', f: r => `<b>${esc(r.p.name)}</b><div class="muted small">${C.phone(r.p.phone)}</div>` }, { h: 'Address', f: r => `<span class="small">${esc(r.s.address)}</span>` }, { h: 'Emergency', f: r => `${esc(r.s.emergency.name)} <span class="muted small">(${esc(r.s.emergency.relation)})</span><div class="muted small">${C.phone(r.s.emergency.phone)}</div>` }, { h: 'Attendance', f: r => attBadge(r.a.pct) }, { h: 'Fees', f: r => UI.status(r.f.status) }, { h: 'Performance', f: r => r.r && r.r.done ? `<b>${r.r.pct}%</b> <span class="muted small">${r.r.grade}</span>` : '—' }], sts.map(s => ({ s, p: S.parent(s.parentId), a: S.studentAtt(s.id), f: S.feeInfo(s.id), r: last ? S.examResult(s.id, last.id) : null })), { href: r => '#/student/' + r.s.id });
    return UI.table([{ h: 'Roll', f: r => r.s.roll, cls: 'num' }, { h: 'Student', f: r => `<a href="#/student/${r.s.id}"><b>${esc(r.s.name)}</b></a><div class="muted small">${esc(r.s.adm)}</div>` }, { h: 'Attendance', f: r => attBadge(r.a.pct) }, { h: tc.join(', ') + (last ? ' – ' + last.name : ''), f: r => r.m == null ? '—' : r.m.toFixed(0) + '%', cls: 'num' }], sts.map(s => ({ s, a: S.studentAtt(s.id), m: (() => { if (!last) return null; const vals = tc.map(sb => { const rec = S.marksRec(last.id, cid, sb); return rec && rec.status === 'published' && rec.entries[s.id] && rec.entries[s.id].obt != null ? rec.entries[s.id].obt * 100 / rec.max : null; }).filter(x => x != null); return vals.length ? C.avg(vals) : null; })() })), { href: r => '#/student/' + r.s.id });
  }
  Pages.myclasses = {
    roles: ['teacher'],
    render(ctx) {
      const u = ctx.u, tc = S.teacherClasses(u.empId), ct = S.classTeacherClass(u.empId);
      if (ctx.arg) { const cid = ctx.arg; if (!tc[cid]) return UI.head({ title: 'Access restricted' }) + UI.card('', UI.empty('You are not assigned to this class')); const c = S.cls(cid), full = ct && ct.id === cid, sd = S.schoolDay(); const done = !!S.classAtt(cid, sd);
        return `<div class="crumbs"><a href="#/myclasses">My classes</a> › ${c.name}</div>` + UI.head({ title: c.name + (full ? ' · Class Teacher' : ''), sub: `${esc(c.room)} · ${S.studentsOf(cid).length} students · You teach: ${esc(tc[cid].join(', ') || '—')}`, actions: (full ? UI.link('Mark attendance', '#/attendance', { cls: 'primary', icon: 'check' }) : '') + (tc[cid].length ? UI.link('Enter marks', '#/marks?c=' + cid, { icon: 'award' }) : '') }) + (full ? `<div class="alert info mb">${UI.icon('shield', 16)}<div>You are the <b>class teacher</b> of ${c.name}, so you can view complete student details. ${done ? 'Attendance marked for ' + C.fmtDay(sd) + '.' : '<b>Attendance for ' + C.fmtDay(sd) + ' is pending.</b>'}</div></div>` : `<div class="alert mb">${UI.icon('lock', 16)}<div>You teach this class but are not its class teacher. Personal details (contacts, address, fees) are restricted.</div></div>`) + UI.card(full ? 'Student details' : 'Class list', teacherStudentTable(cid, u, full), { flush: true });
      }
      return UI.head({ title: 'My classes', sub: 'Classes and subjects assigned to you by the Dean.' }) + `<div class="grid g3">${Object.entries(tc).map(([cid, sb]) => { const c = S.cls(cid); return `<a class="card" href="#/myclasses/${cid}" style="text-decoration:none;color:inherit"><div class="card-b"><div class="row between"><h3 style="font-size:18px">${c.name}</h3>${ct && ct.id === cid ? UI.badge('Class Teacher', 'gold') : ''}</div><div class="muted small" style="margin:4px 0 12px">${esc(c.room)} · ${S.studentsOf(cid).length} students</div><div class="row wrap">${sb.map(x => UI.badge(x, 'navy')).join('') || '<span class="muted small">Class teacher responsibilities</span>'}</div><div class="mt-s small muted">Attendance ${S.classAttPct(cid)}%</div></div></a>`; }).join('')}</div>`;
    }
  };
  Pages.mystudents = {
    roles: ['teacher'],
    render(ctx) {
      const u = ctx.u, tc = S.teacherClasses(u.empId), ct = S.classTeacherClass(u.empId), last = lastExam(); const ids = Object.keys(tc);
      const rows = () => S.students().filter(s => tc[s.classId]).map(s => ({ s, ac: S.studentAccess(u, s.id), a: S.studentAtt(s.id), p: S.parent(s.parentId), f: S.feeInfo(s.id), r: last ? S.examResult(s.id, last.id) : null }));
      return UI.head({ title: 'My students', sub: 'Students in the classes you teach. Contact and fee details are visible only for your own class-teacher class.' }) + UI.listView({ id: 'mystudents', csv: 'my_students', source: rows, pageSize: 15, href: r => '#/student/' + r.s.id, filters: [{ k: 'q', type: 'search', label: 'Search', ph: 'Student or admission no.' }, { k: 'c', type: 'select', label: 'Class', options: [['', 'All my classes']].concat(ids.map(i => [i, S.className(i)])) }], filter: (r, f) => (!f.c || r.s.classId === f.c) && (!f.q || (r.s.name + r.s.adm).toLowerCase().includes(f.q.toLowerCase())),
        cols: [{ h: 'Student', f: r => stuPerson(r.s), csv: r => r.s.name }, { h: 'Class', f: r => S.className(r.s.classId) }, { h: 'Roll', f: r => r.s.roll, cls: 'num' }, { h: 'Parent', f: r => r.ac.contact ? `<b>${esc(r.p.name)}</b><div class="muted small">${C.phone(r.p.phone)}</div>` : '<span class="muted small">Restricted</span>', csv: r => r.ac.contact ? r.p.name + ' ' + r.p.phone : '' }, { h: 'Attendance', f: r => attBadge(r.a.pct), csv: r => r.a.pct + '%' }, { h: 'Fee status', f: r => r.ac.fees === 'status' ? UI.status(r.f.status) : '<span class="muted small">Restricted</span>', csv: r => r.ac.fees === 'status' ? r.f.status : '' }, { h: last ? last.name : 'Exam', f: r => r.ac.marks === true && r.r && r.r.done ? r.r.pct + '%' : '—', cls: 'num' }] });
    }
  };
})(window);
