/* pages-ops.js — operations: cleaning tasks, maintenance requests, principal operations overview */
(function (G) {
  'use strict';
  const C = G.C, S = G.S, UI = G.UI, esc = C.esc, App = G.App, H = G.H;
  const Pages = G.Pages = G.Pages || {};
  const CATS = ['Classroom', 'Washroom', 'Laboratory', 'Office', 'Corridor', 'Playground', 'Waste Management'];
  const PRI = ['High', 'Medium', 'Low'];
  const opsStaff = () => S.employees().filter(e => e.role === 'ops' && !e.supervisor);

  /* ---------- tasks ---------- */
  function taskActions(t, u) {
    const sup = u.supervisor; const mine = sup || t.assignedTo === u.empId; if (!mine) return '';
    const b = [];
    if (t.status === 'Pending' || t.status === 'Requires Attention') b.push(`<button class="btn xs" data-act="taskSet" data-id="${t.id}" data-s="In Progress">Start</button>`);
    if (t.status !== 'Completed') b.push(`<button class="btn xs ok" data-act="taskSet" data-id="${t.id}" data-s="Completed">Complete</button>`, `<button class="btn xs danger" data-act="taskAttn" data-id="${t.id}" title="Flag as requires attention">${UI.icon('alert', 12)}</button>`);
    if (t.status === 'Completed' && sup && !t.verified) b.push(`<button class="btn xs primary" data-act="verifyTask" data-id="${t.id}">Verify</button>`);
    if (t.status === 'Completed' && !sup) b.push(`<button class="btn xs" data-act="taskSet" data-id="${t.id}" data-s="In Progress">Reopen</button>`);
    return `<div class="row" style="gap:5px">${b.join('')}</div>`;
  }
  const tcols = (u, compact) => [{ h: 'Task', f: t => `<b>${esc(t.task)}</b><div class="muted small">${esc(t.category)}</div>`, csv: t => t.task }, { h: 'Location', f: t => esc(t.location) }, { h: 'Assigned to', f: t => esc(S.emp(t.assignedTo).name) }, { h: 'Date', f: t => C.fmtDay(t.date), csv: t => t.date }, { h: 'Time', f: t => C.t12(t.time) }, { h: 'Priority', f: t => UI.status(t.priority) }, { h: 'Status', f: t => UI.status(t.status) + (t.verified ? `<div class="tiny muted">✓ Verified</div>` : t.status === 'Completed' ? '<div class="tiny muted">Awaiting verification</div>' : ''), csv: t => t.status }, { h: 'Remarks', f: t => esc(t.remarks) || '—' }, { h: '', csv: false, f: t => taskActions(t, u) }].filter((c, i) => !compact || ![3, 4, 7].includes(i));
  function tasksTable(rows, u, compact) { return UI.table(tcols(u, compact), rows, { empty: 'No tasks' }); }
  function tasksPage(mode) {
    return ctx => {
      const u = ctx.u, sup = u.supervisor, sd = S.schoolDay(); const own = t => sup || t.assignedTo === u.empId;
      const titles = { today: ["Today's tasks", 'Cleaning and upkeep assigned for ' + C.fmtDate(sd)], cleaning: ['Cleaning', 'Classroom, washroom, laboratory, office, corridor and waste-management tasks'], done: ['Completed tasks', 'Finished tasks and supervisor verification'] }[mode];
      const src = () => S.db().tasks.filter(t => own(t) && (mode === 'today' ? t.date === sd : mode === 'done' ? t.status === 'Completed' : true)).sort((a, b) => b.date.localeCompare(a.date) || a.time.localeCompare(b.time));
      const todays = S.db().tasks.filter(t => t.date === sd && own(t));
      return UI.head({ title: titles[0], sub: titles[1], actions: sup ? UI.btn('Generate today’s tasks', 'genTasks', { icon: 'refresh' }) + UI.btn('New task', 'newTask', { cls: 'primary', icon: 'plus' }) : '' }) +
        (mode === 'today' ? `<div class="grid g4 mb">${['Pending', 'In Progress', 'Completed', 'Requires Attention'].map((k, i) => UI.kpi({ label: k, value: todays.filter(t => t.status === k).length, icon: ['dot', 'clock', 'check', 'alert'][i], tone: ['warn', '', 'ok', 'bad'][i] })).join('')}</div>` : '') +
        UI.listView({ id: 'tasks_' + mode, csv: 'tasks', source: src, pageSize: 12, filters: [{ k: 'q', type: 'search', label: 'Search', ph: 'Task or location' }, { k: 'c', type: 'select', label: 'Category', options: [['', 'All']].concat(CATS) }, { k: 's', type: 'select', label: 'Status', options: [['', 'All'], 'Pending', 'In Progress', 'Completed', 'Requires Attention'] }].concat(sup ? [{ k: 'a', type: 'select', label: 'Staff', options: [['', 'All staff']].concat(opsStaff().map(e => [e.id, e.name])) }] : []).concat(mode !== 'today' ? [{ k: 'from', type: 'date', label: 'From' }] : []),
          filter: (t, f) => (!f.c || t.category === f.c) && (!f.s || t.status === f.s) && (!f.a || t.assignedTo === f.a) && (!f.from || t.date >= f.from) && (mode !== 'cleaning' || ['Classroom', 'Washroom', 'Laboratory', 'Office', 'Corridor'].includes(t.category) || true) && (!f.q || (t.task + t.location).toLowerCase().includes(f.q.toLowerCase())), cols: tcols(u) });
    };
  }
  Pages.tasks = { roles: ['ops'], render: tasksPage('today'), table: tasksTable };
  Pages.cleaning = { roles: ['ops'], render: tasksPage('cleaning') };
  Pages.completed = { roles: ['ops'], render: tasksPage('done') };
  UI.act.taskSet = t => { S.setTaskStatus(t.dataset.id, t.dataset.s); UI.toast('Task marked ' + t.dataset.s, 'ok'); App.refresh(); };
  UI.act.verifyTask = t => { S.verifyTask(t.dataset.id); UI.toast('Task verified', 'ok', 'Visible to the Principal as verified work'); App.refresh(); };
  UI.act.taskAttn = t => UI.modal({ title: 'Flag task – requires attention', size: 'sm', body: UI.field('What is the problem?', '<textarea class="input" id="attnNote" placeholder="e.g. Water supply cut – need plumber"></textarea>'), footer: '<button class="btn" data-act="closeModal">Cancel</button><button class="btn danger" id="attnGo">Flag task</button>', onMount: el => el.querySelector('#attnGo').onclick = () => { S.setTaskStatus(t.dataset.id, 'Requires Attention', document.getElementById('attnNote').value.trim() || 'Needs supervisor attention'); UI.closeModal(); UI.toast('Flagged for supervisor', 'ok'); App.refresh(); } });
  UI.act.genTasks = () => { const n = S.genDailyTasks(S.nextSchoolDay()); UI.toast(n ? n + ' tasks generated for ' + C.fmtDate(S.nextSchoolDay()) : 'Tasks already exist for this day', n ? 'ok' : ''); App.refresh(); };
  UI.act.newTask = () => UI.modal({ title: 'Create task', size: 'lg', body: `<form id="tkForm" class="form-grid">${UI.field('Task', UI.input('task', '', 'required placeholder="e.g. Classroom cleaning"'))}${UI.field('Category', UI.select('category', CATS))}${UI.field('Location', UI.input('location', '', 'required placeholder="e.g. Grade 4 block, Room 401"'))}${UI.field('Assign to', UI.select('assignedTo', opsStaff().map(e => [e.id, e.name])))}${UI.field('Date', UI.input('date', S.nextSchoolDay(), 'type="date"'))}${UI.field('Time', UI.input('time', '09:00', 'type="time"'))}${UI.field('Priority', UI.select('priority', PRI, 'Medium'))}${UI.field('Remarks', UI.input('remarks', ''))}</form>`, footer: '<button class="btn" data-act="closeModal">Cancel</button><button class="btn primary" data-act="saveTask">Create task</button>' });
  UI.act.saveTask = () => { const f = document.getElementById('tkForm'); if (!f.reportValidity()) return; S.addTask(UI.formData(f)); UI.closeModal(); UI.toast('Task created', 'ok'); App.refresh(); };

  /* ---------- maintenance ---------- */
  const ISSUES = ['Broken fan', 'Light not working', 'Projector issue', 'Water leakage', 'Damaged desk', 'Washroom issue', 'Other'];
  G.App.reportIssueModal = () => UI.modal({ title: 'Report a maintenance issue', size: 'lg', body: `<form id="isForm" class="form-grid">${UI.field('Location *', `<input class="input" name="location" list="locs" required placeholder="e.g. Grade 6A classroom">`)}<datalist id="locs">${S.classes().map(c => `<option value="${c.name} Classroom">`).join('')}<option value="Science Laboratory"><option value="Computer Laboratory"><option value="Staff Room"><option value="Library"><option value="Washroom – Ground Floor"><option value="Playground"><option value="Main Corridor"></datalist>${UI.field('Issue *', UI.select('issue', ISSUES))}${UI.field('Priority', UI.select('priority', PRI, 'Medium'))}${UI.field('Reported by', UI.input('by', App.u.name, 'disabled'))}${UI.field('Description *', '<textarea class="input" name="description" required placeholder="Describe the problem so the maintenance team can act quickly"></textarea>', { cls: 'full' })}${UI.field('Photo (optional)', '<input type="file" accept="image/*" class="input" id="isPhoto" data-on="isPhoto"><div id="isPrev"></div>', { cls: 'full' })}</form>`, footer: `<a class="btn" href="#/myissues" data-act="closeModal" style="margin-right:auto">My reported issues</a><button class="btn" data-act="closeModal">Cancel</button><button class="btn primary" data-act="saveIssue">Submit report</button>` });
  UI.on.isPhoto = t => { const f = t.files[0]; if (!f) return; UI.readImage(f, d => { G.__isPhoto = d; document.getElementById('isPrev').innerHTML = `<img src="${d}" style="max-height:110px;border-radius:8px;margin-top:8px;border:1px solid var(--line)">`; }); };
  UI.act.saveIssue = () => { const f = document.getElementById('isForm'); if (!f.reportValidity()) return; const d = UI.formData(f); const m = S.reportIssue({ location: d.location, issue: d.issue, priority: d.priority, description: d.description, photo: G.__isPhoto || null }); G.__isPhoto = null; UI.closeModal(); UI.toast('Issue reported – ' + m.id, 'ok', 'The Operations team has been notified.'); if (App.route.page === 'issues' || App.route.page === 'maintenance' || App.route.page === 'myissues') App.refresh(); };
  function maintCols(u) { return [{ h: 'Ref', f: m => `<b>${m.id}</b><div class="muted tiny">${C.fmtDate(m.date)}</div>`, csv: m => m.id }, { h: 'Issue', f: m => `<b>${esc(m.issue)}</b><div class="muted small">${esc(m.location)}</div>`, csv: m => m.issue + ' – ' + m.location }, { h: 'Description', f: m => `<span class="small">${esc(m.description.length > 70 ? m.description.slice(0, 67) + '…' : m.description)}</span>`, csv: m => m.description }, { h: 'Reported by', f: m => esc(m.reportedBy) }, { h: 'Priority', f: m => UI.status(m.priority), csv: m => m.priority }, { h: 'Assigned to', f: m => m.assignedTo ? esc(S.emp(m.assignedTo).name) : '<span class="muted">Unassigned</span>', csv: m => m.assignedTo ? S.emp(m.assignedTo).name : '' }, { h: 'Status', f: m => UI.status(m.status), csv: m => m.status }, { h: '', csv: false, f: m => UI.btn(u.role === 'ops' ? 'Update' : 'View', 'maintOpen', { cls: 'xs', data: { id: m.id } }) }]; }
  function maintPage(mode) {
    return ctx => {
      const u = ctx.u; const all = S.db().maint; const src = () => all.filter(m => mode === 'issues' ? (u.supervisor || u.role !== 'ops' || true) : m.status === 'Assigned' || m.status === 'In Progress').filter(m => u.supervisor || mode === 'issues' ? true : m.assignedTo === u.empId).sort((a, b) => b.ts.localeCompare(a.ts));
      return UI.head({ title: mode === 'issues' ? 'Reported issues' : 'Maintenance', sub: mode === 'issues' ? 'Issues reported by teachers and staff. Assign and update progress.' : 'Work in progress – assigned and ongoing repairs.', actions: UI.btn('Report issue', 'reportIssue', { cls: 'primary', icon: 'plus' }) }) + `<div class="grid g4 mb">${['Reported', 'Assigned', 'In Progress', 'Resolved'].map((k, i) => UI.kpi({ label: k, value: all.filter(m => m.status === k).length, icon: ['alert', 'user', 'wrench', 'check'][i], tone: ['warn', '', '', 'ok'][i] })).join('')}</div>` + UI.listView({ id: 'maint_' + mode, csv: 'maintenance', source: src, pageSize: 10, filters: [{ k: 'q', type: 'search', label: 'Search', ph: 'Issue, location' }, { k: 's', type: 'select', label: 'Status', options: [['', 'All'], 'Reported', 'Assigned', 'In Progress', 'Resolved'] }, { k: 'p', type: 'select', label: 'Priority', options: [['', 'All'], 'High', 'Medium', 'Low'] }], filter: (m, f) => (!f.s || m.status === f.s) && (!f.p || m.priority === f.p) && (!f.q || (m.issue + m.location + m.description).toLowerCase().includes(f.q.toLowerCase())), cols: maintCols(u) });
    };
  }
  Pages.maintenance = { roles: ['ops'], render: maintPage('maint') };
  Pages.issues = { roles: ['ops'], render: maintPage('issues') };
  Pages.myissues = { roles: ['teacher', 'dean', 'accountant', 'principal'], render(ctx) { const rows = S.db().maint.filter(m => m.reportedBy === ctx.u.name).sort((a, b) => b.ts.localeCompare(a.ts)); return UI.head({ title: 'My reported issues', sub: 'Track maintenance requests you have raised.', actions: UI.btn('Report issue', 'reportIssue', { cls: 'primary', icon: 'plus' }) }) + UI.card('', UI.table(maintCols(ctx.u).slice(0, 7).concat([{ h: '', f: m => UI.btn('Track', 'maintOpen', { cls: 'xs', data: { id: m.id } }) }]), rows, { empty: 'You have not reported any issues' }), { flush: true }); } };
  UI.act.maintOpen = t => {
    const u = App.u, m = S.db().maint.find(x => x.id === t.dataset.id); const sup = u.role === 'ops' && u.supervisor, staff = u.role === 'ops'; const mine = sup || (staff && m.assignedTo === u.empId);
    UI.modal({ title: m.issue + ' · ' + m.id, size: 'lg', body: `<div class="grid g-21"><div>${UI.dl([['Location', esc(m.location)], ['Priority', UI.status(m.priority)], ['Status', UI.status(m.status)], ['Reported by', esc(m.reportedBy)], ['Date', C.fmtStamp(m.ts)], ['Assigned to', m.assignedTo ? esc(S.emp(m.assignedTo).name) : 'Unassigned'], ['Description', esc(m.description)]])}${m.photo ? `<img src="${m.photo}" style="max-width:100%;max-height:220px;border-radius:8px;margin-top:12px;border:1px solid var(--line)">` : ''}</div><div><div class="strong small" style="margin-bottom:8px">Activity</div>${m.updates.map(x => `<div style="border-left:2px solid var(--line);padding:0 0 12px 12px;margin-left:4px"><div class="small"><b>${esc(x.by)}</b> <span class="muted">· ${C.fmtStamp(x.ts)}</span></div><div class="small">${esc(x.note)}</div></div>`).join('')}</div></div>${mine ? `<hr style="border:0;border-top:1px solid var(--line);margin:16px 0"><form id="mtForm" class="form-grid">${sup ? UI.field('Assign to', `<select class="input" name="assignedTo"><option value="">Unassigned</option>${UI.opts(S.employees().filter(e => e.role === 'ops').map(e => [e.id, e.name]), m.assignedTo)}</select>`) : ''}${UI.field('Status', UI.select('status', ['Reported', 'Assigned', 'In Progress', 'Resolved'], m.status))}${UI.field('Update note', '<textarea class="input" name="note" placeholder="What was done / what is needed?"></textarea>', { cls: 'full' })}</form>` : ''}`, footer: `<button class="btn" data-act="closeModal">Close</button>${mine ? `<button class="btn primary" data-act="maintSave" data-id="${m.id}">Save update</button>` : ''}` });
  };
  UI.act.maintSave = t => { const d = UI.formData(document.getElementById('mtForm')); const m = S.db().maint.find(x => x.id === t.dataset.id); const patch = { status: d.status }; if (d.assignedTo !== undefined) { patch.assignedTo = d.assignedTo || null; if (d.assignedTo && d.status === 'Reported') patch.status = 'Assigned'; } S.updateMaint(m.id, patch, d.note.trim() || null); UI.closeModal(); UI.toast('Request updated', 'ok'); App.refresh(); };

  /* ---------- Principal operations overview ---------- */
  Pages.operations = {
    roles: ['principal'],
    render() {
      const db = S.db(), sd = S.schoolDay(), T = C.today(); const days = Array.from(new Set(db.tasks.map(t => t.date))).filter(d => d <= T).sort().slice(-5);
      const tk = db.tasks.filter(t => t.date === sd), done = tk.filter(t => t.status === 'Completed'), open = db.maint.filter(m => m.status !== 'Resolved');
      const cat = CATS.map(c => { const x = db.tasks.filter(t => t.category === c && t.date <= T); return { label: c, value: C.pct(x.filter(t => t.status === 'Completed').length, x.length, 0) }; });
      const staff = opsStaff().map(e => { const x = db.tasks.filter(t => t.assignedTo === e.id && t.date <= T); return { e, n: x.length, d: x.filter(t => t.status === 'Completed').length, v: x.filter(t => t.verified).length, a: x.filter(t => t.status === 'Requires Attention').length }; });
      const clean = C.pct(db.tasks.filter(t => t.date <= T && t.verified).length, db.tasks.filter(t => t.date <= T && t.status === 'Completed').length, 0);
      return UI.head({ title: 'Operations', sub: 'Cleaning, upkeep and maintenance across the campus – ' + C.fmtDate(sd) }) + `<div class="grid g4">${UI.kpi({ label: 'Tasks completed today', value: done.length + ' / ' + tk.length, sub: C.pct(done.length, tk.length, 0) + '% complete', icon: 'check', tone: 'ok' })}${UI.kpi({ label: 'Verified by supervisor', value: tk.filter(t => t.verified).length, sub: clean + '% of completed work verified overall', icon: 'shield' })}${UI.kpi({ label: 'Requires attention', value: tk.filter(t => t.status === 'Requires Attention').length, sub: 'Today · ' + db.tasks.filter(t => t.status === 'Requires Attention').length + ' this week', icon: 'alert', tone: 'bad' })}${UI.kpi({ label: 'Open maintenance requests', value: open.length, sub: open.filter(m => m.priority === 'High').length + ' high priority', icon: 'wrench', tone: 'warn' })}</div>
      <div class="grid g-21 mt">${UI.card('Task completion – last 5 school days', UI.chart.bars({ labels: days.map(d => C.fmtDay(d)), series: [{ name: 'Completed', data: days.map(d => db.tasks.filter(t => t.date === d && t.status === 'Completed').length), color: UI.PAL[2] }, { name: 'Requires attention', data: days.map(d => db.tasks.filter(t => t.date === d && t.status === 'Requires Attention').length), color: UI.PAL[3] }, { name: 'Pending / in progress', data: days.map(d => db.tasks.filter(t => t.date === d && ['Pending', 'In Progress'].includes(t.status)).length), color: UI.PAL[1] }], stacked: true, fmt: v => v, height: 230 }))}${UI.card('Cleanliness score by area', UI.chart.hbars({ items: cat, max: 100, fmt: v => v + '%' }), { sub: 'Completed share of all tasks' })}</div>
      <div class="grid g3 mt">${UI.card('Maintenance by status', UI.chart.donut({ items: ['Reported', 'Assigned', 'In Progress', 'Resolved'].map((k, i) => ({ label: k, value: db.maint.filter(m => m.status === k).length, color: ['#d99a2b', '#6f87ad', '#25609f', '#1b7f57'][i] })), center: db.maint.length, centerLabel: 'REQUESTS' }))}${UI.card('Open requests', open.slice(0, 5).map(m => `<div class="list-i"><div class="grow"><b>${esc(m.issue)}</b><div class="muted small">${esc(m.location)} · ${C.fmtDate(m.date)}</div></div><div class="col" style="align-items:flex-end;gap:4px">${UI.status(m.priority)}${UI.status(m.status)}</div></div>`).join('') || UI.empty('No open requests'), { flush: true })}${UI.card('Needs attention', db.tasks.filter(t => t.status === 'Requires Attention').slice(-5).reverse().map(t => `<div class="list-i"><div class="grow"><b>${esc(t.task)} – ${esc(t.location)}</b><div class="muted small">${C.fmtDay(t.date)} · ${esc(t.remarks)}</div></div></div>`).join('') || UI.empty('Nothing flagged'), { flush: true })}</div>
      <div class="mt">${UI.card('Operations staff performance', UI.table([{ h: 'Staff', f: r => UI.person(r.e.name, r.e.designation, r.e.name.length) }, { h: 'Tasks assigned', f: r => r.n, cls: 'num' }, { h: 'Completed', f: r => r.d, cls: 'num' }, { h: 'Verified', f: r => r.v, cls: 'num' }, { h: 'Flagged', f: r => r.a, cls: 'num' }, { h: 'Completion', f: r => `<div style="min-width:100px"><b class="mono">${C.pct(r.d, r.n, 0)}%</b>${UI.progress(C.pct(r.d, r.n, 0))}</div>` }], staff), { flush: true })}</div>`;
    }
  };
})(window);
