/* pages-finance.js — fee collection, pending fees, receipts, payroll, expenses, finance overview, reports */
(function (G) {
  'use strict';
  const C = G.C, S = G.S, UI = G.UI, esc = C.esc, App = G.App, H = G.H;
  const Pages = G.Pages = G.Pages || {};
  const METHODS = ['Cash', 'UPI', 'Card', 'Net Banking', 'Cheque'];
  const GRADES = [['', 'All grades']].concat([1, 2, 3, 4, 5, 6, 7, 8, 9, 10].map(g => [g, 'Grade ' + g]));
  const stuP = s => UI.person(s.name, s.adm, s.colorIdx, '#/fees/' + s.id);
  const mkRows = () => S.students().map(s => ({ s, p: S.parent(s.parentId), f: S.feeInfo(s.id) }));
  const feeFilter = (r, f) => (!f.g || r.s.grade == f.g) && (!f.sec || r.s.section === f.sec) && (!f.fs || r.f.status === f.fs) && (!f.q || (r.s.name + ' ' + r.s.adm + ' ' + r.p.name + ' ' + r.p.phone + ' ' + r.s.grade + r.s.section).toLowerCase().includes(f.q.toLowerCase()));
  const feeFilters = [{ k: 'q', type: 'search', label: 'Search student', ph: 'Name, admission no., parent name or phone' }, { k: 'g', type: 'select', label: 'Class', options: GRADES }, { k: 'sec', type: 'select', label: 'Section', options: [['', 'All'], 'A', 'B'] }, { k: 'fs', type: 'select', label: 'Payment status', options: [['', 'All'], 'Paid', 'Partially Paid', 'Pending', 'Overdue'] }];

  /* ---------- class-wise fee status table ---------- */
  function classWise(withLinks) {
    const rows = S.classes().map(c => ({ c, f: S.classFee(c.id) })); const tot = rows.reduce((a, r) => { ['total', 'Paid', 'Partially Paid', 'Pending', 'Overdue', 'expected', 'received', 'pending'].forEach(k => a[k] = (a[k] || 0) + r.f[k]); return a; }, {});
    return UI.table([{ h: 'Class', f: r => `<b>${r.c.name}</b>` }, { h: 'Students', f: r => r.f.total, cls: 'num' }, { h: 'Paid', f: r => `<span class="up">${r.f.Paid}</span>`, cls: 'num' }, { h: 'Partially paid', f: r => r.f['Partially Paid'], cls: 'num' }, { h: 'Pending', f: r => r.f.Pending, cls: 'num' }, { h: 'Overdue', f: r => r.f.Overdue ? `<b class="down">${r.f.Overdue}</b>` : 0, cls: 'num' }, { h: 'Total expected', f: r => C.inr(r.f.expected), cls: 'num' }, { h: 'Total received', f: r => C.inr(r.f.received), cls: 'num' }, { h: 'Pending amount', f: r => C.inr(r.f.pending), cls: 'num' }, { h: 'Collected', f: r => `<div style="min-width:90px"><b class="mono">${C.pct(r.f.received, r.f.expected, 0)}%</b>${UI.progress(C.pct(r.f.received, r.f.expected, 0))}</div>` }], rows, { foot: `<td>All classes</td><td class="num">${tot.total}</td><td class="num">${tot.Paid}</td><td class="num">${tot['Partially Paid']}</td><td class="num">${tot.Pending}</td><td class="num">${tot.Overdue}</td><td class="num">${C.inr(tot.expected)}</td><td class="num">${C.inr(tot.received)}</td><td class="num">${C.inr(tot.pending)}</td><td>${C.pct(tot.received, tot.expected, 0)}%</td>` });
  }

  /* ---------- Fees (role switch) ---------- */
  function feesAccountant(ctx) {
    if (ctx.arg) return feeDetail(ctx, ctx.arg);
    const tab = App.tab('fees', 'collect'); const ft = S.feeTotals(); const T = C.today();
    const lv = UI.listView({ id: 'fees', title: 'Find a student', sub: 'Search by name, admission number, class, section, parent name or phone number', csv: 'student_fees', source: mkRows, filter: feeFilter, filters: feeFilters, pageSize: 12, href: r => '#/fees/' + r.s.id,
      cols: [{ h: 'Student', f: r => stuP(r.s), csv: r => r.s.name }, { h: 'Adm. no.', f: r => r.s.adm, cls: 'mono' }, { h: 'Class', f: r => S.className(r.s.classId) }, { h: 'Parent', f: r => `<b>${esc(r.p.name)}</b><div class="muted small">${C.phone(r.p.phone)}</div>`, csv: r => r.p.name + ' ' + r.p.phone }, { h: 'Yearly fee', f: r => C.inr(r.f.total), cls: 'num', csv: r => r.f.total }, { h: 'Paid', f: r => C.inr(r.f.paid), cls: 'num', csv: r => r.f.paid }, { h: 'Balance', f: r => `<b>${C.inr(r.f.balance)}</b>`, cls: 'num', csv: r => r.f.balance }, { h: 'Status', f: r => UI.status(r.f.status), csv: r => r.f.status }, { h: '', csv: false, f: r => r.f.balance > 0 ? `<a class="btn xs primary" href="#/fees/${r.s.id}">Collect</a>` : `<a class="btn xs" href="#/fees/${r.s.id}">View</a>` }] });
    return UI.head({ title: 'Fee collection', sub: 'Record payments, issue receipts and track balances.' }) + `<div class="grid g4 mb">${UI.kpi({ label: 'Collected today', value: C.inr(ft.today), icon: 'rupee', tone: 'ok', sub: S.db().payments.filter(p => p.date === T).length + ' receipts' })}${UI.kpi({ label: 'This month', value: C.inr(ft.month), icon: 'wallet', tone: 'ok' })}${UI.kpi({ label: 'Pending balance', value: C.inrK(ft.pending), icon: 'alert', tone: 'bad', href: '#/pending' })}${UI.kpi({ label: 'Overdue students', value: ft.status.Overdue, icon: 'clock', tone: 'warn', href: '#/pending' })}</div>` + App.tabs('fees', [['collect', 'Collect fees'], ['class', 'Class-wise status']], tab) + (tab === 'collect' ? lv : UI.card('Class-wise fee status', classWise(), { flush: true, sub: 'Total students, paid / partially paid / pending / overdue, expected and received amounts' }));
  }
  function feeDetail(ctx, sid) {
    const s = S.student(sid); if (!s) return UI.head({ title: 'Student not found' }); const p = S.parent(s.parentId), f = S.feeInfo(sid);
    const defAmt = f.overdueAmt || (f.next ? f.next.amount : f.balance);
    return `<div class="crumbs"><a href="#/fees">Fee collection</a> › ${esc(s.name)}</div><div class="card mb"><div class="card-b row wrap" style="gap:18px">${UI.avatar(s.name, s.colorIdx, 'lg')}<div class="grow"><h1 style="font-family:var(--serif);font-size:23px">${esc(s.name)} ${UI.status(f.status)}</h1><div class="row wrap muted" style="gap:4px 18px;margin-top:4px"><span>${esc(s.adm)}</span><span>${esc(S.className(s.classId))} · Roll ${s.roll}</span><span>Parent: <b style="color:var(--text)">${esc(p.name)}</b></span><span>${UI.icon('phone', 13)} ${C.phone(p.phone)}</span></div></div></div></div>` +
      H.feeBlock(sid, false).replace(/^/, '') + `<div class="grid g-21">${UI.card('Instalments', UI.table([{ h: 'Instalment', f: r => r.label }, { h: 'Due date', f: r => C.fmtDate(r.due) }, { h: 'Amount', f: r => C.inr(r.amount), cls: 'num' }, { h: 'Paid', f: r => C.inr(r.paid), cls: 'num' }, { h: 'Pending', f: r => C.inr(r.pending), cls: 'num' }, { h: 'Status', f: r => UI.status(r.status) }], f.terms), { flush: true })}
      ${f.balance > 0 ? UI.card('Record payment', `<form id="payForm" class="col" style="gap:12px" data-sid="${sid}">${UI.field('Amount (₹)', `<input class="input num" name="amount" type="number" min="1" max="${f.balance}" value="${defAmt}" data-on="payAmt" required>`, { hint: 'Balance ' + C.inr(f.balance) + '. Part-payments are allowed.' })}<div class="row wrap"><button type="button" class="btn xs" data-act="payQuick" data-v="${f.next ? f.next.amount : f.balance}">Next instalment</button><button type="button" class="btn xs" data-act="payQuick" data-v="${f.balance}">Full balance</button></div>${UI.field('Payment method', UI.select('method', METHODS, 'UPI'))}${UI.field('Reference / UPI / cheque no.', UI.input('ref', '', 'placeholder="Optional for cash"'))}${UI.field('Payment date', UI.input('date', C.today(), `type="date" max="${C.today()}"`))}<div class="note-row" id="payPreview"></div><button type="button" class="btn primary block" data-act="payRecord">${UI.icon('receipt', 15)} Record payment & generate receipt</button></form>`, {}) : UI.card('Fee fully paid', `<div class="alert ok">${UI.icon('check', 16)}<div>All dues for ${S.db().ay} are cleared. No payment is due.</div></div>`)}</div>
      <div class="mt">${UI.card('Payment history', UI.table([{ h: 'Receipt no.', f: r => `<b>${r.rcpt}</b>` }, { h: 'Date', f: r => C.fmtDate(r.date) }, { h: 'Instalment', f: r => esc(r.term) }, { h: 'Method', f: r => esc(r.method) }, { h: 'Reference', f: r => esc(r.ref) || '—' }, { h: 'Received by', f: r => esc(r.by) }, { h: 'Amount', f: r => C.inr(r.amount), cls: 'num' }, { h: '', f: r => UI.btn('Receipt', 'receipt', { cls: 'xs', icon: 'receipt', data: { id: r.id } }) }], f.payments, { empty: 'No payments recorded yet' }), { flush: true, actions: f.balance > 0 ? UI.btn('Send WhatsApp reminder', 'remindOne', { cls: 'sm', icon: 'wa', data: { id: sid } }) : '' })}</div>`;
  }
  const upPay = () => { const f = document.getElementById('payForm'); if (!f) return; const fi = S.feeInfo(f.dataset.sid); const a = +f.amount.value || 0; document.getElementById('payPreview').innerHTML = `Balance after this payment: <b>${C.inr(Math.max(0, fi.balance - a))}</b>${a > fi.balance ? ' <span class="down">(exceeds balance)</span>' : ''}`; };
  UI.on.payAmt = upPay; UI.act.payQuick = t => { const f = document.getElementById('payForm'); f.amount.value = t.dataset.v; upPay(); };
  UI.act.payRecord = () => {
    const f = document.getElementById('payForm'); if (!f.reportValidity()) return; const d = UI.formData(f); const r = S.recordPayment({ sid: f.dataset.sid, amount: d.amount, method: d.method, ref: d.ref, date: d.date }); if (r.error) { UI.toast(r.error, 'bad'); return; }
    const s = S.student(f.dataset.sid);
    UI.modal({ title: 'Payment recorded', size: 'sm', body: `<div class="center" style="margin-bottom:12px"><div style="color:var(--ok);display:grid;place-items:center">${UI.icon('check', 40)}</div><h3 style="margin-top:6px">${C.inr(r.payment.amount)} received</h3><div class="muted small">Receipt ${r.payment.rcpt}</div></div>${UI.dl([['Student', esc(s.name)], ['Method', esc(r.payment.method)], ['New balance', '<b>' + C.inr(r.info.balance) + '</b>'], ['Status', UI.status(r.info.status)]])}<div class="mt-s"><div class="tiny muted" style="margin-bottom:3px">WhatsApp to ${esc(r.notice.to)} · ${r.notice.status}</div>${UI.wa(r.notice.message)}</div>`, footer: `<button class="btn" data-act="closeModal">Done</button><button class="btn primary" data-act="receipt" data-id="${r.payment.id}">View receipt</button>` });
    App.refresh();
  };
  UI.act.remindOne = t => { const n = S.sendFeeReminder(t.dataset.id); UI.waToast(n); };

  function feesPrincipal(ctx) {
    const ft = S.feeTotals(), fin = H.finMonthly(), db = S.db();
    const top = mkRows().filter(r => r.f.status === 'Overdue').sort((a, b) => b.f.overdueAmt - a.f.overdueAmt).slice(0, 8);
    return UI.head({ title: 'Fees', sub: 'Fee collection and outstanding balances – live from the Accounts office.', actions: UI.link('Fee reports', '#/reports', { icon: 'chart' }) + UI.link('Student fee directory', '#/students', { icon: 'users' }) }) +
      `<div class="grid g4">${UI.kpi({ label: 'Collected today', value: C.inr(ft.today), icon: 'rupee', tone: 'ok' })}${UI.kpi({ label: 'This month', value: C.inr(ft.month), icon: 'wallet', tone: 'ok' })}${UI.kpi({ label: 'Academic year', value: C.inrK(ft.year), sub: C.pct(ft.collected, ft.expected, 0) + '% of ' + C.inrK(ft.expected), icon: 'trend' })}${UI.kpi({ label: 'Pending', value: C.inrK(ft.pending), sub: ft.status.Overdue + ' overdue students', icon: 'alert', tone: 'bad' })}</div>
      <div class="grid g-21 mt">${UI.card('Monthly fee collection', UI.chart.bars({ labels: fin.ms.map(C.monthLabel), series: [{ name: 'Collected', data: fin.income, color: UI.PAL[2] }], fmt: C.inrK, height: 230 }))}${UI.card('Fee status', UI.chart.donut({ items: [{ label: 'Paid', value: ft.status.Paid, color: '#1b7f57' }, { label: 'Partially paid', value: ft.status['Partially Paid'], color: '#25609f' }, { label: 'Pending', value: ft.status.Pending, color: '#d99a2b' }, { label: 'Overdue', value: ft.status.Overdue, color: '#b3261e' }], center: db.students.length, centerLabel: 'STUDENTS' }))}</div>
      <div class="mt">${UI.card('Class-wise fee status', classWise(), { flush: true })}</div>
      <div class="grid g2 mt">${UI.card('Highest overdue balances', UI.table([{ h: 'Student', f: r => UI.person(r.s.name, S.className(r.s.classId), r.s.colorIdx, '#/student/' + r.s.id) }, { h: 'Overdue', f: r => `<b class="down">${C.inr(r.f.overdueAmt)}</b>`, cls: 'num' }, { h: 'Days', f: r => r.f.overdueDays, cls: 'num' }], top), { flush: true })}${UI.card('Recent receipts', db.payments.slice().sort((a, b) => b.ts.localeCompare(a.ts)).slice(0, 7).map(p => `<div class="list-i"><div class="grow"><b>${esc(S.student(p.sid).name)}</b><div class="muted small">${p.rcpt} · ${esc(p.method)}</div></div><b>${C.inr(p.amount)}</b></div>`).join(''), { flush: true, actions: '<a class="btn sm" href="#/receipts">All receipts</a>' })}</div>`;
  }
  /* parent / student fees + online payment */
  function feesFamily(ctx) {
    const u = ctx.u, sid = u.studentId, f = S.feeInfo(sid), isP = u.role === 'parent', s = S.student(sid), en = S.db().settings.onlinePayments;
    if (!isP) return UI.head({ title: 'Fees', sub: 'Fee information is managed by your parent / guardian.' }) + H.feeBlock(sid, false) + UI.card('', `<div class="alert info">${UI.icon('lock', 16)}<div>Payment details and receipts are available in the Parent portal.</div></div>`);
    return UI.head({ title: 'Fees', sub: s.name + ' · ' + S.className(s.classId) + ' · AY ' + S.db().ay, actions: f.balance > 0 ? UI.btn(en ? 'Pay online' : 'Online payment unavailable', 'payOnline', { cls: 'primary', icon: 'wallet', data: {} }).replace('<button', en ? '<button' : '<button disabled') : '' }) +
      (f.status === 'Overdue' ? `<div class="alert bad mb">${UI.icon('alert', 17)}<div><b>${C.inr(f.overdueAmt)} is overdue</b> (${f.overdueDays} days). Please pay at the earliest to avoid hall-ticket or report-card holds.</div></div>` : f.next ? `<div class="alert info mb">${UI.icon('calendar', 17)}<div>Next instalment <b>${C.inr(f.next.amount)}</b> is due on <b>${C.fmtDate(f.next.due)}</b>.</div></div>` : '') + H.feeBlock(sid, true, u);
  }
  UI.act.payOnline = () => {
    const sid = App.u.studentId, f = S.feeInfo(sid); const def = f.overdueAmt || (f.next ? f.next.amount : f.balance);
    UI.modal({ title: 'Pay fees online', size: 'sm', body: `<form id="onForm" class="col" style="gap:14px">${UI.field('Amount (₹)', `<input class="input num" name="amount" type="number" min="1" max="${f.balance}" value="${def}">`, { hint: 'Outstanding balance ' + C.inr(f.balance) })}<div class="row wrap"><button type="button" class="btn xs" data-act="onQuick" data-v="${f.next ? f.next.amount : f.balance}">Next instalment</button><button type="button" class="btn xs" data-act="onQuick" data-v="${f.balance}">Pay full balance</button></div>${UI.field('Pay using', UI.select('via', ['UPI', 'Debit / Credit card', 'Net banking']))}<div class="note-row">${UI.icon('lock', 13)} Secure checkout. <span class="muted">Demo environment – no real money is charged.</span></div></form>`, footer: '<button class="btn" data-act="closeModal">Cancel</button><button class="btn primary" id="onPay">Pay securely</button>', onMount: el => el.querySelector('#onPay').onclick = () => { const d = UI.formData(document.getElementById('onForm')); const a = +d.amount; if (!(a > 0) || a > f.balance) { UI.toast('Enter an amount up to ' + C.inr(f.balance), 'bad'); return; } el.querySelector('.modal-b').innerHTML = `<div class="center" style="padding:30px 0"><div style="width:44px;height:44px;border:4px solid var(--navy-100);border-top-color:var(--navy-700);border-radius:50%;margin:auto;animation:spin 0.8s linear infinite"></div><p class="muted">Processing payment of ${C.inr(a)}…</p></div><style>@keyframes spin{to{transform:rotate(360deg)}}</style>`; el.querySelector('.modal-f').innerHTML = ''; setTimeout(() => { const r = S.recordPayment({ sid, amount: a, method: 'Online (Razorpay)', ref: 'pay_' + Math.random().toString(36).slice(2, 12).toUpperCase(), mode: 'Online' }); if (r.error) { UI.closeModal(); UI.toast(r.error, 'bad'); return; } el.querySelector('.modal-b').innerHTML = `<div class="center"><div style="color:var(--ok);display:grid;place-items:center">${UI.icon('check', 44)}</div><h3 style="margin:6px 0 2px">Payment successful</h3><div class="muted small">${C.inr(a)} paid · ${C.fmtStamp(r.payment.ts)}</div></div>${UI.dl([['Transaction ID', r.payment.ref], ['Receipt no.', r.payment.rcpt], ['Paid via', esc(d.via)], ['Balance now', '<b>' + C.inr(r.info.balance) + '</b>'], ['Status', UI.status(r.info.status)]])}<div class="mt-s"><div class="tiny muted" style="margin-bottom:3px">WhatsApp confirmation sent to ${C.phone(S.parentOf(sid).whatsapp)}</div>${UI.wa(r.notice.message)}</div>`; el.querySelector('.modal-f').innerHTML = `<button class="btn" data-act="closeModal">Close</button><button class="btn primary" data-act="receipt" data-id="${r.payment.id}">Download receipt</button>`; App.refresh(); UI.waToast(r.notice); }, 1300); } });
  };
  UI.act.onQuick = t => { document.querySelector('#onForm [name=amount]').value = t.dataset.v; };
  Pages.fees = { roles: ['accountant', 'principal', 'student', 'parent'], render: ctx => ({ accountant: feesAccountant, principal: feesPrincipal, student: feesFamily, parent: feesFamily }[ctx.u.role])(ctx), mount() { upPay(); } };

  /* ---------- Pending fees ---------- */
  Pages.pending = {
    roles: ['accountant'],
    render(ctx) {
      const rows = () => mkRows().filter(r => r.f.balance > 0); const od = rows().filter(r => r.f.status === 'Overdue');
      const lv = UI.listView({ id: 'pending', title: 'Pending & overdue payments', csv: 'pending_fees', print: true, source: rows, filter: feeFilter, filters: feeFilters.map(f => f.k === 'fs' ? { k: 'fs', type: 'select', label: 'Payment status', options: [['', 'All pending'], 'Partially Paid', 'Pending', 'Overdue'] } : f), pageSize: 12, init: {},
        cols: [{ h: 'Student', f: r => stuP(r.s), csv: r => r.s.name }, { h: 'Class', f: r => S.className(r.s.classId) }, { h: 'Parent', f: r => `<b>${esc(r.p.name)}</b><div class="muted small">${C.phone(r.p.phone)}</div>`, csv: r => r.p.name + ' ' + r.p.phone }, { h: 'Balance', f: r => `<b>${C.inr(r.f.balance)}</b>`, cls: 'num', csv: r => r.f.balance }, { h: 'Overdue', f: r => r.f.overdueAmt ? `<b class="down">${C.inr(r.f.overdueAmt)}</b> <span class="muted small">${r.f.overdueDays}d</span>` : '—', cls: 'num', csv: r => r.f.overdueAmt }, { h: 'Next due', f: r => r.f.next ? C.fmtDate(r.f.next.due) : '—', csv: r => r.f.next ? r.f.next.due : '' }, { h: 'Status', f: r => UI.status(r.f.status), csv: r => r.f.status }, { h: '', csv: false, f: r => `<div class="row"><button class="btn xs" data-act="remindOne" data-id="${r.s.id}" title="WhatsApp reminder">${UI.icon('wa', 13)}</button><a class="btn xs primary" href="#/fees/${r.s.id}">Collect</a></div>` }] });
      return UI.head({ title: 'Pending fees', sub: 'Outstanding balances with one-click WhatsApp reminders.', actions: UI.btn('Remind all overdue (' + od.length + ')', 'remindAll', { cls: 'primary', icon: 'wa' }) }) + `<div class="grid g4 mb">${UI.kpi({ label: 'Overdue students', value: od.length, sub: C.inr(C.sum(od, r => r.f.overdueAmt)) + ' overdue', icon: 'alert', tone: 'bad' })}${UI.kpi({ label: 'Partially paid', value: rows().filter(r => r.f.status === 'Partially Paid').length, icon: 'clock', tone: 'warn' })}${UI.kpi({ label: 'Pending (not yet due)', value: rows().filter(r => r.f.status === 'Pending').length, icon: 'calendar' })}${UI.kpi({ label: 'Total outstanding', value: C.inrK(C.sum(rows(), r => r.f.balance)), icon: 'wallet' })}</div>` + UI.card('Class-wise status', classWise(), { flush: true }) + '<div class="mt"></div>' + lv;
    }
  };
  UI.act.remindAll = () => { const od = mkRows().filter(r => r.f.status === 'Overdue'); UI.confirm('Send reminders to ' + od.length + ' parents?', 'A WhatsApp fee reminder will be sent to every parent with an overdue balance.', 'Send reminders', () => { let n = 0; od.forEach(r => { if (S.sendFeeReminder(r.s.id)) n++; }); UI.toast(n + ' fee reminders sent via WhatsApp', 'wa', 'Logged in notification history'); }); };

  /* ---------- Receipts ---------- */
  function payRows() { return S.db().payments.slice().sort((a, b) => b.ts.localeCompare(a.ts)).map(p => ({ p, s: S.student(p.sid) })); }
  Pages.receipts = {
    roles: ['accountant', 'principal'],
    render() {
      return UI.head({ title: 'Receipts', sub: 'Every payment recorded at the counter or through the parent portal.' }) + UI.listView({ id: 'receipts', title: 'Payment receipts', csv: 'receipts', print: true, source: payRows, pageSize: 14,
        filters: [{ k: 'q', type: 'search', label: 'Search', ph: 'Receipt no., student, admission no.' }, { k: 'from', type: 'date', label: 'From' }, { k: 'to', type: 'date', label: 'To' }, { k: 'm', type: 'select', label: 'Method', options: [['', 'All']].concat(['Cash', 'UPI', 'Card', 'Net Banking', 'Cheque', 'Online (Razorpay)']) }, { k: 'g', type: 'select', label: 'Class', options: GRADES }],
        filter: (r, f) => (!f.from || r.p.date >= f.from) && (!f.to || r.p.date <= f.to) && (!f.m || r.p.method === f.m) && (!f.g || r.s.grade == f.g) && (!f.q || (r.p.rcpt + r.s.name + r.s.adm).toLowerCase().includes(f.q.toLowerCase())),
        cols: [{ h: 'Receipt no.', f: r => `<b>${r.p.rcpt}</b>` }, { h: 'Date', f: r => C.fmtDate(r.p.date), csv: r => r.p.date }, { h: 'Student', f: r => UI.person(r.s.name, r.s.adm, r.s.colorIdx), csv: r => r.s.name }, { h: 'Class', f: r => S.className(r.s.classId) }, { h: 'For', f: r => esc(r.p.term) }, { h: 'Method', f: r => esc(r.p.method) }, { h: 'Received by', f: r => esc(r.p.by) }, { h: 'Amount', f: r => `<b>${C.inr(r.p.amount)}</b>`, cls: 'num', csv: r => r.p.amount }, { h: '', csv: false, f: r => UI.btn('View', 'receipt', { cls: 'xs', icon: 'receipt', data: { id: r.p.id } }) }],
        foot: rows => `<td colspan="7">Total (${rows.length} receipts)</td><td class="num">${C.inr(C.sum(rows, r => r.p.amount))}</td><td></td>` });
    }
  };
  Pages.receipt = { roles: ['accountant', 'principal'], render: ctx => Pages.receipts.render(ctx), mount(ctx) { if (ctx.arg && S.db().payments.some(p => p.id === ctx.arg)) setTimeout(() => G.Docs.open('receipt', ctx.arg), 50); } };

  /* ---------- Payroll ---------- */
  const payBadge = s => UI.status(s);
  H.salaryHistory = eid => { const rs = S.db().payroll.filter(r => r.empId === eid).sort((a, b) => b.month.localeCompare(a.month)); return UI.card('Salary records', UI.table([{ h: 'Month', f: r => C.monthLong(r.month) }, { h: 'Basic', f: r => C.inr(r.basic), cls: 'num' }, { h: 'Allowances', f: r => C.inr(r.allowances), cls: 'num' }, { h: 'Deductions', f: r => C.inr(r.deductions), cls: 'num' }, { h: 'Attendance deduction', f: r => r.attDed ? `<span class="down">${C.inr(r.attDed)}</span> <span class="muted small">(${r.absentDays}d)</span>` : '—', cls: 'num' }, { h: 'Net salary', f: r => `<b>${C.inr(r.net)}</b>`, cls: 'num' }, { h: 'Payment date', f: r => r.paidOn ? C.fmtDate(r.paidOn) : '—' }, { h: 'Status', f: r => payBadge(r.status) }, { h: '', f: r => UI.btn('Slip', 'slip', { cls: 'xs', icon: 'file', data: { id: r.id } }) }], rs), { flush: true }); };
  UI.act.slip = t => G.Docs.open('slip', t.dataset.id);
  function payrollPage(ctx) {
    const u = ctx.u, acc = u.role === 'accountant', st = ctx.st; const months = S.payrollMonths(); const mk = st.m || months[months.length - 1]; const cur = C.today().slice(0, 7);
    const rows = () => S.payrollFor(st.m || months[months.length - 1]).map(r => ({ r, e: S.emp(r.empId) }));
    const all = rows(); const tot = { net: C.sum(all, x => x.r.net), paid: C.sum(all.filter(x => x.r.status === 'Paid'), x => x.r.net), gross: C.sum(all, x => x.r.basic + x.r.allowances), ded: C.sum(all, x => x.r.deductions + x.r.attDed) };
    const trend = months.map(m => ({ m, t: C.sum(S.payrollFor(m).filter(r => S.emp(r.empId).role === 'teacher'), r => r.net), o: C.sum(S.payrollFor(m).filter(r => S.emp(r.empId).role !== 'teacher'), r => r.net) }));
    const lv = UI.listView({ id: 'payroll', title: 'Salary register – ' + C.monthLong(mk), csv: 'payroll_' + mk, print: true, source: rows, pageSize: 14, init: {},
      filters: [{ k: 'q', type: 'search', label: 'Search', ph: 'Name or employee ID' }, { k: 'd', type: 'select', label: 'Department', options: [['', 'All']].concat(Array.from(new Set(S.employees().map(e => e.dept)))) }, { k: 's', type: 'select', label: 'Status', options: [['', 'All'], 'Paid', 'Pending', 'Processing'] }],
      filter: (x, f) => (!f.d || x.e.dept === f.d) && (!f.s || x.r.status === f.s) && (!f.q || (x.e.name + x.e.empId).toLowerCase().includes(f.q.toLowerCase())),
      cols: [{ h: 'Employee', f: x => UI.person(x.e.name, x.e.empId, x.e.name.length, x.e.role === 'teacher' && !acc ? '#/teacher/' + x.e.id : null), csv: x => x.e.name }, { h: 'Department', f: x => esc(x.e.dept) }, { h: 'Designation', f: x => esc(x.e.designation) }, { h: 'Basic', f: x => C.inr(x.r.basic), cls: 'num', csv: x => x.r.basic }, { h: 'Allowances', f: x => C.inr(x.r.allowances), cls: 'num', csv: x => x.r.allowances }, { h: 'Deductions', f: x => C.inr(x.r.deductions), cls: 'num', csv: x => x.r.deductions }, { h: 'Att. deduction', f: x => x.r.attDed ? C.inr(x.r.attDed) : '—', cls: 'num', csv: x => x.r.attDed }, { h: 'Net salary', f: x => `<b>${C.inr(x.r.net)}</b>`, cls: 'num', csv: x => x.r.net }, { h: 'Paid on', f: x => x.r.paidOn ? C.fmtDate(x.r.paidOn) : '—', csv: x => x.r.paidOn || '' }, { h: 'Status', f: x => payBadge(x.r.status), csv: x => x.r.status }, { h: '', csv: false, f: x => `<div class="row">${UI.btn('Slip', 'slip', { cls: 'xs', data: { id: x.r.id } })}${acc ? (x.r.status !== 'Paid' ? `<button class="btn xs ok" data-act="payOne" data-id="${x.r.id}">Pay</button>` : '') + `<button class="btn xs" data-act="editSalary" data-id="${x.r.id}">${UI.icon('edit', 12)}</button>` : ''}</div>` }],
      foot: rs => `<td colspan="7">Total (${rs.length} employees)</td><td class="num">${C.inr(C.sum(rs, x => x.r.net))}</td><td colspan="3"></td>` });
    return UI.head({ title: 'Payroll', sub: acc ? 'Teacher and staff salaries – processing, payment and slips.' : 'Monthly salary expense overview (read-only).', actions: `<select class="input sm" data-on="payMonth">${UI.opts(months.map(m => [m, C.monthLong(m)]), mk)}</select>` + (acc ? (!months.includes(cur) ? UI.btn('Generate ' + C.monthLong(cur), 'genPayroll', { cls: 'primary', icon: 'plus' }) : '') + UI.btn('Pay all pending', 'payAll', { cls: 'primary', icon: 'check' }) : '') }) +
      `<div class="grid g4 mb">${UI.kpi({ label: 'Net payroll – ' + C.monthLabel(mk), value: C.inrK(tot.net), sub: all.length + ' employees', icon: 'receipt', tone: 'gold' })}${UI.kpi({ label: 'Paid', value: C.inrK(tot.paid), sub: all.filter(x => x.r.status === 'Paid').length + ' paid', icon: 'check', tone: 'ok' })}${UI.kpi({ label: 'Pending / processing', value: C.inrK(tot.net - tot.paid), sub: all.filter(x => x.r.status !== 'Paid').length + ' to pay', icon: 'clock', tone: 'warn' })}${UI.kpi({ label: 'Total deductions', value: C.inrK(tot.ded), sub: 'PF, tax, attendance', icon: 'alert' })}</div>
      <div class="grid g-12 mb">${UI.card('Monthly salary expense', UI.chart.bars({ labels: trend.map(x => C.monthLabel(x.m)), series: [{ name: 'Teaching staff', data: trend.map(x => x.t), color: UI.PAL[0] }, { name: 'Non-teaching', data: trend.map(x => x.o), color: UI.PAL[1] }], stacked: true, fmt: C.inrK, height: 220 }))}${UI.card('Status – ' + C.monthLong(mk), UI.chart.donut({ items: ['Paid', 'Processing', 'Pending'].map((k, i) => ({ label: k, value: all.filter(x => x.r.status === k).length, color: ['#1b7f57', '#25609f', '#d99a2b'][i] })), center: all.length, centerLabel: 'EMPLOYEES' }))}</div>` + lv;
  }
  UI.on.payMonth = t => { App.st('payroll').m = t.value; App.refresh(); };
  UI.act.genPayroll = () => { const n = S.ensurePayroll(C.today().slice(0, 7)); UI.toast('Payroll generated for ' + n + ' employees', 'ok'); App.refresh(); };
  UI.act.payOne = t => { S.setSalaryStatus(t.dataset.id, 'Paid'); UI.toast('Salary marked as paid', 'ok'); App.refresh(); };
  UI.act.payAll = () => { const st = App.st('payroll'); const ms = S.payrollMonths(); const mk = st.m || ms[ms.length - 1]; const p = S.payrollFor(mk).filter(r => r.status !== 'Paid'); if (!p.length) { UI.toast('Nothing pending for ' + C.monthLong(mk)); return; } UI.confirm('Pay ' + p.length + ' salaries?', 'Total ' + C.inr(C.sum(p, r => r.net)) + ' for ' + C.monthLong(mk) + ' will be marked as paid by bank transfer.', 'Mark all paid', () => { p.forEach(r => S.setSalaryStatus(r.id, 'Paid')); UI.toast(p.length + ' salaries paid', 'ok'); App.refresh(); }); };
  UI.act.editSalary = t => {
    const r = S.db().payroll.find(x => x.id === t.dataset.id), e = S.emp(r.empId);
    UI.modal({ title: 'Edit salary – ' + esc(e.name) + ' · ' + C.monthLabel(r.month), body: `<form id="salForm" class="form-grid">${[['hra', 'House rent allowance'], ['da', 'Dearness allowance'], ['transport', 'Transport allowance'], ['pf', 'Provident fund'], ['pt', 'Professional tax'], ['tds', 'Income tax (TDS)'], ['attDed', 'Attendance deduction']].map(([k, l]) => UI.field(l + ' (₹)', `<input class="input num" type="number" min="0" name="${k}" value="${r[k]}">`)).join('')}${UI.field('Basic salary (₹)', `<input class="input num" value="${r.basic}" disabled>`)}</form><div class="hint mt-s">All changes are written to the audit log with previous and new values.</div>`, footer: `<button class="btn" data-act="closeModal">Cancel</button><button class="btn primary" data-act="saveSalary" data-id="${r.id}">Save</button>` });
  };
  UI.act.saveSalary = t => { const d = UI.formData(document.getElementById('salForm')); const p = {}; Object.keys(d).forEach(k => p[k] = Math.max(0, Math.round(+d[k] || 0))); S.updateSalary(t.dataset.id, p); UI.closeModal(); UI.toast('Salary record updated', 'ok'); App.refresh(); };
  Pages.payroll = { roles: ['accountant', 'principal'], render: payrollPage };
  Pages.salary = { roles: ['teacher'], render(ctx) { const e = S.emp(ctx.u.empId), rs = S.db().payroll.filter(r => r.empId === e.id).sort((a, b) => b.month.localeCompare(a.month)), r = rs[0]; return UI.head({ title: 'My salary', sub: e.name + ' · ' + e.empId + ' · ' + e.designation }) + `<div class="alert info mb">${UI.icon('lock', 16)}<div>Salary details are visible only to you, the Accountant and the Principal.</div></div><div class="grid g4 mb">${UI.kpi({ label: 'Latest net salary – ' + C.monthLabel(r.month), value: C.inr(r.net), icon: 'wallet', tone: 'gold', sub: r.status })}${UI.kpi({ label: 'Basic', value: C.inr(r.basic), icon: 'receipt' })}${UI.kpi({ label: 'Allowances', value: C.inr(r.allowances), icon: 'plus', tone: 'ok' })}${UI.kpi({ label: 'Deductions', value: C.inr(r.deductions + r.attDed), icon: 'alert', tone: 'bad', sub: r.attDed ? 'incl. attendance ' + C.inr(r.attDed) : 'PF, tax' })}</div>` + H.salaryHistory(e.id); } };

  /* ---------- Expenses ---------- */
  Pages.expenses = {
    roles: ['accountant'],
    render() {
      const db = S.db(), cats = Array.from(new Set(db.expenses.map(e => e.category))); const tot = {}; db.expenses.forEach(e => tot[e.category] = (tot[e.category] || 0) + e.amount);
      return UI.head({ title: 'Expenses', sub: 'Operational and administrative expenses.', actions: UI.btn('Record expense', 'addExpense', { cls: 'primary', icon: 'plus' }) }) + `<div class="grid g-21 mb">${UI.card('Expenses by category (year to date)', UI.chart.hbars({ items: Object.entries(tot).sort((a, b) => b[1] - a[1]).map(([k, v]) => ({ label: k, value: v })), fmt: C.inrK }))}${UI.card('Monthly expenses', UI.chart.bars({ labels: H.monthsAY().map(C.monthLabel), series: [{ name: 'Expenses', data: H.finMonthly().other, color: UI.PAL[1] }], fmt: C.inrK, height: 210 }))}</div>` + UI.listView({ id: 'expenses', title: 'Expense register', csv: 'expenses', print: true, pageSize: 12, source: () => db.expenses.slice().sort((a, b) => b.date.localeCompare(a.date)), filters: [{ k: 'q', type: 'search', label: 'Search', ph: 'Description' }, { k: 'c', type: 'select', label: 'Category', options: [['', 'All']].concat(cats) }, { k: 'from', type: 'date', label: 'From' }, { k: 'to', type: 'date', label: 'To' }], filter: (e, f) => (!f.c || e.category === f.c) && (!f.from || e.date >= f.from) && (!f.to || e.date <= f.to) && (!f.q || e.desc.toLowerCase().includes(f.q.toLowerCase())), cols: [{ h: 'Voucher', f: e => e.id }, { h: 'Date', f: e => C.fmtDate(e.date), csv: e => e.date }, { h: 'Category', f: e => esc(e.category) }, { h: 'Description', f: e => esc(e.desc) }, { h: 'Method', f: e => esc(e.method) }, { h: 'Recorded by', f: e => esc(e.by) }, { h: 'Amount', f: e => `<b>${C.inr(e.amount)}</b>`, cls: 'num', csv: e => e.amount }], foot: rs => `<td colspan="6">Total</td><td class="num">${C.inr(C.sum(rs, e => e.amount))}</td>` });
    }
  };
  UI.act.addExpense = () => UI.modal({ title: 'Record expense', body: `<form id="expForm" class="form-grid">${UI.field('Category', UI.select('category', Array.from(new Set(S.db().expenses.map(e => e.category)))))}${UI.field('Date', UI.input('date', C.today(), `type="date" max="${C.today()}"`))}${UI.field('Description', UI.input('desc', '', 'required'), { cls: 'full' })}${UI.field('Amount (₹)', UI.input('amount', '', 'type="number" min="1" required'))}${UI.field('Payment method', UI.select('method', ['Bank Transfer', 'UPI', 'Cheque', 'Cash']))}</form>`, footer: '<button class="btn" data-act="closeModal">Cancel</button><button class="btn primary" data-act="saveExpense">Save expense</button>' });
  UI.act.saveExpense = () => { const f = document.getElementById('expForm'); if (!f.reportValidity()) return; const d = UI.formData(f); S.addExpense({ category: d.category, date: d.date, desc: d.desc, amount: +d.amount, method: d.method }); UI.closeModal(); UI.toast('Expense recorded', 'ok'); App.refresh(); };

  /* ---------- Finance overview (Principal) ---------- */
  Pages.finance = {
    roles: ['principal'],
    render() {
      const db = S.db(), fin = H.finMonthly(), ft = S.feeTotals(); const inc = C.sum(fin.income), sal = C.sum(fin.salary), oth = C.sum(fin.other); const net = inc - sal - oth; const cls = S.classes().map(c => ({ c, f: S.classFee(c.id) }));
      return UI.head({ title: 'Finance', sub: 'Income, payroll and operating expenses for ' + db.ay + '.', actions: UI.link('Financial reports', '#/reports', { icon: 'chart' }) }) + `<div class="grid g4">${UI.kpi({ label: 'Fee income (YTD)', value: C.inrK(inc), icon: 'rupee', tone: 'ok', sub: C.pct(ft.collected, ft.expected, 0) + '% of expected' })}${UI.kpi({ label: 'Salary expense (YTD)', value: C.inrK(sal), icon: 'receipt', tone: 'gold' })}${UI.kpi({ label: 'Operational expenses (YTD)', value: C.inrK(oth), icon: 'trend', tone: 'warn' })}${UI.kpi({ label: net >= 0 ? 'Net surplus (cash basis)' : 'Net deficit (cash basis)', value: C.inrK(Math.abs(net)), icon: 'wallet', tone: net >= 0 ? 'ok' : 'bad', sub: 'Income − salaries − expenses' })}</div>
      <div class="grid g-21 mt">${UI.card('Income vs expenses', UI.chart.bars({ labels: fin.ms.map(C.monthLabel), series: [{ name: 'Fee income', data: fin.income, color: UI.PAL[2] }, { name: 'Salaries', data: fin.salary, color: UI.PAL[0] }, { name: 'Operational', data: fin.other, color: UI.PAL[1] }], fmt: C.inrK, height: 250 }))}${UI.card('Collection by class', UI.chart.hbars({ items: cls.map(x => ({ label: x.c.name, value: C.pct(x.f.received, x.f.expected, 0) })).sort((a, b) => a.value - b.value).slice(0, 8), max: 100, fmt: v => v + '%' }), { sub: 'Lowest 8 classes' })}</div>
      <div class="mt">${UI.card('Monthly financial summary', UI.table([{ h: 'Month', f: r => C.monthLong(r.m) }, { h: 'Fee income', f: r => C.inr(r.i), cls: 'num' }, { h: 'Salaries', f: r => C.inr(r.s), cls: 'num' }, { h: 'Other expenses', f: r => C.inr(r.o), cls: 'num' }, { h: 'Net', f: r => `<b class="${r.i - r.s - r.o >= 0 ? 'up' : 'down'}">${C.inr(r.i - r.s - r.o)}</b>`, cls: 'num' }], fin.ms.map((m, i) => ({ m, i: fin.income[i], s: fin.salary[i], o: fin.other[i] }))), { flush: true })}</div>
      <div class="mt">${UI.card('Recent expenses', UI.table([{ h: 'Date', f: e => C.fmtDate(e.date) }, { h: 'Category', f: e => esc(e.category) }, { h: 'Description', f: e => esc(e.desc) }, { h: 'Amount', f: e => C.inr(e.amount), cls: 'num' }], db.expenses.slice().sort((a, b) => b.date.localeCompare(a.date)).slice(0, 8)), { flush: true })}</div>`;
    }
  };

  /* ---------- Reports engine ---------- */
  const db = () => S.db();
  const sOk = (s, f) => (!f.g || s.grade == f.g) && (!f.sec || s.section === f.sec);
  const wkStart = d => C.addDays(d, -C.dow(d));
  const examOpts = () => db().exams.filter(x => S.examStatus(x) !== 'Upcoming').map(x => [x.id, x.name]);
  const defEx = () => (examOpts().slice(-1)[0] || [''])[0];
  const REP = {
    fee_collection: { t: 'Fee collection report', d: 'Daily, weekly, monthly or academic-year collections with method split.', fl: ['from', 'to', 'group', 'g', 'sec', 'm'], def: () => ({ from: db().ayStart, to: C.today(), group: 'month' }), run(f) {
      const pays = db().payments.filter(p => p.date >= f.from && p.date <= f.to && (!f.m || p.method === f.m) && sOk(S.student(p.sid), f)); const gm = {}; const ms = ['Cash', 'UPI', 'Card', 'Net Banking', 'Cheque', 'Online (Razorpay)'];
      pays.forEach(p => { const k = f.group === 'day' ? p.date : f.group === 'week' ? wkStart(p.date) : f.group === 'month' ? p.date.slice(0, 7) : 'AY'; (gm[k] = gm[k] || { n: 0, a: 0, m: {} }); gm[k].n++; gm[k].a += p.amount; gm[k].m[p.method] = (gm[k].m[p.method] || 0) + p.amount; });
      const keys = Object.keys(gm).sort(); const lab = k => f.group === 'day' ? C.fmtDate(k) : f.group === 'week' ? 'Week of ' + C.fmtDate(k) : f.group === 'month' ? C.monthLong(k) : 'Academic year ' + db().ay;
      return { cols: ['Period', 'Receipts'].concat(ms, ['Total']), rows: keys.map(k => [lab(k), gm[k].n].concat(ms.map(m => gm[k].m[m] || 0), [gm[k].a])), money: [2, 3, 4, 5, 6, 7, 8], total: true, chart: keys.length > 1 ? UI.chart.bars({ labels: keys.map(k => f.group === 'month' ? C.monthLabel(k) : C.pd(k.length === 7 ? k + '-01' : k).getDate() + '/' + (C.pd(k.length === 7 ? k + '-01' : k).getMonth() + 1)), series: [{ name: 'Collected', data: keys.map(k => gm[k].a), color: UI.PAL[2] }], fmt: C.inrK, height: 220 }) : '' };
    } },
    fee_class: { t: 'Class-wise collection', d: 'Expected vs received by class and section.', fl: ['g', 'sec'], def: () => ({}), run(f) { const cs = S.classes().filter(c => (!f.g || c.grade == f.g) && (!f.sec || c.section === f.sec)).map(c => ({ c, f: S.classFee(c.id) })); return { cols: ['Class', 'Students', 'Paid', 'Partially paid', 'Pending', 'Overdue', 'Expected', 'Received', 'Pending amount', 'Collected %'], rows: cs.map(x => [x.c.name, x.f.total, x.f.Paid, x.f['Partially Paid'], x.f.Pending, x.f.Overdue, x.f.expected, x.f.received, x.f.pending, C.pct(x.f.received, x.f.expected, 0) + '%']), money: [6, 7, 8], total: [1, 2, 3, 4, 5, 6, 7, 8] }; } },
    fee_student: { t: 'Student-wise fee report', d: 'Every student’s fee, payments and balance.', fl: ['q', 'g', 'sec', 'fs'], def: () => ({}), run(f) { const rs = mkRows().filter(r => feeFilter(r, f)); return { cols: ['Student', 'Admission no.', 'Class', 'Parent', 'Phone', 'Total fee', 'Paid', 'Balance', 'Status', 'Last payment'], rows: rs.map(r => [r.s.name, r.s.adm, S.className(r.s.classId), r.p.name, r.p.phone, r.f.total, r.f.paid, r.f.balance, r.f.status, r.f.lastPay ? C.fmtDate(r.f.lastPay.date) : '—']), money: [5, 6, 7], total: [5, 6, 7] }; } },
    fee_pending: { t: 'Pending payments', d: 'All students with an outstanding balance.', fl: ['g', 'sec', 'fs'], def: () => ({}), run(f) { const rs = mkRows().filter(r => r.f.balance > 0 && feeFilter(r, f)); return { cols: ['Student', 'Class', 'Parent', 'Phone', 'Balance', 'Next due', 'Status'], rows: rs.map(r => [r.s.name, S.className(r.s.classId), r.p.name, r.p.phone, r.f.balance, r.f.next ? C.fmtDate(r.f.next.due) : '—', r.f.status]), money: [4], total: [4] }; } },
    fee_overdue: { t: 'Overdue payments', d: 'Instalments past their due date.', fl: ['g', 'sec'], def: () => ({}), run(f) { const rs = mkRows().filter(r => r.f.status === 'Overdue' && sOk(r.s, f)).sort((a, b) => b.f.overdueDays - a.f.overdueDays); return { cols: ['Student', 'Class', 'Parent', 'Phone', 'Overdue amount', 'Days overdue', 'Total balance'], rows: rs.map(r => [r.s.name, S.className(r.s.classId), r.p.name, r.p.phone, r.f.overdueAmt, r.f.overdueDays, r.f.balance]), money: [4, 6], total: [4, 6] }; } },
    salary: { t: 'Salary report', d: 'Monthly salary register for all employees.', fl: ['month'], def: () => ({ month: S.payrollMonths().slice(-1)[0] }), run(f) { const rs = S.payrollFor(f.month).map(r => ({ r, e: S.emp(r.empId) })); return { cols: ['Employee ID', 'Name', 'Department', 'Basic', 'Allowances', 'Deductions', 'Attendance ded.', 'Net salary', 'Status', 'Paid on'], rows: rs.map(x => [x.e.empId, x.e.name, x.e.dept, x.r.basic, x.r.allowances, x.r.deductions, x.r.attDed, x.r.net, x.r.status, x.r.paidOn ? C.fmtDate(x.r.paidOn) : '—']), money: [3, 4, 5, 6, 7], total: [3, 4, 5, 6, 7] }; } },
    expense: { t: 'Expense report', d: 'School expenses by category and month.', fl: ['from', 'to'], def: () => ({ from: db().ayStart, to: C.today() }), run(f) { const g = {}; db().expenses.filter(e => e.date >= f.from && e.date <= f.to).forEach(e => g[e.category] = (g[e.category] || 0) + e.amount); const ks = Object.keys(g).sort((a, b) => g[b] - g[a]); return { cols: ['Category', 'Amount'], rows: ks.map(k => [k, g[k]]), money: [1], total: [1], chart: UI.chart.hbars({ items: ks.map(k => ({ label: k, value: g[k] })), fmt: C.inrK }) }; } },
    att_student: { t: 'Student attendance', d: 'Attendance percentage by student.', fl: ['g', 'sec', 'q'], def: () => ({}), run(f) { const rs = db().students.filter(s => sOk(s, f) && (!f.q || s.name.toLowerCase().includes(f.q.toLowerCase()))).map(s => ({ s, a: S.studentAtt(s.id) })).sort((a, b) => a.a.pct - b.a.pct); return { cols: ['Student', 'Class', 'Present', 'Absent', 'Late', 'Leave', 'Days', 'Attendance %'], rows: rs.map(x => [x.s.name, S.className(x.s.classId), x.a.P, x.a.A, x.a.L, x.a.V, x.a.total, x.a.pct + '%']) }; } },
    att_class: { t: 'Class attendance', d: 'Year-to-date attendance by class.', fl: [], def: () => ({}), run() { const cs = S.classes().map(c => ({ c, p: S.classAttPct(c.id) })); return { cols: ['Class', 'Class teacher', 'Students', 'Attendance %'], rows: cs.map(x => [x.c.name, S.emp(x.c.classTeacherId).name, S.studentsOf(x.c.id).length, x.p + '%']), chart: UI.chart.bars({ labels: cs.map(x => S.clsShort(x.c.id)), series: [{ name: 'Attendance %', data: cs.map(x => x.p), color: UI.PAL[0] }], ymin: 80, ymax: 100, fmt: v => v + '%', height: 220 }) }; } },
    att_teacher: { t: 'Teacher attendance', d: 'Presence, absence and leave of teaching staff.', fl: [], def: () => ({}), run() { const rs = S.teachers().map(t => { let P = 0, A = 0, V = 0; Object.values(db().tAtt).forEach(m => { if (m[t.id] === 'P') P++; else if (m[t.id] === 'A') A++; else if (m[t.id] === 'V') V++; }); return [t.name, t.dept, P, A, V, S.teacherAttPct(t.id) + '%']; }); return { cols: ['Teacher', 'Department', 'Present', 'Absent', 'Leave', 'Attendance %'], rows: rs }; } },
    perf_student: { t: 'Student performance', d: 'Result of every student for an examination.', fl: ['exam', 'g', 'sec', 'q'], def: () => ({ exam: defEx() }), run(f) { const x = S.exam(f.exam); if (!x) return { cols: [], rows: [] }; const rs = db().students.filter(s => sOk(s, f) && (!f.q || s.name.toLowerCase().includes(f.q.toLowerCase()))).map(s => ({ s, r: S.examResult(s.id, x.id) })).filter(a => a.r.done).sort((a, b) => b.r.pct - a.r.pct); return { cols: ['Rank', 'Student', 'Class', 'Total', 'Max', 'Percentage', 'Grade', 'Result'], rows: rs.map((a, i) => [i + 1, a.s.name, S.className(a.s.classId), a.r.total, a.r.max, a.r.pct + '%', a.r.grade, a.r.complete ? a.r.result : 'Partial']) }; } },
    perf_class: { t: 'Class performance', d: 'Average and pass percentage by class.', fl: ['exam'], def: () => ({ exam: defEx() }), run(f) { const rs = S.classes().map(c => ({ c, r: S.classExam(c.id, f.exam) })); return { cols: ['Class', 'Class teacher', 'Students evaluated', 'Average %', 'Pass %'], rows: rs.map(x => [x.c.name, S.emp(x.c.classTeacherId).name, x.r.n, x.r.avg.toFixed(1) + '%', x.r.n ? C.pct(x.r.pass, x.r.n, 0) + '%' : '—']), chart: UI.chart.bars({ labels: rs.map(x => S.clsShort(x.c.id)), series: [{ name: 'Average %', data: rs.map(x => +x.r.avg.toFixed(1)) }], fmt: v => v + '%', ymax: 100, height: 220 }) }; } },
    perf_exam: { t: 'Examination performance', d: 'Whole-school comparison of examinations.', fl: [], def: () => ({}), run() { const rs = db().exams.filter(x => S.examStatus(x) === 'Completed').map(x => { const all = S.classes().map(c => S.classExam(c.id, x.id)); const n = C.sum(all, a => a.n), p = C.sum(all, a => a.pass); return [x.name, C.fmtDate(x.schedule[0].date), n, C.avg(all.filter(a => a.res.length), a => a.avg).toFixed(1) + '%', n ? C.pct(p, n, 0) + '%' : '—']; }); return { cols: ['Examination', 'Start date', 'Students', 'Average %', 'Pass %'], rows: rs }; } },
    ops: { t: 'Operations & cleaning', d: 'Task completion by category.', fl: ['from', 'to'], def: () => ({ from: C.addDays(C.today(), -7), to: C.today() }), run(f) { const g = {}; db().tasks.filter(t => t.date >= f.from && t.date <= f.to).forEach(t => { const k = t.category; g[k] = g[k] || { n: 0, d: 0, a: 0, v: 0 }; g[k].n++; if (t.status === 'Completed') g[k].d++; if (t.status === 'Requires Attention') g[k].a++; if (t.verified) g[k].v++; }); return { cols: ['Category', 'Tasks', 'Completed', 'Requires attention', 'Verified', 'Completion %'], rows: Object.entries(g).map(([k, v]) => [k, v.n, v.d, v.a, v.v, C.pct(v.d, v.n, 0) + '%']) }; } },
    maint: { t: 'Maintenance requests', d: 'Reported issues with status and priority.', fl: [], def: () => ({}), run() { return { cols: ['Reported', 'Location', 'Issue', 'Priority', 'Status', 'Reported by', 'Assigned to'], rows: db().maint.slice().sort((a, b) => b.ts.localeCompare(a.ts)).map(m => [C.fmtDate(m.date), m.location, m.issue, m.priority, m.status, m.reportedBy, m.assignedTo ? S.emp(m.assignedTo).name : '—']) }; } },
    staff: { t: 'Staff statistics', d: 'Headcount, salary bill and attendance by department.', fl: [], def: () => ({}), run() { const g = {}; db().employees.forEach(e => { g[e.dept] = g[e.dept] || { n: 0, b: 0 }; g[e.dept].n++; g[e.dept].b += e.basic; }); return { cols: ['Department', 'Employees', 'Total basic salary', 'Average basic'], rows: Object.entries(g).map(([k, v]) => [k, v.n, v.b, Math.round(v.b / v.n)]), money: [2, 3], total: [1, 2] }; } },
    class_results: { t: 'Class results', d: 'Subject-wise marks of every student in a class.', fl: ['exam', 'cls'], def: () => ({ exam: defEx(), cls: 'C5A' }), run(f) { const x = S.exam(f.exam); if (!x) return { cols: [], rows: [] }; const rs = S.studentsOf(f.cls).map(s => ({ s, r: S.examResult(s.id, x.id) })); return { cols: ['Roll', 'Student'].concat(x.schedule.map(s => s.subject), ['Total', '%', 'Grade', 'Result']), rows: rs.map(a => [a.s.roll, a.s.name].concat(a.r.rows.map(w => w.pending ? '—' : w.obt), [a.r.total, a.r.pct + '%', a.r.grade, a.r.complete ? a.r.result : 'Partial'])) }; } },
    subject_perf: { t: 'Subject performance', d: 'Average % by subject and class.', fl: ['exam'], def: () => ({ exam: defEx() }), run(f) { const x = S.exam(f.exam); if (!x) return { cols: [], rows: [] }; return { cols: ['Class'].concat(x.schedule.map(s => s.subject)), rows: S.classes().map(c => [c.name].concat(x.schedule.map(s => { const v = S.subjectAvg(x.id, c.id, s.subject); return v == null ? '—' : v.toFixed(1) + '%'; }))) }; } },
    workload: { t: 'Teacher workload', d: 'Periods per week, classes and subjects.', fl: [], def: () => ({}), run() { return { cols: ['Teacher', 'Department', 'Subjects', 'Classes', 'Periods / week', 'Free periods', 'Class teacher'], rows: S.teachers().map(t => [t.name, t.dept, t.subjects.join(', '), Object.keys(S.teacherClasses(t.id)).length, S.teacherLoad(t.id), 42 - S.teacherLoad(t.id), S.classTeacherClass(t.id) ? S.classTeacherClass(t.id).name : '—']) }; } },
    exam_stats: { t: 'Examination statistics', d: 'Highest, lowest and pass % by subject for an exam.', fl: ['exam'], def: () => ({ exam: defEx() }), run(f) { const x = S.exam(f.exam); if (!x) return { cols: [], rows: [] }; return { cols: ['Subject', 'Sheets published', 'Students', 'Average', 'Highest', 'Lowest', 'Pass %'], rows: x.schedule.map(sc => { let vals = [], sheets = 0; S.classes().forEach(c => { const r = S.marksRec(x.id, c.id, sc.subject); if (r && r.status === 'published') { sheets++; Object.values(r.entries).forEach(e => e.obt != null && vals.push(e.obt)); } }); return [sc.subject, sheets, vals.length, vals.length ? C.avg(vals).toFixed(1) + '/' + x.max : '—', vals.length ? Math.max(...vals) : '—', vals.length ? Math.min(...vals) : '—', vals.length ? C.pct(vals.filter(v => v >= x.passMarks).length, vals.length, 0) + '%' : '—']; }) }; } }
  };
  const REPS = { principal: ['fee_collection', 'fee_class', 'fee_pending', 'salary', 'att_student', 'att_class', 'att_teacher', 'perf_student', 'perf_class', 'perf_exam', 'ops', 'maint', 'staff'], accountant: ['fee_collection', 'fee_class', 'fee_student', 'fee_pending', 'fee_overdue', 'salary', 'expense'], dean: ['perf_class', 'class_results', 'subject_perf', 'att_class', 'att_student', 'workload', 'exam_stats'] };
  const FL = {
    from: st => UI.field('From', `<input type="date" class="input sm" data-on="repF" data-k="from" value="${st.from || ''}">`), to: st => UI.field('To', `<input type="date" class="input sm" data-on="repF" data-k="to" value="${st.to || ''}">`),
    group: st => UI.field('Group by', `<select class="input sm" data-on="repF" data-k="group">${UI.opts([['day', 'Day (daily)'], ['week', 'Week'], ['month', 'Month'], ['ay', 'Academic year']], st.group)}</select>`),
    g: st => UI.field('Class', `<select class="input sm" data-on="repF" data-k="g">${UI.opts(GRADES, st.g || '')}</select>`), sec: st => UI.field('Section', `<select class="input sm" data-on="repF" data-k="sec">${UI.opts([['', 'All'], 'A', 'B'], st.sec || '')}</select>`),
    m: st => UI.field('Payment method', `<select class="input sm" data-on="repF" data-k="m">${UI.opts([['', 'All']].concat(['Cash', 'UPI', 'Card', 'Net Banking', 'Cheque', 'Online (Razorpay)']), st.m || '')}</select>`), fs: st => UI.field('Payment status', `<select class="input sm" data-on="repF" data-k="fs">${UI.opts([['', 'All'], 'Paid', 'Partially Paid', 'Pending', 'Overdue'], st.fs || '')}</select>`),
    q: st => UI.field('Search', `<input class="input sm" data-on="repF" data-k="q" value="${esc(st.q || '')}" placeholder="Name, adm. no., parent…">`), month: st => UI.field('Month', `<select class="input sm" data-on="repF" data-k="month">${UI.opts(S.payrollMonths().map(m => [m, C.monthLong(m)]), st.month)}</select>`),
    exam: st => UI.field('Examination', `<select class="input sm" data-on="repF" data-k="exam">${UI.opts(examOpts(), st.exam)}</select>`), cls: st => UI.field('Class', `<select class="input sm" data-on="repF" data-k="cls">${UI.opts(S.classes().map(c => [c.id, c.name]), st.cls)}</select>`)
  };
  function repOut(st) {
    const R = REP[st.rid]; const f = st.f; const out = R.run(f); const fm = v => typeof v === 'number' ? C.num(v) : v; const money = out.money || []; const rows = out.rows;
    const totals = out.total ? out.cols.map((c, i) => (out.total === true ? money : out.total).includes(i) ? C.sum(rows, r => +r[i] || 0) : null) : null;
    return (out.chart ? `<div class="card-b" style="border-bottom:1px solid var(--line-2)">${out.chart}</div>` : '') + `<div class="tbl-wrap"><table class="tbl"><thead><tr>${out.cols.map((c, i) => `<th class="${typeof (rows[0] || [])[i] === 'number' ? 'num' : ''}">${esc(c)}</th>`).join('')}</tr></thead><tbody>${rows.length ? rows.map(r => `<tr>${r.map((v, i) => `<td class="${typeof v === 'number' ? 'num' : ''}">${money.includes(i) ? C.inr(v) : esc(fm(v))}</td>`).join('')}</tr>`).join('') : `<tr><td colspan="${out.cols.length || 1}">${UI.empty('No data for the selected filters')}</td></tr>`}</tbody>${totals && rows.length ? `<tfoot><tr>${totals.map((t, i) => `<td class="${t != null ? 'num' : ''}">${i === 0 ? 'Total' : t == null ? '' : money.includes(i) ? C.inr(t) : C.num(t)}</td>`).join('')}</tr></tfoot>` : ''}</table></div><div class="pager"><span>${rows.length} row${rows.length === 1 ? '' : 's'}</span><span>Generated ${C.fmtStamp(C.nowIso())}</span></div>`;
  }
  function repData(st) { const R = REP[st.rid]; const out = R.run(st.f); const money = out.money || []; return { cols: out.cols, rows: out.rows.map(r => r.map((v, i) => money.includes(i) ? v : v)) }; }
  Pages.reports = {
    roles: ['principal', 'dean', 'accountant'],
    render(ctx) {
      const u = ctx.u, st = ctx.st; const list = REPS[u.role]; if (!st.rid || !list.includes(st.rid)) { st.rid = list[0]; st.f = REP[st.rid].def(); } const R = REP[st.rid];
      return UI.head({ title: u.role === 'accountant' ? 'Financial reports' : 'Reports', sub: 'Filter, review and export operational reports. Exports respect your role permissions.' }) + `<div class="grid" style="grid-template-columns:270px 1fr;gap:16px;align-items:start" id="repGrid"><div class="card"><div class="card-b flush">${list.map(id => `<button class="list-i" style="width:100%;text-align:left;background:${id === st.rid ? 'var(--navy-50)' : '#fff'};border:0;border-bottom:1px solid var(--line-2);cursor:pointer;border-left:3px solid ${id === st.rid ? 'var(--gold)' : 'transparent'}" data-act="repPick" data-id="${id}"><div><b style="font-size:13px">${REP[id].t}</b><div class="muted tiny">${REP[id].d}</div></div></button>`).join('')}</div></div>
      <div class="card"><div class="card-h"><div><h3>${R.t}</h3><div class="sub">${R.d}</div></div><div class="row">${UI.btn('Export CSV', 'repCsv', { cls: 'sm', icon: 'download' })}${UI.btn('Print / PDF', 'repPrint', { cls: 'sm', icon: 'printer' })}</div></div>${R.fl.length ? `<div class="filters">${R.fl.map(k => FL[k](st.f)).join('')}</div>` : ''}<div id="repOut">${repOut(st)}</div></div></div><style>@media(max-width:960px){#repGrid{grid-template-columns:1fr!important}}</style>`;
    }
  };
  UI.act.repPick = t => { const st = App.st('reports'); st.rid = t.dataset.id; st.f = REP[st.rid].def(); App.refresh(); };
  UI.on.repF = t => { const st = App.st('reports'); st.f[t.dataset.k] = t.value; const el = document.getElementById('repOut'); if (el) el.innerHTML = repOut(st); };
  UI.act.repCsv = () => { const st = App.st('reports'); const d = repData(st); UI.csv(REP[st.rid].t, d.cols, d.rows); };
  UI.act.repPrint = () => { const st = App.st('reports'); const d = repData(st); UI.docPreview(REP[st.rid].t, UI.docTable(REP[st.rid].t, Object.entries(st.f).filter(([k, v]) => v).map(([k, v]) => k + ': ' + v).join(' · ') || 'All records', d.cols, d.rows), REP[st.rid].t); };
})(window);
