/* site.js — public website of Rainbow's English Medium High School (hash-routed).
   Announcements and events come from the same data store the portal uses. */
(function () {
  'use strict';
  const C = window.C, S = window.S, esc = C.esc, SCH = C.SCHOOL;
  const app = document.getElementById('app');

  /* ---------- icons ---------- */
  const P = { book: '<path d="M4 5a2 2 0 012-2h13v16H6a2 2 0 00-2 2z"/><path d="M4 19V5"/>', flask: '<path d="M9 3h6M10 3v6L4 20h16l-6-11V3"/>', cap: '<path d="M2 9l10-5 10 5-10 5z"/><path d="M6 11.5V16c0 1.5 3 3 6 3s6-1.5 6-3v-4.5"/>', users: '<circle cx="9" cy="8" r="3.5"/><path d="M2.5 20c0-3.6 2.9-6 6.5-6s6.5 2.4 6.5 6"/><path d="M16 4.5a3.5 3.5 0 010 7"/><path d="M18 14.5c2 .8 3.5 2.7 3.5 5.5"/>', trophy: '<path d="M7 4h10v5a5 5 0 01-10 0zM7 6H4v1a3 3 0 003 3M17 6h3v1a3 3 0 01-3 3M12 14v4M8 21h8"/>', bus: '<rect x="4" y="4" width="16" height="13" rx="2"/><path d="M4 11h16M7 20v-3M17 20v-3"/>', shield: '<path d="M12 3l8 3v6c0 5-3.5 8-8 9-4.5-1-8-4-8-9V6z"/><path d="M9 12l2 2 4-4"/>', calendar: '<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M3 10h18M8 3v4M16 3v4"/>', phone: '<path d="M5 3h4l2 5-2.5 1.5a11 11 0 006 6L16 13l5 2v4a2 2 0 01-2 2A16 16 0 013 5a2 2 0 012-2z"/>', mail: '<rect x="3" y="5" width="18" height="14" rx="2"/><path d="M3 7l9 6 9-6"/>', pin: '<path d="M12 21s7-6 7-12a7 7 0 10-14 0c0 6 7 12 7 12z"/><circle cx="12" cy="9" r="2.5"/>', clock: '<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>', building: '<path d="M4 21V5l8-2v18M12 8h8v13M4 21h16M8 9h.01M8 13h.01M8 17h.01M16 12h.01M16 16h.01"/>', award: '<circle cx="12" cy="9" r="6"/><path d="M8.5 14L7 21l5-3 5 3-1.5-7"/>', monitor: '<rect x="3" y="4" width="18" height="12" rx="2"/><path d="M8 20h8M12 16v4"/>', heart: '<path d="M12 20s-8-5-8-11a4.5 4.5 0 018-2.5A4.5 4.5 0 0120 9c0 6-8 11-8 11z"/>', palette: '<path d="M12 3a9 9 0 100 18c1.4 0 2-1 1.5-2-.6-1.2.2-2.5 1.6-2.5H18a3 3 0 003-3A9 9 0 0012 3z"/><circle cx="7.5" cy="11" r="1"/><circle cx="10" cy="7" r="1"/><circle cx="15" cy="7.5" r="1"/>', login: '<path d="M15 4h4v16h-4"/><path d="M8 8l4 4-4 4M12 12H3"/>', arrow: '<path d="M5 12h14M13 6l6 6-6 6"/>', menu: '<path d="M4 6h16M4 12h16M4 18h16"/>', file: '<path d="M6 3h8l5 5v13H6z"/><path d="M14 3v5h5"/>', leaf: '<path d="M5 19c0-9 5-14 15-14 0 10-5 15-14 15"/><path d="M5 19l7-7"/>', star: '<path d="M12 3l2.7 5.8 6.3.8-4.6 4.4 1.2 6.3L12 17.2 6.4 20.3l1.2-6.3L3 9.6l6.3-.8z"/>', key: '<circle cx="8" cy="15" r="4"/><path d="M11 12l9-9M16 7l3 3"/>', globe: '<circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c3 3 3 15 0 18M12 3c-3 3-3 15 0 18"/>', target: '<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1"/>' };
  const ic = (n, s = 24) => `<svg width="${s}" height="${s}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${P[n] || P.book}</svg>`;
  const inl = (n, s = 15) => ic(n, s).replace('<svg', '<svg style="display:inline;vertical-align:-2px;margin-right:7px"');

  /* ---------- photographs (the school's own) ---------- */
  const IMG = { building: ['images/bg_00.jpg', 'School building, Kanipakam Road'], campus: ['images/bg_02.jpg', 'Campus and school buses'] };
  const GAL = [
    ['images/bg_00.jpg', 'Our school building'], ['images/bg_02.jpg', 'Campus and school buses'], ['images/event/DSC_0043.jpg', 'Annual Day Celebrations'], ['images/event/DSC_0219.jpg', 'Classical dance – Annual Day'],
    ['images/event/DSC_0765.jpg', 'Karate champions'], ['images/event/DSC_0436.jpg', 'Independence Day celebrations'], ['images/event/DSC_1373.jpg', 'Independence Day – cultural programme'], ['images/event/DSC_0396_1.jpg', 'Independence Day march-past'],
    ['images/event/DSC_0855.jpg', 'Sankranti celebrations'], ['images/event/DSC_0743.jpg', 'Sankranti – traditional dance'], ['images/event/DSC_0607.jpg', 'Teachers in traditional attire'], ['images/event/DSC_0386.jpg', 'Festival celebrations with staff'],
    ['images/event/148.jpg', 'Fancy Dress Competition'], ['images/event/DSC_0708.jpg', 'Students in fancy dress'], ['images/event/DSC_0344.jpg', 'UKG Convocation Day'], ['images/event/DSC_0407.jpg', 'UKG Convocation Day – performance'],
    ['images/event/DSC_0429.jpg', 'UKG Convocation Day'], ['images/event/DSC_0274.jpg', 'Karate demonstration'], ['images/event/DSC_0251.jpg', 'Annual Day – students on stage'], ['images/event/DSC_0004.jpg', 'Prizes and trophies'],
    ['images/event/DSC_0181.jpg', 'Cultural programme'], ['images/event/DSC_0002.jpg', 'Annual Day stage'], ['images/event/DSC_0525.jpg', 'Independence Day – dance'], ['images/event/DSC_1327.jpg', 'Independence Day – karate display'], ['images/event/DSC_0687.jpg', 'Student activity day'], ['images/event/DSC_0850.jpg', 'School gathering']
  ];
  const img = (i, cls = '') => `<div class="photo ${cls}"><img src="${GAL[i][0]}" alt="${esc(GAL[i][1])}" loading="lazy"></div>`;

  /* ---------- data ---------- */
  const db = () => S.db(); const T = () => C.today();
  const pubAnn = () => db().announcements.filter(a => a.public).sort((a, b) => (b.pinned - a.pinned) || b.ts.localeCompare(a.ts));
  const evs = () => db().events.filter(e => ['event', 'ptm', 'special'].includes(e.type) && e.audience !== 'staff');
  const upcoming = () => evs().filter(e => e.end >= T()).sort((a, b) => a.date.localeCompare(b.date));

  /* ---------- layout ---------- */
  const NAV = [['home', 'Home'], ['About', [['about', 'About School'], ['principal', 'Chairman & Principal'], ['vision', 'Vision & Values']]], ['Academics', [['academics', 'Academics'], ['classes', 'Classes Offered'], ['faculty', 'Faculty']]], ['Campus', [['facilities', 'Facilities'], ['infrastructure', 'Infrastructure'], ['labs', 'Laboratories'], ['library', 'Library'], ['transport', 'Transport'], ['sports', 'Sports']]], ['Life at School', [['achievements', 'Achievements'], ['events', 'Events'], ['gallery', 'Gallery'], ['news', 'News & Announcements']]], ['admissions', 'Admissions'], ['Contact', [['contact', 'Contact Us'], ['location', 'School Location'], ['disclosure', 'Mandatory Disclosure']]]];
  function header(cur) {
    const link = (id, l) => `<a href="#/${id}" class="${id === cur ? 'on' : ''}">${l}</a>`;
    return `<div class="util"><div class="wrap"><div class="l"><span>${inl('pin')}${esc(SCH.address)}</span><span>${inl('phone')}${SCH.phone} · ${SCH.mobile}</span><span>${inl('mail')}${SCH.email}</span></div><a href="portal.html">${inl('login')}Parent / Student / Staff Login</a></div></div>
    <header class="site"><div class="wrap"><a class="brand" href="#/home"><img src="${SCH.logo}" alt="${esc(SCH.name)} logo"><div class="nm"><b>Rainbow's</b><span>English Medium High School</span></div></a>
    <nav class="main" id="mainnav">${NAV.map(n => Array.isArray(n[1]) ? `<div class="dd"><a href="#" onclick="return false" class="${n[1].some(x => x[0] === cur) ? 'on' : ''}">${n[0]} ▾</a><div class="menu">${n[1].map(x => link(x[0], x[1])).join('')}</div></div>` : link(n[0], n[1])).join('')}</nav>
    <div class="nav-cta"><a class="btn sm blue keep" href="#/login">${inl('login')}Login</a><button class="burger" id="burger" aria-label="Menu">${ic('menu', 22)}</button></div></div></header>`;
  }
  function footer() {
    return `<footer class="site"><div class="rainbow"></div><div class="wrap" style="padding-top:60px"><div class="cols"><div><div class="logo-chip"><img src="${SCH.logo}" alt="${esc(SCH.name)}"></div><p style="color:#fff;font-family:var(--head);font-weight:600;margin-bottom:6px">${esc(SCH.name)}</p><p>${esc(SCH.address)}</p></div>
    <div><h4>Explore</h4>${[['about', 'About Us'], ['academics', 'Academics'], ['facilities', 'Facilities'], ['achievements', 'Achievements'], ['gallery', 'Gallery'], ['news', 'News']].map(l => `<a href="#/${l[0]}">${l[1]}</a>`).join('')}</div>
    <div><h4>Parents</h4>${[['admissions', 'Admissions'], ['transport', 'Transport'], ['events', 'Events'], ['contact', 'Contact Us'], ['disclosure', 'Mandatory Disclosure'], ['login', 'Parent Portal Login']].map(l => `<a href="#/${l[0]}">${l[1]}</a>`).join('')}</div>
    <div><h4>Contact</h4><p>${inl('phone')}${SCH.phone}<br>${inl('phone')}${SCH.mobile}<br>${inl('mail')}${SCH.email}<br>${inl('clock')}${SCH.hours}</p></div></div>
    <div class="bar"><span>© ${new Date().getFullYear()} ${esc(SCH.name)}. All rights reserved.</span><span>${esc(SCH.address)}</span></div></div></footer>`;
  }
  const hero = (title, lead, crumb, bg) => `<section class="page-hero">${arcs()}<div class="wrap"><div><div class="crumb"><a href="#/home">Home</a> › ${esc(crumb || title)}</div><h1>${title}</h1>${lead ? `<p>${lead}</p>` : ''}</div><div class="ph"><img src="${bg || IMG.building[0]}" alt=""></div></div></section>`;
  const sec = (inner, cls = '') => `<section class="sec ${cls}"><div class="wrap">${inner}</div></section>`;
  const head = (eb, t, p, c = '') => `<div class="sec-head ${c}">${eb ? `<div class="eyebrow">${eb}</div>` : ''}<h2>${t}</h2>${p ? `<p>${p}</p>` : ''}</div>`;
  const split = (eb, t, body, photo, rev) => `<div class="split ${rev ? 'rev' : ''}"><div>${eb ? `<div class="eyebrow">${eb}</div>` : ''}<h2 style="font-size:clamp(25px,3vw,34px);margin-bottom:16px">${t}</h2>${body}</div>${photo}</div>`;
  const checks = l => `<ul class="check">${l.map(x => `<li><span>${x}</span></li>`).join('')}</ul>`;
  const COL = ['#f0245f', '#fb8c00', '#43a047', '#1e9be8', '#7e57c2', '#00acc1'];
  const arcs = cls => `<svg class="arcs ${cls || ''}" viewBox="0 0 400 400" aria-hidden="true"><g fill="none" stroke-width="30">${[['#f0245f', 185], ['#ffb81c', 155], ['#43a047', 125], ['#1e9be8', 95], ['#7e57c2', 65]].map(a => `<circle cx="200" cy="200" r="${a[1]}" stroke="${a[0]}"/>`).join('')}</g></svg>`;
  const wave = (fill = '#fff') => `<svg class="wave" viewBox="0 0 1440 70" preserveAspectRatio="none" aria-hidden="true"><path style="fill:${fill}" d="M0 38 C200 86 420 4 700 34 C980 64 1200 8 1440 40 L1440 70 L0 70Z"/></svg>`;
  const cards = (arr, cols = 3) => `<div class="grid g${cols}">${arr.map((c, i) => `<div class="feat" style="--c:${COL[i % 6]}"><div class="ico">${ic(c[0], 26)}</div><h3>${c[1]}</h3><p class="muted" style="margin:0">${c[2]}</p></div>`).join('')}</div>`;
  const evRow = e => { const d = C.pd(e.date); return `<div class="list-row"><div class="datebox"><b>${d.getDate()}</b><span>${C.MONTHS[d.getMonth()].slice(0, 3)}</span></div><div><b style="color:var(--navy-d)">${esc(e.title)}</b><div class="muted small">${C.fmtDateLong(e.date)}${e.end !== e.date ? ' – ' + C.fmtDate(e.end) : ''}</div>${e.desc ? `<div class="small" style="margin-top:3px;color:var(--text-2)">${esc(e.desc)}</div>` : ''}</div></div>`; };
  const annRow = a => `<div class="list-row"><div class="datebox pink"><b>${C.pd(a.ts.slice(0, 10)).getDate()}</b><span>${C.MONTHS[C.pd(a.ts.slice(0, 10)).getMonth()].slice(0, 3)}</span></div><div><b style="color:var(--navy-d)">${esc(a.title)}</b><div class="small" style="color:var(--text-2)">${esc(a.body)}</div></div></div>`;
  const enqForm = (id, label) => `<form class="form" id="${id}" novalidate><div class="row2"><div><label>Child's name *</label><input name="child" required></div><div><label>Class applying for *</label><select name="grade">${['LKG', 'UKG'].concat([1, 2, 3, 4, 5, 6, 7, 8, 9, 10].map(g => 'Class ' + g)).map(g => `<option>${g}</option>`).join('')}</select></div></div><div class="row2"><div><label>Parent / guardian name *</label><input name="parent" required></div><div><label>Mobile number *</label><input name="phone" inputmode="numeric" maxlength="10" placeholder="10-digit mobile" required></div></div><div><label>Email *</label><input name="email" type="email" required></div><div><label>Message</label><textarea name="message" rows="3" placeholder="Tell us how we can help"></textarea></div><div class="err" style="color:#b3261e;font-size:14px"></div><button class="btn primary" type="submit">${label}</button></form>`;
  const mapEmbed = () => `<div class="map"><iframe title="School location map" loading="lazy" referrerpolicy="no-referrer-when-downgrade" src="https://www.google.com/maps?q=${encodeURIComponent("Rainbow's English Medium High School, Kanipakam Road, Chittoor 517004")}&output=embed"></iframe></div>`;
  const VALUES = [['Responsibility', 'Taking ownership of studies, actions and the school community.'], ['Integrity', 'Honesty and strong moral principles in everything we do.'], ['Caring', 'Kindness and concern for classmates, teachers and family.'], ['Respectful', 'Courtesy towards elders, teachers, peers and the environment.'], ['Academic', 'A love of learning and the drive to do one’s best.'], ['Cooperative', 'Working together – students, parents and teachers as one team.']];

  /* ---------- pages ---------- */
  const PAGES = {
    home() {
      const ups = upcoming().slice(0, 4), anns = pubAnn().slice(0, 4); const yrs = new Date().getFullYear() - SCH.est;
      const stage = (n, t, p, c, bg) => `<div class="stage" style="--c:${c};--bg2:${bg}"><small>${n}</small><h3>${t}</h3><p>${p}</p></div>`;
      return `<section class="hero">${arcs()}<i class="cloud c1"></i><i class="cloud c2"></i><div class="wrap"><div class="fade"><div class="tag"><i>${ic('pin', 14)}</i>Kanipakam Road, Chittoor</div>
        <h1>Excellence in <span class="rb">Learning</span></h1><div class="sub">Rainbow's English Medium High School</div><p class="lead">A caring English-medium school where creativity, observation and knowledge grow together — and where parents, students and teachers work as one team.</p>
        <div class="cta"><a class="btn primary" href="#/admissions">Admission enquiry ${ic('arrow', 18)}</a><a class="btn blue" href="#/login">${inl('login', 17)}Parent / Student Login</a></div>
        <div class="trust"><div><b>${yrs}+</b><span>Years of service</span></div><div><b>LKG–10</b><span>English medium</span></div><div><b>6</b><span>Core values</span></div></div></div>
        <div class="collage fade"><div class="p p1"><img src="${GAL[3][0]}" alt="${GAL[3][1]}"></div><div class="p p2"><img src="${GAL[4][0]}" alt="${GAL[4][1]}"></div><div class="p p3"><img src="${GAL[8][0]}" alt="${GAL[8][1]}"></div><div class="p p4"><img src="${GAL[12][0]}" alt="${GAL[12][1]}"></div>
        <div class="badge b1"><i style="background:#f0245f">${ic('star', 18)}</i>Annual Day</div><div class="badge b2"><i style="background:#43a047">${ic('trophy', 18)}</i>Karate champions</div></div></div>${wave('#fff')}</section>
      ${sec(`${head('Why Rainbow\'s', 'Everything a child needs to grow', 'Learning, play, culture and values — all under one roof.', 'center')}${cards([['book', 'Strong academics', 'English-medium teaching with regular tests and attention to every child.'], ['heart', 'Values first', 'The RICRAC values guide behaviour, respect and responsibility.'], ['trophy', 'Sports & karate', 'Physical education, karate training and competitions through the year.'], ['palette', 'Culture & celebrations', 'Annual Day, national festivals, Sankranti and fancy dress competitions.'], ['users', 'Parents as partners', 'Regular updates and a school portal for attendance, results and fees.'], ['bus', 'Safe travel', 'School buses carry students to and from school.']])}`)}
      <section class="ribbon"><div class="wrap"><div class="grid g4">${[[yrs + '+', 'Years of service'], ['LKG – 10', 'Classes'], ['English', 'Medium of instruction'], ['6', 'Core values · RICRAC']].map(x => `<div class="stat"><b>${x[0]}</b><span>${x[1]}</span></div>`).join('')}</div></div></section>
      ${sec(split('Welcome', 'A school where parents, students and teachers are one team', `<p>At Rainbow's English Medium High School we aim to develop <b>all-round capability — creativity, observation and knowledge empowerment</b> — in every child.</p><p>We believe parents, students and the school authorities are a team and must complement each other's efforts. That partnership, built over ${yrs} years, is the strength of our school.</p>${checks(['English-medium education from LKG to Class 10', 'Caring teachers who know every child', 'Sports, karate, dance and celebrations all through the year'])}<div style="margin-top:26px"><a class="btn primary" href="#/about">Read our story</a></div>`, `<div class="photo"><img src="${IMG.campus[0]}" alt="${IMG.campus[1]}" loading="lazy"></div>`, true), 'warm')}
      ${sec(`${head('Our values', 'The RICRAC way', 'Six values that shape every student who walks through our gates.', 'center')}<div class="values">${VALUES.map((v, i) => `<div class="val" style="--c:${COL[i]}"><i>${v[0][0]}</i><div><h3>${v[0]}</h3><p class="muted" style="margin:0">${v[1]}</p></div></div>`).join('')}</div>`, 'pinkish')}
      ${sec(`${head('Classes', 'From first steps to Class 10', null, 'center')}<div class="stages">${stage('LKG – UKG', 'Pre-primary', 'Songs, stories, play and first letters in a happy classroom.', '#f0245f', '#fff0f4') + stage('Classes 1 – 5', 'Primary', 'Reading, writing, numbers and a love of learning.', '#fb8c00', '#fff3e2') + stage('Classes 6 – 7', 'Upper primary', 'Subject-wise learning, projects and confidence.', '#43a047', '#e9f6ea') + stage('Classes 8 – 10', 'High school', 'Concept clarity and preparation for the Class 10 examination.', '#1e9be8', '#e6f4fd')}</div><div style="text-align:center;margin-top:30px"><a class="btn" href="#/classes">See classes offered</a></div>`)}
      ${sec(`${head('Life at school', 'Moments that make us smile', 'Annual Day, national festivals, Sankranti and karate — a few glimpses from our school.')}<div class="mosaic">${[[3, 'Annual Day'], [4, 'Karate champions'], [8, 'Sankranti'], [5, 'Independence Day'], [12, 'Fancy dress']].map(m => `<a href="#/gallery"><img src="${GAL[m[0]][0]}" alt="${m[1]}" loading="lazy"><span>${m[1]}</span></a>`).join('')}</div><div style="text-align:center;margin-top:32px"><a class="btn blue" href="#/gallery">Open the gallery</a></div>`, 'tint')}
      ${sec(`<div class="grid g2" style="gap:44px;align-items:start"><div>${head('Notice board', 'Announcements')}<div class="card"><div class="pad" style="padding:6px 24px">${anns.length ? anns.map(annRow).join('') : '<p class="muted" style="padding:16px 0">No announcements at the moment.</p>'}</div></div><div style="margin-top:16px"><a class="btn sm" href="#/news">All announcements</a></div></div><div>${head('Calendar', 'Upcoming events')}<div class="card"><div class="pad" style="padding:6px 24px">${ups.map(evRow).join('') || '<p class="muted" style="padding:16px 0">No upcoming events.</p>'}</div></div><div style="margin-top:16px"><a class="btn sm" href="#/events">All events</a></div></div></div>`)}
      ${sec(`${head('Leadership', 'Guided by experience', null, 'center')}<div class="grid g2" style="max-width:860px;margin:auto">${[[SCH.chairman, 'Chairman', SCH.chairmanQual, 'MM'], [SCH.principal, 'Principal', 'Academic head of the school', 'SS']].map(p => `<div class="card"><div class="pad"><div class="lead-card"><div class="avatar">${p[3]}</div><div><h3 style="font-size:20px;margin:0">${esc(p[0])}</h3><div style="color:var(--pink);font-weight:700">${p[1]}</div><div class="muted small">${esc(p[2])}</div></div></div></div></div>`).join('')}</div><div style="text-align:center;margin-top:26px"><a class="btn" href="#/principal">Read their message</a></div>`, 'warm')}
      <section class="sec cta-band">${arcs()}<div class="wrap"><div class="grid g2" style="gap:50px;align-items:center"><div><div class="eyebrow">Admissions</div><h2 style="font-size:clamp(28px,3.8vw,42px)">Join the Rainbow's family</h2><p style="color:#e3f1ff;font-size:18px;margin:14px 0 22px">Send us an enquiry or visit the school office on Kanipakam Road. We will be happy to show you around.</p><p style="color:#fff;font-weight:700">${inl('phone', 17)}${SCH.phone} &nbsp;·&nbsp; ${SCH.mobile}</p><a class="btn light" href="#/admissions" style="margin-top:10px">Admission details</a></div><div class="card"><div class="pad"><h3>Quick enquiry</h3><p class="muted small">Leave your details and our office will contact you.</p>${enqForm('enqHome', 'Send enquiry')}</div></div></div></div></section>
      ${sec(`<div class="grid g3">${[['pin', 'Visit us', esc(SCH.address)], ['phone', 'Call us', SCH.phone + '<br>' + SCH.mobile], ['mail', 'Write to us', SCH.email]].map((c, i) => `<div class="feat" style="--c:${COL[i + 1]}"><div class="cinfo"><div class="ico" style="margin:0;flex:none">${ic(c[0], 24)}</div><div><h3 style="margin:0 0 2px">${c[1]}</h3><p class="muted small" style="margin:0">${c[2]}</p></div></div></div>`).join('')}</div><div style="margin-top:30px">${mapEmbed()}</div>`)}`;
    },
    about() {
      return hero('About our school', `Serving the children of Chittoor for over ${new Date().getFullYear() - SCH.est} years.`, 'About Us', IMG.campus[0]) + sec(split('Our story', "Rainbow's English Medium High School", `<p>Rainbow's English Medium High School stands on Kanipakam Road, Chittoor, and has been educating children in the English medium for more than ${new Date().getFullYear() - SCH.est} years. The school is recognised by the State Board and is run under the guidance of our Chairman, <b>${SCH.chairman}</b> (${SCH.chairmanQual}), and Principal, <b>${SCH.principal}</b>.</p><p>We want every child to grow in creativity, observation and knowledge — and to become a responsible, caring and capable citizen. We do this together with parents, who are partners in each child's progress.</p>${checks(['Recognised by the State Board', 'English-medium classes from LKG to Class 10', 'Regular cultural programmes, national festivals and sports', 'Karate training and competitions', 'School buses for students'])}`, img(1, ''))) +
        sec(`${head('Our community', 'Celebrating together', 'Festivals, performances and prize days bring our whole school family together.', 'center')}<div class="grid g3">${img(2)}${img(8)}${img(5)}</div>`, 'tint');
    },
    principal() {
      return hero('Chairman & Principal', 'The people who guide our school.', 'Chairman & Principal', IMG.building[0]) + sec(`<div class="grid g2" style="gap:30px">${[[SCH.chairman, 'Chairman', SCH.chairmanQual, 'MM'], [SCH.principal, 'Principal', '', 'SS']].map(p => `<div class="card"><div class="pad"><div class="lead-card"><div class="avatar">${p[3]}</div><div><h3 style="font-size:22px;margin:0">${esc(p[0])}</h3><div style="color:var(--pink);font-weight:600">${p[1]}</div>${p[2] ? `<div class="muted small">${esc(p[2])}</div>` : ''}</div></div></div></div>`).join('')}</div>` +
        `<div style="max-width:800px;margin:50px auto 0"><div class="quote">“Parents, students and the school authorities are a team, and we have to complement each other's efforts.”</div><div style="margin-top:28px;font-size:17px"><p>Our aim is to develop <b>all-round capability, including creativity, observation and knowledge empowerment</b>, in every student.</p><p>We encourage every child to live by our six values — Responsibility, Integrity, Caring, Respectful, Academic and Cooperative — so that they grow into confident, capable and kind leaders of tomorrow.</p><p>We invite parents to stay closely involved in their child's education and to work with our teachers throughout the year. Our school portal keeps you informed about attendance, results and fees.</p><p><b style="font-family:var(--head);color:var(--navy-d)">Management & Principal</b><br><span class="muted">${esc(SCH.name)}</span></p></div></div>`);
    },
    vision() {
      return hero('Vision & values', 'What we want for every child, and how we get there.', 'Vision & Values', IMG.campus[0]) + sec(split('Our vision', 'All-round capability for every child', `<p style="font-size:18px">We aim to develop <b>all-round capability, including creativity, observation and knowledge empowerment</b>, so that our students become the leaders of the future.</p><p>Parents, students and the school authorities are a team, and we complement each other's efforts. Education works best when home and school pull in the same direction.</p>`, img(6), true)) + sec(`${head('Our values', 'R · I · C · R · A · C', 'The RICRAC framework guides our teaching, discipline and school culture.', 'center')}<div class="values">${VALUES.map((v, i) => `<div class="val" style="--c:${COL[i]}"><i>${v[0][0]}</i><h3>${v[0]}</h3><p class="muted" style="margin:0">${v[1]}</p></div>`).join('')}</div>`, 'tint');
    },
    academics() {
      return hero('Academics', 'English-medium education with strong foundations from LKG to Class 10.', 'Academics') + sec(`${head('Our approach', 'Learning that builds understanding')}${cards([['book', 'Strong basics', 'Reading, writing, language and mathematics are built carefully in the early classes.'], ['flask', 'Learning by doing', 'Activities, projects and practical work help children observe and understand.'], ['users', 'Individual attention', 'Class teachers track every child’s progress and stay in touch with parents.'], ['monitor', 'Computers', 'Computer education is part of the school timetable.'], ['palette', 'Co-curricular life', 'Dance, drama, art, karate and celebrations develop confidence and creativity.'], ['heart', 'Values', 'Moral education and the RICRAC values are part of daily school life.']])}`) +
        sec(`<div class="grid g2" style="gap:40px"><div>${head('Subjects', 'What students study')}<table class="tbl"><thead><tr><th>Subject</th></tr></thead><tbody>${C.SUBJECTS.map(s => `<tr><td>${s.name}</td></tr>`).join('')}</tbody></table></div><div>${head('Assessment', 'Regular evaluation')}<table class="tbl"><thead><tr><th>Examination</th></tr></thead><tbody>${db().exams.map(x => `<tr><td>${esc(x.name)}</td></tr>`).join('')}</tbody></table><p class="muted small" style="margin-top:12px">Marks, report cards and hall tickets are available to parents on the school portal.</p></div></div>`, 'tint');
    },
    classes() {
      return hero('Classes offered', 'From pre-primary to high school.', 'Classes Offered') + sec(`<table class="tbl"><thead><tr><th>Stage</th><th>Classes</th><th>Focus</th></tr></thead><tbody>${[['Pre-primary', 'LKG – UKG', 'Play-way learning, language, number sense, songs, activities'], ['Primary', 'Classes 1 – 5', 'Reading, writing, mathematics, environmental science, English, Telugu, Hindi'], ['Upper primary', 'Classes 6 – 7', 'Subject-wise learning in languages, mathematics, science and social studies'], ['High school', 'Classes 8 – 10', 'Concept clarity, regular tests and preparation for the Class 10 public examination']].map(r => `<tr><td><b>${r[0]}</b></td><td>${r[1]}</td><td>${r[2]}</td></tr>`).join('')}</tbody></table><p class="muted small" style="margin-top:12px">Please confirm class-wise sections and availability of seats with the school office.</p>`) + sec(split('', 'UKG Convocation Day', '<p>Every year our youngest students celebrate their UKG Convocation Day on stage in cap and gown, with songs, dances and certificates, in front of proud parents.</p>', img(14)), 'tint');
    },
    faculty() {
      const depts = Array.from(new Set(S.teachers().map(t => t.dept)));
      return hero('Faculty', 'Dedicated teachers across every subject.', 'Faculty') + sec(`${head('Leadership', 'Management & Principal')}<div class="grid g2" style="margin-bottom:50px">${[[SCH.chairman, 'Chairman', SCH.chairmanQual, 'MM'], [SCH.principal, 'Principal', 'Academic head of the school', 'SS']].map(p => `<div class="card"><div class="pad"><div class="lead-card"><div class="avatar">${p[3]}</div><div><h3 style="font-size:20px;margin:0">${esc(p[0])}</h3><div style="color:var(--pink);font-weight:600">${p[1]}</div><div class="muted small">${esc(p[2])}</div></div></div></div></div>`).join('')}</div>${head('Our departments', 'Teaching staff')}${cards([['book', 'English', 'Spoken and written English from the early classes.'], ['globe', 'Languages', 'Telugu and Hindi language teaching.'], ['target', 'Mathematics', 'Concept-based teaching and regular practice.'], ['flask', 'Science', 'Observation, experiments and understanding.'], ['users', 'Social Studies', 'History, geography, civics and our environment.'], ['monitor', 'Computer Science', 'Computer education for every class.'], ['trophy', 'Physical Education', 'Sports, drill and karate.'], ['palette', 'Arts & Moral Science', 'Art, craft, music, dance and values.']], 4)}`);
    },
    facilities() {
      return hero('Facilities', 'A safe, green campus designed for children.', 'Facilities', IMG.campus[0]) + sec(cards([['building', 'Spacious building', 'A multi-storey school building with airy classrooms and corridors around an open courtyard.'], ['leaf', 'Green surroundings', 'Trees and plants around the campus keep the school fresh and pleasant.'], ['bus', 'School buses', 'A fleet of school buses carries students safely to and from school.'], ['palette', 'Stage & open assembly area', 'A covered stage in the courtyard hosts our Annual Day, festivals and competitions.'], ['monitor', 'Computer education', 'Students learn computers as part of the school curriculum.'], ['shield', 'Safety', 'Fire safety, building safety and safe drinking water certificates are on record.']]) + `<div class="grid g3" style="margin-top:44px">${img(0)}${img(1)}${img(20)}</div>`);
    },
    infrastructure() {
      return hero('Infrastructure', 'A well-kept campus on Kanipakam Road.', 'Infrastructure', IMG.building[0]) + sec(split('Our campus', 'Space to learn, play and celebrate', `<p>Our white multi-storey building surrounds a central courtyard where assemblies, drill, sports and celebrations take place. Wide verandahs and tree-lined surroundings keep the campus bright and airy.</p>${checks(['Classrooms across multiple floors', 'Open courtyard with covered stage', 'Compound wall and gated entry for safety', 'Parking and bus bay inside the campus', 'Building safety, fire safety and drinking-water certificates'])}<p style="margin-top:16px"><a href="#/disclosure">See mandatory disclosure documents →</a></p>`, img(0), true));
    },
    labs() {
      return hero('Laboratories', 'Learning by observing and doing.', 'Laboratories') + sec(split('Hands-on learning', 'Science and computer practice', `<p>Observation is one of the pillars of our vision. Students are encouraged to see, test and ask questions, through experiments, models and charts, and through regular computer practice.</p>${checks(['Science practical work and demonstrations', 'Computer education for students', 'Exhibitions where students present their own models and projects'])}`, img(24)));
    },
    library() {
      return hero('Library', 'Building a habit of reading.', 'Library') + sec(split('Reading', 'Books for every age', `<p>Reading is the base of all learning. Students are encouraged to read story books, reference books and magazines beyond their textbooks, and teachers guide them towards good reading habits.</p>${checks(['Story books and reference books for different classes', 'Reading encouraged through class activities', 'Parents are welcome to support reading at home'])}`, img(13), true));
    },
    transport() {
      return hero('Transport', 'School buses for safe, regular travel.', 'Transport', IMG.campus[0]) + sec(split('Getting to school', 'Our yellow school buses', `<p>Rainbow's school buses bring students to and from school from different parts of Chittoor and nearby areas. Buses are parked inside the school campus, which has a gated entry.</p>${checks(['Buses marked with the school name and route number', 'Pick-up and drop timings shared with parents', 'Transport fee is added to the school fee schedule'])}<p style="margin-top:16px">For routes, timings and fee, please contact the school office: <b>${SCH.phone}</b>.</p>`, `<div class="photo"><img src="${IMG.campus[0]}" alt="${IMG.campus[1]}" loading="lazy"></div>`));
    },
    sports() {
      return hero('Sports & karate', 'Fitness, discipline and confidence.', 'Sports', 'images/event/DSC_0765.jpg') + sec(split('Physical education', 'Strong body, strong mind', `<p>Sports and physical education are part of school life. Our students also train in <b>karate</b> and take part in belt gradings and open championships, bringing home medals, certificates and trophies for the school.</p>${checks(['Physical education periods', 'Karate training and belt examinations', 'Drill and physical displays on national days', 'Games and competitions during school events'])}`, img(4), true)) + sec(`<div class="grid g3">${img(17)}${img(23)}${img(7)}</div>`, 'tint');
    },
    achievements() {
      return hero('Achievements', 'Our students and their success.', 'Achievements', 'images/event/DSC_0765.jpg') + sec(split('Karate', 'Champions in the ring', `<p>Our karate students won medals and a team trophy at the <b>Open Goju-Ryu Karate-Do Championship 2019</b>, and many of them hold coloured belts earned through regular gradings.</p>`, img(4)) + `<div style="margin-top:56px">${split('Annual Day', 'Prizes and recognition', '<p>Every year at Annual Day we recognise students for academics, sports, discipline and co-curricular activities with prizes and trophies.</p>', img(19), true)}</div>`);
    },
    events() {
      const ups = upcoming();
      return hero('Events', 'Celebrations, competitions and meetings through the year.', 'Events') + sec(`<div class="grid g2" style="gap:44px;align-items:start"><div>${head('Calendar', 'Upcoming events')}<div class="card"><div class="pad" style="padding:6px 24px">${ups.map(evRow).join('') || '<p class="muted" style="padding:16px 0">No upcoming events.</p>'}</div></div></div><div>${head('Every year', 'Our celebrations')}${checks(['Annual Day Celebrations', 'Independence Day and Republic Day', 'Sankranti celebrations with rangoli', "Teachers' Day and Children's Day", 'Fancy Dress Competition', 'UKG Convocation Day', 'Karate belt gradings and tournaments'])}<div class="grid g2" style="margin-top:26px">${img(8)}${img(12)}</div></div></div>`);
    },
    gallery() { return hero('Gallery', 'Moments from school life.', 'Gallery', 'images/event/DSC_0043.jpg') + sec(`<div class="gal">${GAL.map((g, i) => `<button data-light="${i}"><img src="${g[0]}" alt="${esc(g[1])}" loading="lazy"><span>${esc(g[1])}</span></button>`).join('')}</div>`); },
    news() {
      const a = pubAnn();
      return hero('News & announcements', 'Notices for parents and the community.', 'News') + sec(`<div class="grid g2" style="gap:44px;align-items:start"><div>${head('Notice board', 'Announcements')}<div class="card"><div class="pad" style="padding:6px 24px">${a.map(annRow).join('') || '<p class="muted" style="padding:16px 0">No announcements.</p>'}</div></div></div><div>${head('Calendar', 'Upcoming events')}<div class="card"><div class="pad" style="padding:6px 24px">${upcoming().slice(0, 5).map(evRow).join('')}</div></div></div></div>`);
    },
    admissions() {
      return hero('Admissions', 'We welcome children to the Rainbow\'s family.', 'Admissions', IMG.campus[0]) + sec(`${head('Process', 'How to join')}<div class="steps">${[['Enquire', 'Send the enquiry form or visit the school office on Kanipakam Road.'], ['Meet us', 'Meet the Principal, see the school and learn about classes and fees.'], ['Interaction', 'A friendly interaction with the child, and a short assessment for higher classes.'], ['Enrol', 'Submit documents and pay the admission fee to confirm the seat.']].map(s => `<div class="st"><h3>${s[0]}</h3><p class="muted small" style="margin:0">${s[1]}</p></div>`).join('')}</div>`) +
        sec(`<div class="grid g2" style="gap:44px;align-items:start"><div>${head('Documents', 'What to bring')}${checks(['Birth certificate', 'Aadhaar card of the child (and parents, if available)', 'Transfer certificate and previous report card (for Classes 2 and above)', 'Passport-size photographs', 'Address proof of parents'])}<div class="card" style="margin-top:28px"><div class="pad"><h3>Fee structure</h3><p class="muted" style="margin:0">Fees differ by class and transport. Please contact the school office on <b>${SCH.phone}</b> or <b>${SCH.mobile}</b> for the current fee structure.</p></div></div></div><div>${head('Apply', 'Admission enquiry')}<div class="card"><div class="pad">${enqForm('enqAdm', 'Submit enquiry')}</div></div></div></div>`, 'tint') +
        sec(`<div style="max-width:780px;margin:auto">${head('FAQ', 'Common questions')}<div class="faq">${[['Which classes are available?', 'English-medium classes from LKG up to Class 10. Please confirm seat availability with the school office.'], ['Can I pay fees online?', 'Yes, parents can pay through the parent portal and receive an instant receipt and WhatsApp confirmation.'], ['Is school bus facility available?', 'Yes, school buses are available. Please ask the office about your area.'], ['How do I track my child’s progress?', 'The parent portal shows attendance, timetable, marks, report cards, hall tickets, fees and announcements.']].map(f => `<details><summary>${f[0]}</summary><p>${f[1]}</p></details>`).join('')}</div></div>`);
    },
    contact() {
      return hero('Contact us', 'We would be happy to hear from you.', 'Contact') + sec(`<div class="grid g2" style="gap:44px;align-items:start"><div>${head('Get in touch', 'Send a message')}<div class="card"><div class="pad">${enqForm('enqContact', 'Send message')}</div></div></div><div>${head('School office', 'Reach us')}<div class="grid" style="gap:14px">${[['pin', 'Address', esc(SCH.address)], ['phone', 'Phone', SCH.phone + '<br>' + SCH.mobile], ['mail', 'Email', SCH.email], ['clock', 'Office hours', SCH.hours]].map((c, i) => `<div class="card"><div class="pad" style="display:flex;gap:16px;padding:18px"><div class="ico" style="margin:0;flex:none;width:44px;height:44px;background:${COL[i]}">${ic(c[0], 22)}</div><div><b style="color:var(--navy-d);font-family:var(--head)">${c[1]}</b><div class="muted small">${c[2]}</div></div></div></div>`).join('')}</div></div></div>`);
    },
    location() {
      return hero('School location', 'Kanipakam Road, near Bans Hotel, Chittoor.', 'School Location') + sec(`<div class="grid g2" style="gap:40px;align-items:center">${mapEmbed()}<div>${head('Find us', 'How to reach')}<p style="font-size:17px">${esc(SCH.address)}</p>${checks(['On Kanipakam Road, near Bans Hotel', 'Chittoor town – 517004', 'Call the office for directions: ' + SCH.phone])}<div style="margin-top:22px;display:flex;gap:12px;flex-wrap:wrap"><a class="btn primary" target="_blank" rel="noopener" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent("Rainbow's English Medium High School Kanipakam Road Chittoor")}">${inl('pin', 17)}Open in Google Maps</a><a class="btn" href="#/contact">Contact us</a></div></div></div>`);
    },
    disclosure() {
      const docs = [['State Board Recognition', 'StateBoardRecogniation'], ['No Objection Certificate', 'NOC'], ['Land Certificate', 'LandCertificate'], ['Building Safety Certificate', 'BuildingSafetyCertificate'], ['Fire Safety Certificate', 'FireSafetyCertificate'], ['Safe Drinking Water and Sanitary Certificate', 'SafeDrinking_SanitaryCertificate'], ['Water Sample Test Certificate', 'WaterSampleTestCertificate'], ['Society Registration Certificate', 'SocietyRegistrationCertificate']];
      return hero('Mandatory disclosure', 'Certificates and documents of the school, open to parents and the public.', 'Mandatory Disclosure') + sec(`<div class="grid g2">${docs.map(d => `<a class="doc" href="files/${d[1]}.pdf" target="_blank" rel="noopener"><div class="ico">${ic('file', 20)}</div><div class="grow" style="flex:1"><b style="font-family:var(--head);color:var(--navy-d)">${d[0]}</b><div class="muted small">PDF document · tap to open</div></div>${ic('arrow', 18)}</a>`).join('')}</div>`);
    },
    login() {
      const R = [['Parents & Students', 'users', 'See attendance, timetable, results, hall tickets, fee receipts and school notices. Pay fees online.', 'Sign in with your registered mobile number (parents) or admission number (students).'], ['Teachers', 'cap', 'Mark attendance, enter marks, see your timetable and classes.', 'Sign in with the username given by the school.'], ['Office & Management', 'building', 'Principal, Dean, Accountant, operations staff and administrators.', 'Sign in with your staff username.']];
      return hero('School portal', 'One place for parents, students, teachers and staff.', 'School Portal') + sec(`<div class="grid g3">${R.map((r, i) => `<a class="card hover" href="portal.html" style="color:inherit"><div class="pad"><div class="ico" style="background:${COL[i]}">${ic(r[1], 24)}</div><h3>${r[0]}</h3><p style="margin-bottom:8px">${r[2]}</p><p class="muted small" style="margin:0">${r[3]}</p></div></a>`).join('')}</div><div style="text-align:center;margin-top:34px"><a class="btn primary" href="portal.html">Go to sign in ${ic('arrow', 18)}</a><p class="muted small" style="margin-top:16px">Forgot your password? Please call the school office on <b>${SCH.phone}</b>.</p></div>`);
    }
  };

  /* ---------- router & behaviours ---------- */
  function render() {
    const id = (location.hash.replace(/^#\/?/, '') || 'home').split('?')[0]; const key = PAGES[id] ? id : 'home';
    app.innerHTML = header(key) + `<main class="fade">${PAGES[key]()}</main>` + footer(); document.title = (key === 'home' ? '' : (NAV.flatMap(n => Array.isArray(n[1]) ? n[1] : [n]).find(n => n[0] === key) || [0, key])[1] + ' · ') + SCH.name; window.scrollTo(0, 0);
    bind();
  }
  function bind() {
    const nav = document.getElementById('mainnav'); document.getElementById('burger').onclick = () => nav.classList.toggle('open');
    nav.querySelectorAll('.menu a, nav > a').forEach(a => a.addEventListener('click', () => nav.classList.remove('open')));
    ['enqHome', 'enqAdm', 'enqContact'].forEach(id => { const f = document.getElementById(id); if (!f) return; f.onsubmit = e => { e.preventDefault(); const d = Object.fromEntries(new FormData(f)); const er = f.querySelector('.err'); if (!d.child || !d.parent || !/^\d{10}$/.test(d.phone || '') || !/^\S+@\S+\.\S+$/.test(d.email || '')) { er.textContent = 'Please fill all required fields with a valid 10-digit mobile number and email.'; return; } S.addEnquiry({ child: d.child, grade: d.grade, parent: d.parent, phone: d.phone, email: d.email, message: d.message || '' }); f.innerHTML = `<div class="notice-ok">Thank you, ${esc(d.parent)}. Your enquiry for ${esc(d.child)} (${esc(d.grade)}) has been received. Our office will contact you on ${esc(d.phone)}.</div>`; }; });
    document.querySelectorAll('[data-light]').forEach(b => b.onclick = () => { const g = GAL[+b.dataset.light]; const l = document.createElement('div'); l.className = 'lightbox'; l.innerHTML = `<button class="x" aria-label="Close">×</button><div class="inner"><img src="${g[0]}" alt="${esc(g[1])}"><p>${esc(g[1])}</p></div>`; l.onclick = e => { if (e.target === l || e.target.className === 'x') l.remove(); }; document.body.appendChild(l); });
  }
  document.addEventListener('keydown', e => { if (e.key === 'Escape') { const l = document.querySelector('.lightbox'); l && l.remove(); } });
  window.addEventListener('hashchange', render); render();
})();
